### ISSUE TITLE
Language in pygmentize -L lexers, but minted Error: no lexer for alias

### ISSUE THREAD

**Issue by SamuelMarks** [gpoore/minted#101]
```
$ pygmentize -L lexers | grep Type
    TypeScript (filenames *.ts)
```

```
.pygtex)Error: no lexer for alias 'TypeScript' found


! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.
```

Using`\begin{minted}[mathescape, linenos, numbersep=5pt, gobble=2, frame=lines, framesep=2mm]`. Tried with `{TypeScript}` and `{typescript}`.

**Comment by gpoore** [comment]
It looks like Pygments wants `{ts}`. I would think that `{typescript}`, with or without capitalization, really should have been allowed. You might open an issue at the [Pygments Bitbucket page](https://bitbucket.org/birkenfeld/pygments-main/) to request the additional option.

**Comment by SamuelMarks** [comment]
Thanks, done => https://bitbucket.org/birkenfeld/pygments-main/pull-requests/540/added-more-aliases-for-typescript/diff
