### ISSUE TITLE
escapeinside changes rendering

### ISSUE THREAD

**Issue by koppor** [gpoore/minted#103]
When I use `escapeinside=||` inside an XML, the XML attributes are not rendered correctly.

### Example document:

```latex
\documentclass{article}
\usepackage{minted}

\begin{document}

\begin{minted}{xml}
<top xmlns="ns1"
  xmlns:ns2="ns2" />
\end{minted}

\begin{minted}[escapeinside=||]{xml}
<top xmlns="ns1"
  xmlns:ns2="ns2" />
\end{minted}

\end{document}
```

### Result:

![grabbed_20160103-231622](https://cloud.githubusercontent.com/assets/1366654/12081092/03cb9e6a-b270-11e5-97a9-68534dad9d34.png)

### Environment:

    pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
    Package: minted 2015/09/09 v2.1 Yet another Pygments shim for LaTeX

**Comment by koppor** [comment]
When I try to find out, which token kinds are used, I have no success:

```python
from pygments.style import Style
from pygments.token import Keyword, Name, Comment, String, Error, \
     Number, Operator, Generic, Whitespace, Text, Other, Literal

class FriendlygrayscaleStyle(Style):
    default_style = ""

    styles = {
        Keyword: "#abcdef",
        Name: "#abcdef",
        Comment: "#abcdef",
        String: "#abcdef",
        Generic: "#abcdef",
        Error: "#abcdef",
        Number: "#abcdef",
        Operator: "#abcdef",
        Whitespace: "#abcdef",
        Text: "#abcdef",
        Other: "#abcdef",
        Literal: "#abcdef"
    }
```

Seems to be some kind of other token.

![grabbed_20160104-000130](https://cloud.githubusercontent.com/assets/1366654/12081335/51b0efda-b276-11e5-8a8f-5f361e6915dd.png)

**Comment by koppor** [comment]
Workaround for me (as I use gray scale): Set `Name.Attribute` to `#000000` in the style file.

**Comment by gpoore** [comment]
This looks like a Pygments bug. The way that Pygments does `escapeinside` [can be fragile](https://bitbucket.org/birkenfeld/pygments-main/issues/1118/escapeinside-is-fragile-with-some-lexers), and this looks like another case where it breaks. Somehow, the `xmlns:ns2=` isn't being tokenized at all when `escapeinside` is used. You might open an issue at the [Pygments site](https://bitbucket.org/birkenfeld/pygments-main/).
