### ISSUE TITLE
Documentation request: note on bold font

### ISSUE THREAD

**Issue by cheshire** [gpoore/minted#106]
Hi,
Many default styles in pygments ("trac" in particular) make use of bold font.
However, the default (textlive on latest Ubuntu LTS)  typewriter font in latex does not support it, and it can result in a large amount of confusion ("why are my keywords not being highlighted?").

I would add a note on that in documentation. It can also say that switching to e.g. Inconsolata would solve the problem.

**Comment by gpoore** [comment]
Thanks for pointing this out. I've added a note about font warnings/substitutions in the FAQ.
