### ISSUE TITLE
Please don't report error when `-shell-escape` is not passed in

### ISSUE THREAD

**Issue by xuhdev** [gpoore/minted#107]
The minted package currently stops the compilation if `-shell-escape` is not passed in. However, using the minted package does not mean using the minted environment---the extensions of fancyvrb in this package is also very useful. Can we move the `-shell-escape` check to somewhere at the beginning of the `minted` environment?

**Comment by gpoore** [comment]
If you use `\usepackage[draft]{minted}`, the checks for `-shell-escape` should be disabled.

I'm actually planning to split off the extensions to `fancyvrb` into a separate package, so that they are more accessible. I just haven't gotten around to doing that yet.

**Comment by gpoore** [comment]
I've created a new package [`fvextra`](https://github.com/gpoore/fvextra) that contains most of the `fancyvrb` extensions from `minted` (`breaklines`, etc.), as well as some new ones. The few remaining pieces in `minted` will be moved to `fvextra` when I have a chance, but most of those are low-level things related to `VerbatimOut` that aren't really accessible for users anyway. So `fvextra` should give you what you want in the future, and as a `fancyvrb` extension package, it never needs `-shell-escape` to function.
