### ISSUE TITLE
Custom enviroment for minted

### ISSUE THREAD

**Issue by ReneHollander** [gpoore/minted#108]
Hello,

I am trying to create a custom `code` enviroment:
```tex
\newenvironment{code}[2]
{
  \begin{listing}[H]
  \caption{#2}
  \begin{minted}{#1}
}
{
  \end{minted}
  \end{listing}
}
```
```tex
\begin{code}{c}{Awesome C Code}
int main() {
  printf("Hello World\n");
  return 0;
}
\end{code}
```

Executing it with latexmk I get the following error:
```
! FancyVerb Error:
  Extraneous input ` ' between \begin{minted}[<key=value>] and line end
.
\FV@Error ... {FancyVerb Error:
\space \space #1
}
                                                  
l.85 \begin{code}{c}{Awesome C Code}
```

I also tried to use verbments which did work, but I can't figure out on how to move the caption below the code in the center.

**Comment by klmr** [comment]
See http://tex.stackexchange.com/q/25190/42:

You must use the command `newminted` to create a new minted environment.

**Comment by gpoore** [comment]
This should do what you want:
```latex
\newenvironment{code}[2]
{%
  \VerbatimEnvironment
  \begin{listing}[H]
  \caption{#2}%
  \begin{minted}{#1}%
}
{%
  \end{minted}%
  \end{listing}%
}
```
The `\VerbatimEnvironment` command is needed with custom commands involving `fancyvrb`, so that `fancyvrb` can find the end of the environment. The `%` characters cause newlines to be discarded within comments, so that the newlines aren't converted to spaces and cause trouble.

**Comment by ReneHollander** [comment]
Thank you for your input, it works now! I was about to give up...

**Comment by ReneHollander** [comment]
Sorry for reopening the issue, but I have got two more questions:
1. Why is there an empty line between the code and the caption?
2. Is there a way to get the number of the chapter into the number of the listing?

![listing](https://cloud.githubusercontent.com/assets/5379596/13222737/a74db04a-d981-11e5-9e1f-868fd935c63a.png)

**Comment by gpoore** [comment]
1 -- You can modify spacing by adding `\vspace` between `\end{minted}` and `\end{listing}`.  For example,
```latex
\newenvironment{code}[2]
{%
  \VerbatimEnvironment
  \begin{listing}[H]
  \caption{#2}%
  \begin{minted}{#1}%
}
{%
  \end{minted}%
  \vspace{-10pt}%
  \end{listing}%
}
```
2 -- From the documentation: `\usepackage[chapter]{minted}`

**Comment by ReneHollander** [comment]
Thanks! Sorry for asking so many questions. I am trying to get this working for too long...
One last thing. When using `\begin{lstlisting}` I get my code listings exactly where I want them to be, without any large whitespace areas. I get my code listings where I want if I use `\begin{listing}[H]`, but it produces large amounts of white area on some pages. By using [htp] as suggested [here](http://tex.stackexchange.com/questions/77809/how-do-i-remove-white-space-before-or-after-the-figures-and-tables) I can reduce the white area, but the code listings are all over the place.

**Comment by gpoore** [comment]
The `listing` environment is a float, while `lstlisting` is not by default (unless you use the `float` option). Floats can only be controlled to an extent. If you want to position things exactly, then you may want to define a different environment to use instead, which has captions but is not actually a float. For example, the `longlisting` from the docs.
```latex
\usepackage[newfloat]{minted}
\usepackage{caption}
\newenvironment{longlisting}{\captionsetup{type=listing}}{}
```

**Comment by ReneHollander** [comment]
That fixed it!
Thanks for all your help.

**Comment by jones1008** [comment]
I am using the custom environment from this issue like this with `type=lstlisting` instead of `listing`:
```latex
\usepackage[newfloat]{minted}
\usepackage{caption}
\definecolor{codebg}{rgb}{0.95,0.95,0.95}
\setminted{
	bgcolor=codebg,
	startinline=true
}
\renewcommand{\lstlistingname}{Code}

\newenvironment{longlisting}{\captionsetup{type=lstlisting}}{}
\newenvironment{code}[3]
{%
	\VerbatimEnvironment
	\begin{longlisting}%
	\label{lst:#3}%
	\caption{#2}%
	\begin{minted}{#1}%
	}
	{%
	\end{minted}%
	\end{longlisting}%
}
```
and calling it with this:
```latex
\begin{code}{php}{customCaption}{customLabel}
my custom code
\end{code}
```
which produces this:
![grafik](https://user-images.githubusercontent.com/25104859/62529282-a0fe1500-b83e-11e9-94e2-dafbf025a7df.png)

However I can't seem to find a solution to place the caption below the code...
I tried to move the `\caption{#2}%` into the end-block but apparently [you can't do that](https://tex.stackexchange.com/questions/17036/why-cant-the-end-code-of-an-environment-contain-an-argument)...

Any ideas how I can place the caption below the minted-environment?

**Comment by klmr** [comment]
@jones1008 Do the solutions in your linked thread not work for you? E.g. this one:https://tex.stackexchange.com/a/126458/42

**Comment by jones1008** [comment]
Thanks @klmr for pointing out this answer. This worked perfectly! I just didn't scroll down far enough in the thread ^^
