### ISSUE TITLE
the ANSYS language support 

### ISSUE THREAD

**Issue by xiaoleeza** [gpoore/minted#109]
Under the v2.1 from 2015/09/09, through command pygmentize -L lexers, I cannot find the language ANSYS, could you please add this language support? Best wishes!

**Comment by gpoore** [comment]
`minted` uses the [Pygments library](http://pygments.org/) to do the actual highlighting. You could request support for additional languages at the [Pygments Bitbucket page](https://bitbucket.org/birkenfeld/pygments-main).

**Comment by averter** [comment]
Hi,

I've opened this request since I would be very interested on this as well.
Here is the link for backing up the request
https://bitbucket.org/birkenfeld/pygments-main/issues/1248/ansys-apdl-lexer

Best

**Comment by averter** [comment]
Here is a lexer which I have written for APDL. 
https://github.com/averter/lexers_pygments
If someone can double check it please do so since I am a newbie on python and/or lexers.
Cheers

**Comment by averter** [comment]
I have recently created this commit [b872095ed5c7c71ae119bb4e04bdf70689cc2336](https://github.com/pygments/pygments/commit/b872095ed5c7c71ae119bb4e04bdf70689cc2336) on pygments which should do the work.
