### ISSUE TITLE
minted delivers non-highlighted gibberish

### ISSUE THREAD

**Issue by drewx0r** [gpoore/minted#111]
The following is the output I get with the minimal example. Something is obviously not working correctly, but I don't know enough to know what's causing the issue.

`k+ktint n+nfmainp() p{

    nprintfp(l+s"hello, world"p);

        kreturn l+m+mi0p;

p}`

any ideas?

**Comment by gpoore** [comment]
There should be a folder called `_minted-<file name>`, where `<file name>` is the name of the file you are compiling. You could try to delete that and then recompile. If that doesn't fix it, then I will need a little more detail about what you're compiling, LaTeX distribution and version, Pygments version, and Python version.

**Comment by pthariensflame** [comment]
I have had this problem as well, but only with certain styles; others display correctly.

**Comment by gpoore** [comment]
@pthariensflame Can you provide any details about the styles, or anything else that might help me track down the cause?

**Comment by pthariensflame** [comment]
Here is a test file that demonstrates the problem.  (I’ve included the final output, and all intermediate files I could find, in case they might be helpful.)

[minted-test.zip](https://github.com/gpoore/minted/files/176408/minted-test.zip)

I’m compiling with LuaLaTeX, but the exact same results are given by XeLaTeX and pdfLaTeX as well.

**Comment by davidcarlisle** [comment]
@pthariensflame Oh that's non letters in the style name, if I change your example to

```
\catcode`\_=11
\section*{\centering\textit{\texttt{algol_nu}}}
```
then the algol one works (not a real fix of course) 

you would need similar for paraiso-light

Problem is in `\def\PYGalgol_nu@reset{...}`  if `_` is not a letter....

**Comment by gpoore** [comment]
@pthariensflame The problem is that Pygments is creating invalid LaTeX. The style names involving an underscore (`algol_nu`) or dash (`paraiso-light` and `paraiso-dark`) are generating invalid LaTeX code in which the underscore/dash is used as a letter.

This is ultimately a bug in Pygments. However, following @davidcarlisle's suggestion, a fix on the `minted` side may also be possible. Maybe wrap all of the style definitions within something like this:
```latex
\begingroup
\let\def\gdef
\catcode`\_=11
\catcode`\-=11
<input style definitions>
\endgroup
```
I'll look into a fix for the next release, and probably also open an issue on the [Pygments site](https://bitbucket.org/birkenfeld/pygments-main).

**Comment by pthariensflame** [comment]
@gpoore @davidcarlisle Thanks!  I eagerly await a fix.  :)

**Comment by m1so** [comment]
@gpoore Hi, I'm having the same problem using `paraiso-dark`, however I can't seem to figure out how to define `\catcode` for a single block that is defined this way:

```tex
\begin{minted}[style=paraiso-dark]{yaml}
...
\end{minted}
```

Do you guys have any suggestions? Thanks.

**Comment by davidcarlisle** [comment]
@m1so 

something like
```

\begingroup
\catcode`\-=11
\begin{minted}[style=paraiso-dark]{yaml}
...
\end{minted}
\endgroup

```

**Comment by m1so** [comment]
@davidcarlisle I have tried that as well, but I only get bunch of errors. The yaml file contains `-` character inside the minted environment, I have no idea if this might have any side effects though.
I'm using latexmk and xelatex btw.

**Comment by davidcarlisle** [comment]
@m1so I get no error from this, if you can change it so it does error, I can probably suggest a workaround 


```
\documentclass{article}
\usepackage{minted}
\begin{document}



bbb
\begingroup
\catcode`\-=11
\begin{minted}[style=paraiso-dark]{yaml}
abc-xyz: -22
\end{minted}
\endgroup

\end{document}

```

**Comment by gpoore** [comment]
@m1so I don't have any immediate suggestions beyond what @davidcarlisle has given. I'm in the midst of grading final exams and expect to be back on `minted` development next week. So perhaps I'll be able to create a permanent fix then.

**Comment by m1so** [comment]
I managed to get it working, in case anyone is getting errors, run the following commands in terminal:
```
tlmgr update --self
tlmgr update minted
```
Looks like texlive 2015 didn't have the latest version of minted
```
[1/1, ??:??/??:??] update: minted [709k] (36197 -> 38339) ... done
```

Thanks for the help @gpoore @davidcarlisle !

**Comment by cmoang** [comment]
Arch linux here. Same problem. Was using ``minted`` successfully in the past. The solution did not work for me.... strange.
I redownloaded the `.sty` from [http://mirrors.ctan.org/macros/latex/contrib/minted.zip](http://mirrors.ctan.org/macros/latex/contrib/minted.zip) and run
```
sudo cp minted.sty /usr/local/texlive/2015/texmf-dist/tex/latex/minted/minted.sty
sudo cp minted.sty  /usr/share/texmf-dist/tex/latex/minted/minted.sty
sudo tlmgr update --self
sudo tlmgr update minted
```
But no success...
