### ISSUE TITLE
Compile error when many sub-tex files are included

### ISSUE THREAD

**Issue by doyaklee** [gpoore/minted#114]
Hi, I wrote a big tex file in a book class. I write each chapter separately then include those files with `\include{ch1}`, `\include{ch2}`  , ...
After I successfully  compiled my main tex file, when I included several, say 10 tex files with `\include{}` commands and recompiled main tex file, I got the following error message.

! I can't write on file `main.mw'.
<to be read again> 
                   \scan_stop: 
l.21 ...e{toc}{\defcounter {refsection}{0}\relax }
                                                  \@writefile{toc}{\contents...

After I re-compiled it many many times, now it was successfully compiled. 
Since I included a lot of packages, maybe there could be some incompatibilities. But, when I don't use `\include{}` command, there's no compile error. And, the more I use `\include{}` commands, the more number of re-compilation is needed. 

Is there a way to fix this symptom?  Thanks!

**Comment by gpoore** [comment]
This doesn't appear to be related to the `minted` package. The `\include` command is a normal part of LaTeX, not part of `minted`. If you think there is a connection to `minted`, please provide more details. Otherwise, it would be better to ask a general LaTeX question at http://tex.stackexchange.com/ or a similar location.

**Comment by doyaklee** [comment]
I know it sounds weird, and I fell it weird. 
With exact same tex files without `minted` package loaded, there's no problem in compilation. And, if I just add `minted` package, the problem pops up. Also, without any `\include` command, there's no problem with using `minted` package.  That's the reason why I thought that there's some problem with `minted` and `\include` command

I'm using `pdflatex` engine, and I put most packages in `.sty` file, and load that file using `\include` command. Here's a list of packages I use in order:

`\RequirePackage{sgamevar}`
`\RequirePackage{tikz}`
`\usetikzlibrary{positioning, calc}`
`\RequirePackage{amsmath}`
`\RequirePackage{amsthm} `
`\RequirePackage{amsfonts} `
`\RequirePackage{amssymb} `
`\RequirePackage{bm}	 `
`\RequirePackage{soul}`
`\RequirePackage{mathpazo} `
`\RequirePackage[utf8]{inputenc}`
`\RequirePackage[english]{babel}`
`\RequirePackage[retainorgcmds]{IEEEtrantools}`
`\RequirePackage{xcolor}`
`\RequirePackage{graphicx}`
`\RequirePackage{subfig}`
`\RequirePackage{enumitem}`
`\RequirePackage{microtype} `
`\RequirePackage{booktabs}   `
`\RequirePackage{listings} `
`\RequirePackage[flushleft]{threeparttable}`
`\RequirePackage{verbatim}`
`\RequirePackage[colorinlistoftodos]{todonotes}`
`\RequirePackage{pdfpages} `
`\RequirePackage{lscape}`
`\RequirePackage[capposition=top]{floatrow}`
`\RequirePackage{multirow}`
`\RequirePackage{epigraph}`
`\RequirePackage{etoolbox}`

`\RequirePackage{titletoc}`
`\RequirePackage[explicit]{titlesec}`
`\RequirePackage{etoc}`
`\RequirePackage{titling}  `
`\RequirePackage{fancyhdr} `
`\RequirePackage[sorting=nyt, style=authoryear-comp, backend=biber, isbn=false, url=false, doi=false, eprint=false, dashed=false]{biblatex}`
`\RequirePackage{xpatch}`
`\RequirePackage[colorlinks=true,citecolor=citeblue, urlcolor=urlblue,  pdfencoding=auto, bookmarks=true, bookmarksnumbered=true]{hyperref} `
`\RequirePackage{footnotebackref}`
`\RequirePackage{makeidx}`
`\makeindex`
`\RequirePackage[toc, nopostdot]{glossaries}`
`\makeglossaries`
`\RequirePackage{datatool}% http://ctan.org/pkg/datatool`
`\RequirePackage[framemethod=default]{mdframed} % Required for creating the theorem, definition, exercise and corollary boxes`
`\RequirePackage{morewrites}`
`\RequirePackage{minted}`


`\usepackage[margin=0.9in, top=1in, headheight=0.6in]{geometry}`
`\usepackage{setspace}`

**Comment by NobbZ** [comment]
You really shouldn't use `\RequirePackage` in a document, it is an internal
command thought for package-authors only, please rewrite to use
`\usepackage` instead. Don't know if this is related to your problem though…

Instead I do think, that you are running into TeX' limit of open files,
which is sometimes hidden behind obscure error-messages. Depending on the
TeX-engine you are using, you might find some help in the `morewrites`
package (no link, since CTAN seems to be down from here)

doyaklee <notifications@github.com> schrieb am Di., 5. Apr. 2016 um
16:54 Uhr:

**Comment by gpoore** [comment]
It sounds like you have a file with a `.sty` extension that contains a lot of `\RequirePackage`'s, and then bring in that file with `\include`. It would be more standard to have a file with extension `.tex` that contains a lot of `\usepackage`'s, and bring that in with `\input`. Or, if you want this to be your own style file, then use `.sty` and bring it in with `\usepackage`. `\include` does extra things you don't want, and as @NobbZ pointed out, `\RequirePackage` isn't something you typically want to use, unless you're writing your own package.

Usually, you want to load `hyperref` absolutely last, unless you know for sure that a particular package must be loaded after it.

You probably want all of the `\make...` commands after all the packages have been loaded.

I don't see any obvious package incompatibilities, though it's possible that there is one. My guess is that you are hitting a limitation in the TeX engine, by loading one more package, which just happens to be `minted`. You might try loading `morewrites` at the beginning, and look at the latest documentation for it to see if that is useful. If that doesn't work, you might try `lualatex` (which should have fewer limitations, though it would require different font-related packages).

**Comment by davidcarlisle** [comment]
Judging by the .mw extension and the fact that the error message displays
expl3 code I would guess that this is a morewrites error however

> and load that file using \include command.

that is definitely an error and not supported by latex.

\include should never be used before \begin{document} it's not surprising
that that confuses morewrites.

Call the file with all the \RequirePackage lines  something.sty and then
load it via

\usepackage[something}

**Comment by doyaklee** [comment]
Thanks for all the suggestions.
I originally used .`sty` file with `RequirePackage` and `usepackage`  as @gpoore described. Then, I changed that file as `.tex` file with `usepackage` command and using it with `input`, and move things a little bit as suggested. But that didn't help.

After several hours' try, I failed to figure out the origins of the problem, but it seems that I found the solution in my case. 

I have three machines with Windows 10 OS. For two of them, I installed `tex live` at `C:\`, and for the remaining one, I installed it at `D:\`. All my `tex` files are located at `D:\` for all machines. 

What I found is that `tex live` in `D:\` compiled tex files in both `C:\` and `D:\` successfully without any error, but `tex live` installed in `C:\` pops out errors when compiling tex files in `D:\`. After I moved my tex files into `C:\` and recompiled it, there were no problems. 

I installed Python using Anaconda. Since this package uses Python and Pygments, I still don't know exactly where the problem comes from, but It seems that this problem is not directly related to `minted` package or `LaTex' itself, so please close this issue if you think this is off topic. Thanks!

**Comment by lustosatorres** [comment]
I had the same problem. And for me, the solution of transferring the project from C:\ to D:\ solved the problem
