### ISSUE TITLE
Minted does not highlight doctest examples. 

### ISSUE THREAD

**Issue by Erotemic** [gpoore/minted#116]
I have the following code in an external file egregister.py 

```python
import dtool
import utool as ut
import numpy as np

register_preproc = dtool.make_depcache_decors('annotation')['preproc']

class FeatConfig(dtool.Config):
    _param_info_list = [
        ut.ParamInfo('affine_invariance', True, alias='AI'),
        ut.ParamInfo('rotation_invariance', False),
        ut.ParamInfo('augment_orientation', False),
        ut.ParamInfo('dense', False),
        ut.ParamInfo('dense_stride', False, hideif=lambda cfg: not cfg['dense']),
    ]

@register_preproc(
    tablename='feat', parents=['chip'],
    colnames=['num', 'kpts', 'vecs'],
    coltypes=[int, np.ndarray, np.ndarray],
    configclass=FeatConfig,
)
def compute_feats(depc, chip_id_list, config):
    """
    Worker function that computes SIFT features for a set of chips.

    Args:
        depc (dtool.DependencyCache): dependency cache object
        cid_list (list): parent chip rowids
        config (dict): configuration options

    Yields:
        tuple: number of features, affine keypoints, SIFT descriptors

    Example:
        >>> # Get circular keypoints of the first three annotations
        >>> kpts_list = depc.get('feat', [1, 2, 3], 'kpts', config={'AI': False})
    """
    import pyhesaff
    chip_gen = depc.get_native('chip', chip_id_list, 'img')
    for chip in chip_gen:
        kpts, vecs = pyhesaff.detect(chip, **config)
        yield len(kpts), kpts, vecs

```

and I want to highlight it in a pdf with minted.

`\inputminted[linenos,tabsize=4,fontsize=\footnotesize]{python3}{egregister.py}`

This correctly inserts the code except for the doctest example. There seem to be two errors happening. 

The first is a clear error is happening because instead of three right angle brackets to prefix the doctest I instead get a \guillemotright followed by a normal \rangle. When I should get \rangle\rangle\rangle. 

This can be seen here: 
![compiled doc](http://i.imgur.com/NfPzPx1.png)

The second is more of a feature request. It would be nice if the doctest code was highlighted, but that isn't a huge deal. (It seems like it is only marginally supported by github markdown)

**Comment by gpoore** [comment]
What version of Pygments are you using? With 2.1.1, I get the correct `>>>`.

In terms of highlighting doctests, that would be something to suggest at the [Pygments site](https://bitbucket.org/birkenfeld/pygments-main).

**Comment by Erotemic** [comment]
It seems that I'm on 2.0.2. I upgraded to 2.1.1, and then rebuilt my entire project making sure I got rid of _minted-main. It still shows up the same. 

I made a minimal example and it showed up with the correct `>>>`. It must be due to some 
configuration I have in my project. 

Apologies for posting an issue without making the minimal example first.

**Comment by gpoore** [comment]
If you figure out what was causing the `>>>` issue, I would be interested to know. If there is a package conflict, it might be possible to fix/protect against on the `minted` side.

**Comment by Erotemic** [comment]
I was able to find the package that caused the error. Removing \usepackage[T1]{fontenc} removes the issue. I'm not sure why it is happening, but I'm not currently using fontenc for my project so I was able to remove it. Here is the minimal example. 

main.tex is
```
\documentclass[chap]{book}

\usepackage[T1]{fontenc}  % Commenting this line removes the >>> bug
\usepackage[chapter]{minted}
\newenvironment{code}{\captionsetup{type=listing}}{}

\begin{document}
\newmintedfile[pythonscript]{python}{
linenos=true,
gobble=0,
funcnamehighlighting=true,
tabsize=4,
fontsize=\scriptsize{},
samepage=false,
}

\newcommand{\egregister}{
    \begin{figure}[!ht]
    \centering
    \RecustomVerbatimEnvironment{Verbatim}{BVerbatim}{}
    \fbox{
    \pythonscript{egregister.py}
    }
    \caption[Example of a registered cache function]{
    % ---
        A simplified version of the function that compute features
          given a chip.
        This function is registered with the annotation cache in a
          declarative style.
        This property can be accessed using the cache as shown in the
          doctest example.
    % ---
    }\label{fig:egregister}
    \end{figure}
}

\chapter{The Dependency Cache}

A code snippet that shows how a function is registered as a node of
  the cache is illustrated in Figure~\ref{fig:egregister}.

\egregister{}

\end{document}
```


egregister.py is 
```
import dtool
import utool as ut
import numpy as np

register_preproc = dtool.make_depcache_decors('annotation')['preproc']

class FeatConfig(dtool.Config):
    _param_info_list = [
        ut.ParamInfo('affine_invariance', True, alias='AI'),
        ut.ParamInfo('rotation_invariance', False, alias='RI'),
        ut.ParamInfo('augment_orientation', False, alias='AQH'),
    ]

@register_preproc(
    tablename='feat', parents=['chip'],
    colnames=['num', 'kpts', 'vecs'],
    coltypes=[int, np.ndarray, np.ndarray],
    configclass=FeatConfig,
)
def compute_feats(depc, chip_id_list, config):
    """
    Worker function that computes SIFT features for a set of chips.

    Example:
        >>> # Get circular keypoints of the first three annotations
        >>> config = dict(AI=False)
        >>> kpts_list = depc.get('feat', [1, 2, 3], 'kpts', config)
    """
    import pyhesaff
    chip_gen = depc.get_native('chip', chip_id_list, 'img')
    for chip in chip_gen:
        kpts, vecs = pyhesaff.detect_feats(chip, **config)
        yield len(kpts), kpts, vecs
```

**Comment by gpoore** [comment]
I've verified that `fontenc` was causing the problem. Apparently `>>` is defined as an abbreviation for `\guillemotright`, and this isn't being correctly disabled in verbatim mode. I'm reopening the issue so I will remember to try to fix this in a future release.

**Comment by gpoore** [comment]
The `>>>` issue appears to be due to using `fontenc` with `lualatex`. `fontenc` is fine with `pdflatex` and `xelatex`. Apparently, [`fontenc` shouldn't be used with `lualatex`](http://tex.stackexchange.com/questions/243482/switching-to-lualatex-how-to-translate-font-setups). So this appears to be a TeX engine/font package clash, rather than something that `minted` may need to resolve.
