### ISSUE TITLE
CamelCase

### ISSUE THREAD

**Issue by Eyenseo** [gpoore/minted#117]
Hello,

It would be nice if there was an `breakbefore` option so that one could specify all capital letters so CamelCases will be broken too.

Thank you very much!

**Comment by gpoore** [comment]
There is now a `breakbefore` that works like `breakafter`, with associated `breakbeforegroup`, `breakbeforesymbolpre`, and `breakbeforesymbolpost`.  It is possible to use `breakbefore` and `breakafter` for the same character, so long as `breakbeforegroup` and `breakaftergroup` have the same setting (both are on by default).

**Comment by Eyenseo** [comment]
Thank you very much, you are awesome!
