### ISSUE TITLE
Problem with caption

### ISSUE THREAD

**Issue by metal3d** [gpoore/minted#12]
Finally I found a problem.

I'm using "opensans" package to write my book, I've got figures and minted listings.

For figures, the "Figure X:" follows the right font (open sans)

For listings, "Listing X:" use True Type font (Times new roman), which I don't want (not open, not on Linux box... and not embed on pdf generation).

Is this a minted problem or a LaTeX problem ? Any suggestion ?

**Comment by gpoore** [comment]
There is now a `newfloat` package option that uses `newfloat` rather than `float` to create the `listing` environment. This provides better compatibility with the `caption` package.
