### ISSUE TITLE
Minted doesn't highlight my code

### ISSUE THREAD

**Issue by lythenas** [gpoore/minted#120]
Hi.
I'm trying to use minted for syntax highlighting. But no matter what I do it doesn't seem to want to highlight my code.
At first my code didn't even show up in the pdf. After I fixed that(don't ask me how) it shows up but isn't formatted in any way. No background, no text color, just text.
I'm using xelatex to convert my tex file to pdf.

I hope someone can help me.

**Comment by Sancho-Panza** [comment]
Try using the -shell-escape option.

**Comment by lythenas** [comment]
Yes I'm already using that. Without -shell-escape it won't even run 'cause it need pygments.
Speaking of pygments. Is there an easy way to find out if my pygments install is the problem here?

**Comment by Sancho-Panza** [comment]
Try to make a pdf with [this](https://github.com/Sancho-Panza/textasie-challenge/tree/master/proposition-projet) ; if it works, then, your pygment install is ok, if not, then, something is wrong in your code I guess.

**Comment by lythenas** [comment]
I was able to make the pdf. And all the syntax highlighting looks perfectly fine.
I'll have a look at my tex file then and maybe clean it up to try and figure out what's going wrong.

**Comment by Sancho-Panza** [comment]
If you want, I could look at your tex file and try to find what's wrong.

**Comment by lythenas** [comment]
Ok, so as it turns out my latex file worked perfectly since the start.
Pygments just only highlights bash when the actual code is preceded with `#!/bin/bash`
and php when preceded with `<?php`.

Sorry to waste your time.

**Comment by gpoore** [comment]
@lythenas You might take a look at the `startinline` option for working with PHP, so you won't need the `<?php`. Also, for `bash`, there is `bash` for scripts, but also `shell-session`. One may be better than the other depending on what you are doing. More [details](http://pygments.org/docs/lexers/#lexers-for-php-and-related-languages).
