### ISSUE TITLE
codetagify: can't use a list of tags

### ISSUE THREAD

**Issue by levbishop** [gpoore/minted#126]
Only a single tag works.
Commands such as

``` tex
\setminted{codetagify={TAG1,TAG2,TAG3}}
```

only highlights the first `TAG1`.

Or perhaps I am trying this with the wrong syntax, in which case the documentation should be updated

**Comment by levbishop** [comment]
Failing example:
``` tex
\documentclass{article}
\usepackage{minted}
\setminted{codetagify={TAG1,TAG2}}
\begin{document}
\usemintedstyle{colorful}
\begin{minted}{yaml}
  # TAG1: this is first tag, it works <>
  # TAG2: this is second tag, it doesn't work <>
\end{minted}
\end{document}
```

**Comment by gpoore** [comment]
This is strange. It isn't behaving like the other Pygments options. I'll have to see if there is a bug in Pygments.

In the meantime, a **space-separated, quoted** list of tags seems to work:
```latex
\setminted{codetagify={"TAG1 TAG2"}}
```

**Comment by gpoore** [comment]
Pygments only supports space-delimited lists for `codetagify`. I've added support for comma-delimited lists in `minted` v3.0, which is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon.
