### ISSUE TITLE
escapeinside removes end-of-line?

### ISSUE THREAD

**Issue by adl** [gpoore/minted#127]
For some reason I don't really understand, using `escapeinside` in a `console` example removes everything to the right of the escaped fragment.

```latex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[escapeinside=@@]{console}
$ ls
@x@foo
bar@y@
baz
\end{minted}
\end{document}
```
![test](https://cloud.githubusercontent.com/assets/822900/16775634/da5fcde8-4861-11e6-9144-f46074c5a41e.png)

In the above example, the text `bar` disappeared.

Note that the problem does not exist (i.e., `bar` is output) when using `{sh}` instead of `{console}`, but then the syntax highlighting is incorrect.

**Comment by gpoore** [comment]
This looks like a [Pygments](http://pygments.org/docs/tokens/) bug. `escapeinside` can be [fragile in some cases](https://bitbucket.org/birkenfeld/pygments-main/issues/1118), but this looks like a new problem. You might open a bug on the [Pygments Bitbucket page](https://bitbucket.org/birkenfeld/pygments-main/issues).

**Comment by adl** [comment]
I can indeed reproduce this problem by calling `pygmentize` directly.
Pygments issue created [here](https://bitbucket.org/birkenfeld/pygments-main/issues/1255/).
