### ISSUE TITLE
Beamer overlays for highlightlines

### ISSUE THREAD

**Issue by cocreature** [gpoore/minted#128]
Maybe I’m missing something but I can’t seem to use beamer overlays for changing the highlighting of certain lines.

I tried

```
\inputminted[highlightines=<1>{1}]{c}{main.c}
```
but that ends up highlighting no lines at all.

**Comment by gpoore** [comment]
Overlays don't work in command arguments. You would want to try something like this, with the `fragile` frame option.
```latex
\only<1>{\setminted{highlightines=1}}
\only<2>{\setminted{highlightines=2}}
\inputminted{c}{main.c}
```
You could also just use `\inputminted` multiple times, once per overlay.

**Comment by cocreature** [comment]
Perfect, thanks a lot (sorry that it took me so long to reply).

**Comment by gsstark** [comment]
This was super helpful. Thanks!

**Comment by aubertc** [comment]
That *is* extremely useful, thanks a lot!

_On a side note, it should read `highlightlines` and not `highlightines`, i.e., a "l" is missing._
