### ISSUE TITLE
Minted not working any more

### ISSUE THREAD

**Issue by MarcoNiemann** [gpoore/minted#129]
With todays Miktex Update the `minted` package was also updated. 
However, now I cannot compile any document using `minted` commands anymore.  I keep getting the following error message:

```
[Loading MPS to PDF converter (version 2006.09.02).]
) (_minted-test/default-pyg-prefix.pygstyle) (_minted-test/default.pygstyle)
! Undefined control sequence.
\minted@inputpyg ...}\endcsname \VerbatimPygments
                                                  {\PYG }{\minted@PYGstyle }...
l.10   \end{minted}
```

Uninstalling and reinstalling both `pygments` as well as `minted` did not solve the problem. Also deleting the subdirectory `_minted-{filename}` as proposed in some Stackoverflow posts did not change anything.

Current test file:

``` latex
\documentclass[10pt, a4paper]{scrartcl}

\usepackage{minted}

\begin{document}
\begin{minted}{csharp}

string test;

\end{minted}
\end{document}
```

**Comment by bazzilic** [comment]
Encountering similar behavior after updating MiKTeX today.

```
[Compiling C:\Users\bazzilic\...tex]

TraditionalBuilder: Engine: pdflatex. Invoking texify... done.

Errors:

C:/Users/bazzilic/....tex:18: Undefined control sequence. [...same file), and \mintinline{csharp}{using}]
```

**Comment by MarcoNiemann** [comment]
Update from my side:
Go to your `minted.sty` and replace the code there with the code of the commit before the most recent one (-> [minted.sty (last working)](https://github.com/gpoore/minted/blob/aa6032d0a2eb50dfabc3ff9404c26c7bb17f7831/source/minted.sty) ). 

Is a dirty hack but will settle the problem till it is officially fixed.

**Comment by bazzilic** [comment]
Thanks, it worked.

**Comment by gpoore** [comment]
The latest version of `minted`, 2.4, needs [`fvextra` version 1.2](https://github.com/gpoore/fvextra/releases/tag/v1.2). It looks like there is a bug in the MiKTeX packaging system. On a fresh MiKTeX install, the package manager shows `fvextra` 1.2 as the current version, but it actually installs 1.1 instead. TeX Live is working fine, so this appears to be MiKTeX-specific.

**Comment by andreaskiermeier** [comment]
Thanks. I'm on Miktex and have replaced the fvextra.sty file on my installation (system wide) with the one from Github (your link).
Note that I had to remove my personal installation (in Appdata/Roaming/Miktex/2.9/tex/latex) which I think was installed on the fly.

**Comment by bazzilic** [comment]
Should this issue be reported here https://sourceforge.net/p/miktex/bugs/ ?

**Comment by gpoore** [comment]
@bazzilic Bug report: https://sourceforge.net/p/miktex/bugs/2519/

**Comment by bazzilic** [comment]
Nice, thanks. Looks like fix will be rolled out in the next miktex update.

**Comment by MarcoNiemann** [comment]
Perfect. Thanks for taking care of the issue so quick @gpoore.
