### ISSUE TITLE
Option autogobble is not working as expected

### ISSUE THREAD

**Issue by michel-zimmer** [gpoore/minted#130]
I'm using `inputminted` to display code from a file and everything is working as expected so far. The option `autogobble` works, when the entire file has the same preceding whitespace characters in each line.

But when I use `firstline` and/or `lastline` and in the remaining lines even more whitespace characters are the same for each line, then it's not getting un-indented as far as possible anymore.

**Comment by gpoore** [comment]
That is a bug in `autogobble` -- it wasn't accounting for `firstline` or `lastline`. The `minted.sty` from the last commit should fix it.

**Comment by michel-zimmer** [comment]
Works as expected now. Thanks!
