### ISSUE TITLE
Are there any plans on including SPICE source code highlight?

### ISSUE THREAD

**Issue by LaloHao** [gpoore/minted#134]
Basically what the title says

**Comment by gpoore** [comment]
`minted` uses [Pygments](http://pygments.org/) to do the actual highlighting, so you would want to look into Pygments support for SPICE.

**Comment by LaloHao** [comment]
It seems there is already a [2 year request](https://bitbucket.org/birkenfeld/pygments-main/issues/1009/new-lexer-request-systemc-systemc-ams-and) to add SPICE to pygments, im gonna go ask there
