### ISSUE TITLE
Upgrade the minted version

### ISSUE THREAD

**Issue by auzias** [gpoore/minted#136]
I actually have the version 1.7 and would like to know how to get the most up-to-date version.

**Comment by auzias** [comment]
I actually manage to update the version by replacing the RAW `minted.syt`. Though I could not find how to get `fvextra.sty` so I downgrade to the **version 2.2.2** and everything seems to be working.

---
Great work ! Thanks a lot !

**Comment by gpoore** [comment]
If you are using a recent version of TeX Live or MiKTeX, you should be able to run the package manager and have it update to get the latest version of `minted` (and get `fvextra`) automatically. You would want to refer to their documentation for details on how to do that.
