### ISSUE TITLE
Can't find pygmentize despite that it truely exists

### ISSUE THREAD

**Issue by koosha--** [gpoore/minted#137]
I'm using the latest version of minted (and before that I was using an older version) on my Debian system. The `pygmentize` is installed and is executable from the CLI. However, minted still complains about `pygmentize` and refuses to compile my document. I have also tried to override AND modify the original source of minted to point to `/usr/bin/pygmentize` but still the issue exists! Any insight on this?

**Comment by NobbZ** [comment]
Are you able to use pygmentize directly? is the executable bit set? Is it
set for the correct user? Is write18 fully enabled for that tex run?

Koosha K. M. <notifications@github.com> schrieb am Fr., 28. Okt. 2016 um
13:33 Uhr:

**Comment by koosha--** [comment]
Yes, yes, yes, and most probably yes (`pdflatex -shell-escape file.tex`).

**Comment by gpoore** [comment]
@koosha-- Are you running the command on the command line, or using an editor? If using an editor, which one? Does the editor have its own, built-in Python distribution, or does it modify the PATH? I know that can be an issue with some editors under OS X, though I'm not aware of any previous Linux cases.

**Comment by koosha--** [comment]
I tried both ways: CLI and the editor. My editor is Texmaker which I have configured to have `-shell-escape` flag set in its settings. But, still the issue is there.

**Comment by gpoore** [comment]
@koosha-- Can you post the exact error message that you are getting?

**Comment by koosha--** [comment]
I've realized that the reason is probably other libraries:

```
sh: 1: Syntax error: Unterminated quoted string

! Package minted Error: You must have `pygmentize' installed to use this package.
```
The minimal example works fine. Is there anyway to figure out what line in what package exactly is causing the "Unterminated quoted string"?

**Comment by gpoore** [comment]
@koosha-- My guess would be some other package that involves using `-shell-escape` / `\write18`. Otherwise the shell shouldn't be involved. If you want to post a list of the packages, I can take a quick look, but unless it's something obvious, somewhere like http://tex.stackexchange.com/ may be a better place to pursue this further.

One additional possibility. Does your filename have any unusual characters in it?

**Comment by koosha--** [comment]
Bingo, the problem was the file name. It had an apostrophe in it. I removed it and  the issue got fixed. Thank you so much for the hint. If not already covered, it would be good to mention this subtle issue in the documentation.

Thank you.

**Comment by gpoore** [comment]
@koosha-- I tried a file with a single quote in the name under Windows, and got an error there too. In the last commit, I've changed some of the internals so that single quotes are sanitized, not just double quotes. That should prevent this from causing problems under all operating systems.

**Comment by koosha--** [comment]
Great, thank you.
