### ISSUE TITLE
inputminted with R file converts $ to £ in R comment

### ISSUE THREAD

**Issue by jsams** [gpoore/minted#138]
I have an R file with a comment that contains the text "diag(gb$sigmas)", and this gets printed in my pdf as "diag(gb£sigmas)" instead. Using the package from the ubuntu repository in 16.04 using Kile with pdflatex.

Simple enough. Hope that is enough detail?

**Comment by gpoore** [comment]
That sounds like a font issue. You probably need to use T1 font encodings. Under pdfTeX, `\usepackage[T1]{fontenc}`.
