### ISSUE TITLE
doesn't work if `-output-directory` is used

### ISSUE THREAD

**Issue by lex93ushakov** [gpoore/minted#141]
Ubuntu 16.10, pygments installed via pip3

**Comment by gpoore** [comment]
Are you using the `outputdir` package option for `minted`? Unfortunately, there is no way for `minted` to detect `-output-directory`, so the directory must be specified manually as a package option. And if the directory name contains special characters, those will have to be escaped in normal LaTeX fashion (or use `\detokenize`).

**Comment by lex93ushakov** [comment]
I think that the simplest solution here is using symlinks; they are supported via git.
