### ISSUE TITLE
Unable to use keys as filename argument for minted.

### ISSUE THREAD

**Issue by alvarocombo** [gpoore/minted#142]
Since I'm not fully proficient in Latex I might be doing some mistake, but I tried many approaches and still stuck. When I try to give `\inputminted` (or similar) filename parameter as a setkey (from either keyval of xkeyval packages) it fails, apparently because it does not fully expand the argument.

Can you tell me if this a problem of my code or a minted limitation? (Any suggestion to overcome it?)

Below is a test example.

`
\documentclass{article}

% Preamble Setting for {minted} package
\usepackage{minted}
\usemintedstyle{friendly}  
% Specify Custom Styles for minted Source Codes
\newmintedfile[codec]{c}{linenos=true} 

\usepackage{keyval}% http://ctan.org/pkg/keyval 

\newcommand{\tempsrc}{./tmpsrc/}   % Just a path!
\newcounter{cntTmp}

\makeatletter
\newcommand{\gitRepoDir}{S:/temp/git_test/}
\newcommand{\tmpSrcDir}{./tmpsrc/}
\newcommand{\mysome}[1]{#1}
% \gFile{<Init Directory>}{<Tag>}{<Source Directory>}{Filename}
\newcommand{\gFile}[4]{
% Define Key
\define@key{}{fdTmp\arabic{cntTmp}}[]{tmp#2#4}
\stepcounter{cntTmp}
}
\makeatother

\begin{document}

- Add a key.

\gFile{src}{first-tag}{./}{test.txt}

- End Key creation. \newline
- Verify SETKEYS (for fdTmp0): \setkeys{}{fdTmp0} \newline

-- At this point assume the following files exist:\newline
+++++ \setkeys{}{fdTmp0} \newline

- Now the minted command WITH file name.

\codec[firstline=5, lastline=50]{\tempsrc tmpfirst-tagtest.txt}

- Now the same command, but where the parameter is given by setkeys.

%%% HERE LIES THE PROBLEM   
%\codec[firstline=5, lastline=50]{\tempsrc \setkeys{}{fdTmp0}}

% The following error appears if the above line is added:
% Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: './tmpsrc/\\def KV@FV@{KV@@}\\let \\par '

\end{document}
`

**Comment by davidcarlisle** [comment]
This is unrelated to minted, \setkeys will never work in such a situation (see what 

`\typeout{\setkeys{}{fdTmp0}}`

for example produces. `\setkeys`  is a complicated parsing macro which makes many internal definitions, parsing a comma separated list, splitting up key=value assignments on `=` and normalising white space.

However it isn't clear why you are using it at all as  you have no comma separated list of key=value settings?

It would seem far more natural for your `\gFile` command to simply store the filename in a macro which you then use in the minted argument.

**Comment by alvarocombo** [comment]
Dear David,

Thanks for your reply. Unfortunately the answer just confirms my suspicions.

The reason why (I tried to)  use the \setkeys is because it provided an
solution for my problem, which can be stated like this:


   1. I have a (big) list of (source) files: As you putted I could create a
   command for each and every one, but that will lead to a big list of
   commands. Still these commands would be used for instance in references
   along the text (NOT as minted argument... see below).
   2. All source files ARE copied (by system requirement) to a local
   directory AND with a temporary name (temporary files). Is THIS name that
   MUST be fed to minted.
   3. Using key=value would allow me to maintain a relation between key
   (that would be the name of a temporary file) and the value (the name of the
   source file).
   4. It also AVOIDed the creation of a second set of commands for the
   temporary file names.
   5. Finally, and since names can have characters other than letters, the
   key=value would allow to overcome this limitation on command names.

I appreciate your answer. Regards.

**Comment by davidcarlisle** [comment]
keys don't help you at all here. I think you want something like the following (but if not, best ask on tex.stackexchange or some such, it's definitely not a minted issue so we shouldn't use this github)

```
\documentclass{article}

% Preamble Setting for {minted} package
\usepackage{minted}
\usemintedstyle{friendly}
% Specify Custom Styles for minted Source Codes
\newmintedfile[codec]{c}{linenos=true}

\usepackage{keyval}% http://ctan.org/pkg/keyval

\newcommand{\tempsrc}{./} % Just a path!
\newcounter{cntTmp}

\makeatletter
\newcommand{\gitRepoDir}{./}
\newcommand{\tmpSrcDir}{./}
\newcommand{\mysome}[1]{#1}
% \gFile{}{}{}{Filename}
\newcommand{\gFile}[4]{%
% Define Key
\expandafter\xdef\csname fdTmp\arabic{cntTmp}\endcsname{#2#4}%
\stepcounter{cntTmp}%
}
\newcommand\usefile[1]{\csname fdTmp#1\endcsname}
\makeatother

\begin{document}

    Add a key.

\gFile{src}{first-tag}{./}{test.txt}


\typeout{FILE 0 is \usefile{0}}

    End Key creation. \newline
    Verify SETKEYS (for fdTmp0): \usefile{0} \newline

-- At this point assume the following files exist:\newline
+++++ \usefile{0} \newline

    Now the minted command WITH file name.

\codec[firstline=2, lastline=3]{\tempsrc test.txt}

    Now the same command, but where the parameter is given by setkeys.

%%% HERE LIES THE PROBLEM
\codec[firstline=2, lastline=3]{\tempsrc \usefile{0}}

% The following error appears if the above line is added:
% Traceback (most recent call last): File "", line 1, in IOError: [Errno 2] No such file or directory: './tmpsrc/\def KV@FV@{KV@@}\let \par '

\end{document}
```
