### ISSUE TITLE
Add the ability to include only pat of a file (e.g. using a line number range)

### ISSUE THREAD

**Issue by GuillaumeDIDIER** [gpoore/minted#143]
When one has a big code file and want to include only part of it in the TEX file this could come handy.

**Comment by gpoore** [comment]
Have you looked at the `firstline` and `lastline` options?

**Comment by GuillaumeDIDIER** [comment]
That's exactly what I was looking for and did not find.
Sorry for disturbing, and by the way, thanks for this extremely handy package !
