### ISSUE TITLE
bug in firstline / lastline when using begin{minted} ... end{minted}  

### ISSUE THREAD

**Issue by bidspells** [gpoore/minted#145]
The firstline and lastline attributes work fine in the context of \inputminted, e.g.,
\inputminted[firstline=93,lastline=121,fontsize=\tiny]{cpp}{media/09/samek-cpp/watch.cpp}

However, when the same code is directly provided within an \begin{minted} ... \end{minted} environment,  you do _not get the lines specified_ in the firstline/lastline attributes, e.g., 

```
\begin{minted}[firstline=93,lastline=121,fontsize=\tiny]{cpp}
/**
 * watch.cpp
 * Simple digital watch example
...
\end{minted}
```

In this case, I got a LateX error:
```
! FancyVerb Error:
  Empty verbatim environment
.
\FV@Error ...ncyVerb Error:^^J\space \space #1^^J}
                                                  
l.213 \end{Verbatim}
```

Is this a bug?
In my case, Latex/minted code is generated by pandoc thus I cannot simply use \inputminted

Best regards,
Erik

**Comment by gpoore** [comment]
This was a bug. Everything should work with the `minted.sty` from the last commit.
