### ISSUE TITLE
all $ go to £

### ISSUE THREAD

**Issue by alinelena** [gpoore/minted#147]
Hi I have a very strange issue.

I try to include a source code (Fortran) but for a reason all my $ in comments get transformed in £ the same happens for C code.

attached files to reproduce the issue and the ouput.
pdflatex -shell-escape hello2.tex

[hello2.pdf](https://github.com/gpoore/minted/files/696871/hello2.pdf)

[hello.zip](https://github.com/gpoore/minted/files/696872/hello.zip)

specifics of the latex (opensuse install)

[17:29:19 drFaustroll@circassia:~/lavello]: pdflatex -v
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/TeX Live for SUSE Linux)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.26; using libpng 1.6.26
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.50.0

minted version 2015/09/09 v2.1

**Comment by gpoore** [comment]
That's a font issue. Try `\usepackage[T1]{fontenc}` or `\usepackage{lmodern}`.

**Comment by alinelena** [comment]
just to comment... tried the git version of minted and the same problem persists. 
in normal latex code \$ is rendered as expected.

**Comment by alinelena** [comment]
indeed the font made the trick.
