### ISSUE TITLE
problem with samepage=true

### ISSUE THREAD

**Issue by eendebakpt** [gpoore/minted#15]
I am trying to prevent an environment from splitting over 2 pages. The option samepage=true prevents the block from splitting, but the label (part of the frame) is still placed on a separate page.

Example code showing the problem is included below.

---

\documentclass[a4paper,notitlepage]{article}
\usepackage{minted}

\newminted{cpp}{mathescape, numbersep=5pt, frame=lines, samepage=true,  fontsize=\small,label=C++ interface}

\title{Test}
\author{Pieter}

\begin{document}

\section{Test document}

This is a test
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

yyy yyy yyyyy yyyy y yyyy yyy yyy yy yyyyy yyyyyyyyy yyyy yyyyy
yyy yyy yyyyy yyyy y yyyy yyy yyy yy yyyyy yyyyyyyyy yyyy yyyyy
yyy yyy yyyyy yyyy y yyyy yyy yyy yy yyyyy yyyyyyyyy yyyy yyyyy

xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx
xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

\begin{cppcode}
struct xxx
{
    int i;
    int j;
    int x;
    int y;
    int z;

```
/// Constructor functions
xxx();
xxx(int index);
~xxx();
xxx(const xxx &);
```

public:
    void test1();

```
void test2();

void test3();

void test1b();

void test2b();

void test3b();

...
```

}
\end{cppcode}

xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

\subsection{End of test}

xx xxxxx xx xx xx  xxxxx xx xxxxx xxxx xxxxx xxxx x xxxxxx xxxx

\end{document}

**Comment by gpoore** [comment]
@lucbouge Unfortunately, I am not aware of any progress. `fancyvrb` is still essentially the same, and I'm not aware of any patches for it that would fix this issue.
