### ISSUE TITLE
Syntax highlight error in Scala lexer, literal types

### ISSUE THREAD

**Issue by soronpo** [gpoore/minted#153]
Scala code will soon allow literals to be placed in types position (SIP-23). Typelevel Scala and Dotty already allow this. The minted lexer is required not to mark the following as errors:
```
type Test[A] = Int
type MyTest = Test[1]

val one :  1 = 1
```

**Comment by gpoore** [comment]
The actual lexing is performed by [Pygments](http://pygments.org/). The [Pygments BitBucket page](https://bitbucket.org/birkenfeld/pygments-main) would be the place to request new lexer features or submit a pull request.

**Comment by soronpo** [comment]
OK. Will do. Closing this issue.
