### ISSUE TITLE
\BeforeBeginEnvironment{minted}{} does not work with \inputminted{}

### ISSUE THREAD

**Issue by neic** [gpoore/minted#154]
```LaTeX
\usepackage{minted}
\usepackage{mdframed}
\BeforeBeginEnvironment{minted}{\begin{mdframed}}
\AfterEndEnvironment{minted}{\end{mdframed}}
% or \surroundwithmdframed{minted}

\newcommand{\mdframedinputminted}[2]{\begin{mdframed}\inputminted{#1}{#2}\end{mdframed}}

% […]

\begin{minted}{latex}
This is in a frame
\end{minted}

\inputminted{latex}{noframe.tex} % This is not in a frame.

\mdframedinputminted{latex}{frame.tex} % This is in a frame.
```

I want all of my listing to be in a `mdframed`. Is it possible to support a way to do this for `\imputminted` without making a `\newcommand`? 

Thank you for a great package.

**Comment by gpoore** [comment]
`\BeforeBeginEnvironment` is from the [`etoolbox`](http://ctan.org/pkg/etoolbox) package, and only works for environments.  You could look into using some of the command macros from that package. Otherwise, a redefinition is possible.  Something like this.
```latex
\let\originalinputminted\inputminted
\renewcommand{\inputminted}[][3]{\begin{mdframed}\originalinputminted[#1]{#2}{#3}\end{mdframed}}
```
