### ISSUE TITLE
Add support for beamer overlays

### ISSUE THREAD

**Issue by mmoya** [gpoore/minted#155]
This is more a feature request.

The following snippet works in a _lstlisting_ environment:

    % lstlisting configured to escape with {||}
    \begin{frame}
      \begin{lstlisting}
        |\textcolor<2>{red}{this}| text will be red in the second frame
      \end{lstlisting}
     \end{frame}

the same `\textcolor<2>` command doesn't work in minted:

    \begin{frame}
      \begin{minted}[escapeinside=||]
        |\textcolor<2>{red}{this}| text will be red in the second frame
      \end{minted}
    \end{frame}

is it possible to add support for it?

**Comment by gpoore** [comment]
Using `escapeinside` along with `\textcolor` can work without the overlays (though `escapeinside` is fragile with some lexers). Fixing the overlays isn't something that could be done in `minted` itself. 

I'm really not sure where changes would have to be made to do this. `minted` uses `fancyvrb` internally to typeset code, and there might have to be changes at that level. Even with `fancyvrb` improvements, it's possible that there would be conflicts with the way Pygments defines its LaTeX output, particularly in terms of the `escapeinside` handling. It's also very likely that the `beamer` internals would need modification. It would be a very nice feature to have, but I don't expect any progress from within `minted` itself given all the other packages and programs involved.

You might look at this for an alternative approach: http://tex.stackexchange.com/a/51618/10742

**Comment by davidcarlisle** [comment]
I think you just need to hide the  <> from the verbatim processor, I get a
red this on the second slide from

\documentclass{beamer}
\usepackage{minted}
\begin{document}
\def\zz{\textcolor<2>{red}}
\begin{frame}[fragile]

  \begin{minted}[escapeinside=||]{python}
    |\zz{this}| text will be red in the second frame
  \end{minted}
\end{frame}
\end{document}

**Comment by gpoore** [comment]
@davidcarlisle Thanks for that. That means it's just catcodes, which means `\@noligs`. Removing `\do\<\do\>` from `\verbatim@nolig@list` seems to fix things. And it doesn't cause any issues for `minted`, because Pygments represents those characters with macros, so they don't appear literally in the code. Much less painful than expected!

```latex
\documentclass{beamer}

\makeatletter
% Removed:  \do\<\do\>
\AtBeginEnvironment{minted}{%
  \def\verbatim@nolig@list{\do\`\do\,\do\'\do\-}}
\makeatother

\usepackage{minted}

\begin{document}

\begin{frame}[fragile]
\begin{minted}[escapeinside=||]{python}
var = 'Some string' + |\only<2>{\textcolor{red}{this}}|'another string'
\end{minted}
\end{frame}

\begin{frame}[fragile]
\begin{minted}[escapeinside=||]{text}
|\textcolor<2>{red}{this} |text will be red in the second frame
\end{minted}
\end{frame}

\end{document}
```

**Comment by gpoore** [comment]
The last commit adds a `beameroverlays` option that makes the `<` and `>` work with `beamer` overlays. This requires the latest version of `fvextra`, v1.3.1.
