### ISSUE TITLE
Breakline not working with strings

### ISSUE THREAD

**Issue by tbossi** [gpoore/minted#157]
Hello,

I'm trying to display a piece of code containing some long strings (the values for "description" and "photoPath"):

```
\begin{minted}{json}
{
  "products" : {
    "-1914207197" : {
      "color" : "Blu",
      "description" : "ASICS giacca da corsa Poseidon sports. Composizione: 51% poliammide, 49% poliestere",
      "discount" : 0,
      "merchantId" : "x6Q9eCn0ogh4RstXISteaO3UpU02",
      "name" : "Giacca da corsa Poseidon",
      "photoPath" : "/merchants/x6Q9eCn0ogh4RstXISteaO3UpU02/products/-1914207197.jpg",
      "price" : 130,
    },
  }
}
\end{minted}
```

The problem is that breaklines is not working as I expected with strings.
It seems that when it finds a sequence of characters between "" it just goes on to the next token without trying to break it.
I tried both **breakanywhere** and **breakafter/before** with no result. If I use ' instead of " then breaklines works but that's not the right syntax for json.

Also, this problem is not limited to json. For example:

```
\begin{minted}[breakanywhere]{java}
System.out.println("A very long string which must be broken into multiple lines by minted/pygment.");
Long.method.calling.list.that(must.be(broken,into).several).lines(of,code.foobar);
A_very_long_variable_name.a_very_very_very_very_very_long_method_with_some_parameters(param1, param2);
\end{minted}
```

Here is the pdf: [test.pdf](https://github.com/gpoore/minted/files/913312/test.pdf)
The first line is broken only after ( and ); while the other two lines are correctly broken. 

Am I doing something wrong or is this a bug?

**Comment by gpoore** [comment]
This is happening because the highlighting style is putting a colored background behind the string text, which disables line breaking. You could change to a different highlighting style that doesn't do this, or disable the background with something like
```latex
\AtBeginEnvironment{minted}{\renewcommand{\colorbox}[3][]{#3}}
```
More details are in the manual, under `breaklines`, around pages 19-20.

**Comment by atilaromero** [comment]
In my case I found that the option \hyphenpenalty set to a high value (\hyphenpenalty=100000 in my case) to prevent hyphens also prevented  breakanywhere from working in minted. Just mentioning in case someone else sees the same problem, the solution is to avoid the \hyphenpenalty trick.
