### ISSUE TITLE
Package minted Error: Missing Pygments output

### ISSUE THREAD

**Issue by mufeili** [gpoore/minted#160]
`[19] [20]sh: /usr/local/bin/pygmentize: /usr/local/opt/python3/bin/python3.5: bad interpreter: No such file or directory system returned with code 32256.`

I recently changed a use of brew to a use of anaconda and I am not sure if this is because I changed my python environment. Is there a way to update it correspondingly? Thank you!

**Comment by gpoore** [comment]
This looks like a path or configuration issue with Python. You'll probably want to open a shell, run `pygmentize -V` to see if it can find Pygments, and then go from there.

**Comment by mufeili** [comment]
Thank you Geoffrey! I got `Pygments version 2.1.3, (c) 2006-2015 by Georg Brandl`, so I assume it can be found at least from terminal.

**Comment by gpoore** [comment]
In that case, you'll need to look at your LaTeX editor or build system to figure out what's going wrong. That can get pretty system-specific, so I may not be able to help much with that.

**Comment by mufeili** [comment]
I see. Thank you.

**Comment by GoingMyWay** [comment]
@mufeili  Have you ever try to locate where the pygmentize is? 

Same error, first you should locate where the pygmentize is?

On my Macbook, here is
```
$ which pygmentize
/Library/Frameworks/Python.framework/Versions/3.6/bin/pygmentize
```
And try to make a link
```
$ cd /usr/local/bin/
$ sudo mv pygmentize pygmentize.bak
$ sudo ln -s /Library/Frameworks/Python.framework/Versions/3.6/bin/pygmentize pygmentize
```
