### ISSUE TITLE
Copy-paste like bug in Introduction in minted.pdf

### ISSUE THREAD

**Issue by disconnect3d** [gpoore/minted#161]
Hello,

Great package!

I have found a copy-paste like bug in minted.pdf. There is:

```
For example: for compatibility with earlier versionsfor compatibility with earlier versions
```
in introduction.

**Comment by gpoore** [comment]
Thanks for pointing that out. I'll try to get it fixed in the next release. It's actually a comment in LaTeX source code that `minted` imports, which is somehow getting unescaped and then showing up as literal text...debugging may be fun!

**Comment by davidcarlisle** [comment]
I've just posted a workaround on stackexchange, and came here to report it but found this issue here already.

https://tex.stackexchange.com/q/368441/1090

**Comment by gpoore** [comment]
@davidcarlisle Thanks for that. I added it to my existing list of catcode exceptions when loading Pygments style file. Should be fixed now.

I'll try to get the new version on CTAN soon.
