### ISSUE TITLE
Minted doesn't work in tabularx environment

### ISSUE THREAD

**Issue by disconnect3d** [gpoore/minted#162]
Hello,

It seems that minted is not working with tabularx environment. Here is a minimal testcase:

```tex
\documentclass{article}

\usepackage{tabularx}
\usepackage{minted}

\begin{document}
\begin{table}[!h]
    \begin{tabularx}{\textwidth}{c}
        asd \\
        \mintinline{nasm}|mov eax, 5| \\
    \end{tabularx}
\end{table}
\end{document}
```

Commenting out the `\mintinline` line will make the document compile...

Is there any solution for it? I haven't found it in the docs/examples.

**Comment by davidcarlisle** [comment]
as documented in the tabularx package documentation, the body of tabularx
is a macro argument so you can not use verbatim constructs (including
minted). (Also tabularx has to have an X column, in your example you could
simply use tabular).

If you really need it you could put the code in an external file and use
the minted file input form rather than the inline code form.

David (tabularx author just lurking here:-)

**Comment by Virtlink** [comment]
I stumbled upon the same issue, so here's my minimal test case:

```
\documentclass[twoside,a4paper,11pt]{memoir}

\RequireXeTeX
\usepackage{tabularx}
\usepackage{minted}

\begin{document}
Text with \mintinline{java}{Inline}.

\begin{tabularx}{\linewidth}{ X }
    Some \mintinline{java}{inline} text.\\
\end{tabularx}

\end{document}
```

When compiled with:

```
pdflatex -shell-escape test.tex
```

It gives this error:

```
! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 \end{tabularx}
```

(Which is a very unhelpful error if you don't know Minted won't work inside tabularx.)

**Comment by davidcarlisle** [comment]
@Virtlink Ah well that's a different issue

there are two aspects about tabularx that affect minted

1) minted is essentially verbatim and verbatim doesn't work in the argument of another command  (including macro arguments that look like environments such as tabularx)

2) tabularx does many trial settings to find the correct column widths and during those trials it disable file writing (and other things) other wise \index and \label etc would end up being written multiple times
minted isn't expecting file writing to be disabled...

2 is relatively easy to fix just make minted do nothing during the trials (here I test that footnote has been disabled) I make it write an approximation of the right text just so the table calculation has some text to keep it happy.

\documentclass[twoside,a4paper,11pt]{memoir}

\RequireXeTeX
\usepackage{tabularx}
\usepackage{minted}
\makeatletter
\def\myinline#1#2{%
\ifx\@footnotetext\TX@trial@ftn
\detokenize{#2}%
\else
\mintinline{#1}{#2}%
\fi}
\makeatother

\begin{document}
Text with \myinline{java}{Inline}.

\noindent
\begin{tabularx}{\linewidth}{ X }
    Some \myinline{java}{if(inline)x=6} text.\\
\end{tabularx}

\end{document}
