### ISSUE TITLE
Compilation never finishes when using commas in escaped math together with breqn

### ISSUE THREAD

**Issue by BitVortex** [gpoore/minted#163]
Using 'mathescape' to escape math with commas inside, like 'i, j', does result in endless compilation when the 'breqn' package is loaded.

A minimal working example would be the following:

```latex
\documentclass[preview]{standalone}
\usepackage[usenames]{xcolor}
\usepackage[newfloat]{minted}
\newminted[mymintenv]{c}{escapeinside=||,mathescape}
\newcommand{\hlmath}[1]{\colorbox{gray}{\ensuremath{#1}}}

%\usepackage{breqn}

\begin{document}
    \begin{minted}[escapeinside=||,mathescape]{c}
#include <stdio.h>
int main(|$\hlmath{i, j}$|)
{
    // printf() displays the string inside quotation
    printf("Hello, World!");
    return 0;
}
    \end{minted}
\end{document}
```

Uncommenting the 'breqn'-import and trying to compile the document never produces a PDF or results in an error, it just doesn't finish. Removing the comma, for example to the macro `\hlmath{i}`, works with 'breqn' enabled.

**Comment by gpoore** [comment]
This is due to the way that `breqn` redefines the comma. If you add this after loading `breqn`, it should work:
```latex
\AtBeginEnvironment{minted}{\catcode`\,=12\mathcode`\,="613B}
```
I'll have to think about whether there is a way to get things like this to work automatically...there may not be, given all the possibilities of packages like `breqn`. I'll at least add a note to the documentation.

**Comment by marsmee** [comment]
To get this to work with the `\mintinline` command, one can use the following "trick":
```latex
\usepackage{etoolbox}
\pretocmd{\mintinline}{\catcode`\,=12\mathcode`\,="613B}{}{}
```
