### ISSUE TITLE
Issues on Windows: I can't write on file `thesis.pyg'

### ISSUE THREAD

**Issue by IARI** [gpoore/minted#164]
In my thesis I am using minted for listings and lots of short inline references.

I'm running TeXLive on Windows with python 3.6. I am also using the cache, kpsewhich and outputdir options:

```latex
\usepackage[cache=true,kpsewhich=true,outputdir=pdflatex_out]{minted}
```
The more inline minted usages I have, the more often I get a compiler error

```
d:/Dropbox/Informatik/master-thesis/thesis/05-implementation-UAI-protocol.tex:2
76: I can't write on file `thesis.pyg'.
<to be read again> 
                   \relax 
l.276 ...supposed to await a \protobufinline|QUIT|
                                                   action
```

When I turn minteds caching off, it seems to work fine, but compiling takes ages. I need kpeswitch as the document has several dependencies to other directories and I am building with some TEXINPUTS.

Also note, that the error position l.276 is just an example: it seemingly randomly occurs at different positions, mostly where mintedinline commands are used.

I suppose it makes little sense to give a minimal example, as the problem only occurs in the huge document and the frequency is increase with the usage of minted commands.

Sadly I have no good idea how to beginn debugging this issue and could not find anything related.

Note: I have posted this here on tex.so:

https://tex.stackexchange.com/questions/373143/compiling-issues-with-minted-i-cant-write-on-file-thesis-pyg

**Comment by gpoore** [comment]
Have you tried compiling without using `outputdir`? This seems to be related to the filesystem or temp files somehow, so if we can figure out exactly where it's happening, that may help.

Also, the package option `draft` might be useful for now, since it completely turns off highlighting and should at least let you compile quickly.

**Comment by IARI** [comment]
Thanks for the reply!

_Update:_ By now, when I do lots of compilation runs in short times, it is hardly possible to get it to run through - it will compile about 1 in 8 times. Given that with each compilation, the other auxiliary files are overwritten, it needs 2+ compilation runs for a complete toc and references to work.

---

Draft has worked of course, but that's a workaround:
If it is possible to fix compiling with the syntax highlighting, that would be preferable :)

I have just adjusted the build system such that it does not use pdflatex with the -output-directory option, and thus using minted without outputdir.
First it seemed to work as I was able to compile wihtout error for several times.
But after trying a few more times, the problem has returned.

The behaviour has been unpredictable like that before: sometimes it would not have problems for 6 or more compilation runs, and then they start again.
Particularly after a longer idle phase - i.e. when I have done no compilation in 20 minutes or more - it works better for a short time, but after a couple of runs it always returns.

It seems to me, like the writing process for the ".pyg" auxilliary file in the main directory is happening to frequently. As if it was written assynchronously, but the code would not wait for properly closing the file stream, such that it is still locked when the next writing process starts.

Sadly my tex/latex coding skills are not existent, and everything between \makeatletter and \makeatother just totally confuses me, otherwise i would have tryed to look into that myself, sorry :(.
Also i have not the slightest idea how writing aux files in latex works.

**Comment by gpoore** [comment]
I agree that it looks like there is an issue with the files, but I double checked, and the files are being opened and closed correctly. Try adding this to your preamble. It will delete the `.pyg` temp file before using it, instead of opening and overwriting the old file. Perhaps that will make a difference.

```latex
\makeatletter
\def\minted@writecmdcode#1{%
  \DeleteFile[\minted@outputdir]{\minted@jobname.pyg}
  \immediate\openout\minted@code\minted@jobname.pyg\relax
  \immediate\write\minted@code{\detokenize{#1}}%
  \immediate\closeout\minted@code}
\AtBeginEnvironment{minted}{\DeleteFile[\minted@outputdir]{\minted@jobname.pyg}}%
\makeatother
```

**Comment by IARI** [comment]
Thank you - this is interesting. Now I get the following, slightly different error:


```
(./pdflatex_out/_minted-thesis/C494376FB77814A937BA51849FA8AE6CE904D7D4D5A13AED
C289437F6035F2D8.pygtex)D:\Dropbox\Informatik\master-thesis\pdflatex_out\thesis.pyg
Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
system returned with code 1

d:/Dropbox/Informatik/master-thesis/thesis/05-implementation-UAI-Services.tex:4
9: I can't write on file `thesis.pyg'.
<to be read again> 
                   \relax 
l.49 of the \javainline|serviceType|
                                     which is
(Press Enter to retry, or Control-Z to exit; default file extension is `.tex')
```

saying, the process cannot access the file (thesis.pyg) since it is being used by another process.

**Comment by gpoore** [comment]
Here's another possibility. Is your `D:\Dropbox` directory actively being synced with Dropbox? Because if the files keep changing, and Dropbox keeps trying to sync them, that could cause some file conflicts. Maybe try without the patch, in a non-Dropbox directory. Or disable Dropbox syncing temporarily.

**Comment by IARI** [comment]
Yeah I just thought of that too -- that should have come to my mind earlier.
I think that was the actual cause of this problem.
Thanks a lot - sorry for bothering you with this.

**Comment by gpoore** [comment]
I'll put a note in the documentation about the possibility of file synchronizing tools conflicting with the temp files.
