### ISSUE TITLE
how can I \cref a minted env

### ISSUE THREAD

**Issue by amosbird** [gpoore/minted#168]
I have a SQL statement written in minted env,
```
\begin{minted}{SQL}
SELECT COUNT(*) FROM lineitem
WHERE l_shipdate <= :shipdate
\end{minted}
```

how can I add a label to it so that it can be \cref ?

**Comment by gpoore** [comment]
There is a `listing` environment if you want to turn it into a float and reference it that way. You can use `\label` inside the `listing` environment.

**Comment by amosbird** [comment]
hmm, I tried
```
\begin{listing}
\begin{minted}{SQL}
SELECT COUNT(*) FROM lineitem
WHERE l_shipdate <= :shipdate
\end{minted}
\label{test}
\end{listing}
```
but it doesn't work. ` \cref{test} ` reference to the parent section

**Comment by gpoore** [comment]
In that case, `cleveref` or the `listing` environment may need some sort of customization to work together.

**Comment by amosbird** [comment]
hmm, could you give me an example?

**Comment by gpoore** [comment]
I don't have much experience with `cleveref`. You might try asking a question at https://tex.stackexchange.com/.
