### ISSUE TITLE
No bold and italic highlighting while using bw style

### ISSUE THREAD

**Issue by rominf** [gpoore/minted#17]
I want to print my article, so I pick out "bw" style. But on output pdf I don't see any bold or italic highlights. I saw this http://tex.stackexchange.com/questions/50514/how-can-i-produce-black-and-white-source-code-using-the-minted-package question but I cannot use XeLaTeX (due incapability with some packages I use) and package courier doesn't help (should I do something besides `\usepackage{courier}`?).

Here is my code:

``` latex
\documentclass[a4paper,10pt]{article}

\usepackage[T2A]{fontenc}
\usepackage[mathletters]{ucs}
\usepackage[utf8x]{inputenc}

\usepackage{minted}
\newminted{python}{linenos,fontseries=Liberation Mono,frame=single,encoding=utf8,outencoding=utf8,fontsize=\footnotesize,style=bw}

\begin{document}

\begin{listing}
\begin{pythoncode}
class Light:
    def __init__(self):
        self.light = GL_LIGHT0 + self.number
        """Test"""
\end{pythoncode}        
\caption{Caption}
\label{lst:light}
\end{listing}

\end{document}
```

PS: I use last version (2.0) of minted package and pdflatex.

**Comment by khatchad** [comment]
I'm also experiencing this problem.

**Comment by khatchad** [comment]
Bold works ok but not italics.
