### ISSUE TITLE
How to not select the line number?

### ISSUE THREAD

**Issue by takfate** [gpoore/minted#171]
in PDF, when i select code , i will select the line number too.

**Comment by gpoore** [comment]
You can try something like this:
```latex
\usepackage{minted}

\usepackage{accsupp}

\renewcommand{\theFancyVerbLine}{%
  \protect\BeginAccSupp{ActualText={}}%
  {\rmfamily\tiny\arabic{FancyVerbLine}}%
  \protect\EndAccSupp{}}
```
This should let you copy code without the line numbers with Acrobat Reader, but it doesn't work with all PDF viewers.

Related information: https://tex.stackexchange.com/questions/30783.

**Comment by re1** [comment]
Is there a way to avoid copying line numbers in a browser?

**Comment by gpoore** [comment]
@re1 The solution I gave didn't work for all PDF viewers. I would expect that it, or something like it, might work in some browsers, but any solution like this will probably depend a lot on how the browser handles PDFs. I don't expect that there is a universal solution.

**Comment by fuhrmanator** [comment]
It seems this is also a problem for eBooks (I'm using Calibre's reader). It's too bad.
