### ISSUE TITLE
Can't use minted from subfolder

### ISSUE THREAD

**Issue by hagen93** [gpoore/minted#172]
It looks like minted doesn't recognize that it is being used from within a subfolder, e.g. when importing a file with the import package it looks like pygments is still outputting its processed files to the root directory while the IfFileExists/input commands ([minted.sty line 101/102](https://github.com/gpoore/minted/blob/master/source/minted.sty#L101)) looks for them under the current directory. See attached tarball for minimum viable example of this bug.

[test.tar.gz](https://github.com/gpoore/minted/files/1165933/test.tar.gz)
Compiled with: latexmk --shell-escape -pdf main.tex  < /dev/null

**Comment by hagen93** [comment]
Problem seems to be absent when using the subfiles package instead of import by the way

**Comment by gpoore** [comment]
`minted` does everything based on the root document directory, so it is incompatible with the `import` package's starred commands, like the `\import*{sub/}{sub.tex}` in the sample document. The starred commands only look for input in the subdirectory. However, the unstarred commands (`\import{sub/}{sub.tex}`) also look for input further up the directory tree. Removing the `*` allows the document to compile without errors.

I can add a note about this to the `minted` FAQ, but getting things to work with the starred commands probably won't happen. If `import` provided a way to locally disable its path modifications, then it would be possible to get things to work (but then the starred commands wouldn't *really* be limited only to the subdirectory). Trying to get `minted` to work with anything other than the root document directory would introduce a lot of additional complexity.

**Comment by hagen93** [comment]
Yeah, I suppose just adding a note about it is the best then. As I said above the subfiles package seems to be compatible (as far as I can see), so my solution was to just switch to that one. =)
