### ISSUE TITLE
Incompatibility with the exam class (\framed already defined)

### ISSUE THREAD

**Issue by cbourke** [gpoore/minted#181]
Using the exam class with minted leads to a conflict with the framed package.  A minimal working example:

```latex
\documentclass{exam}
\usepackage{minted}
\begin{document}
Minimum Working Example
\end{document}
```

resulting in the error message:

`/opt/local/share/texmf-texlive/tex/latex/framed/framed.sty:115: LaTeX Error: Command \framed already defined.`

I'm using minted 2.4.1 and the exam class version 2.5 (2015/05/07) on texlive

**Comment by gpoore** [comment]
You can prevent `framed` from being loaded. This only works if you will not be using `minted`'s `bgcolor` option.
```latex
\documentclass{exam}
\makeatletter
\@namedef{ver@framed.sty}{9999/12/31}
\@namedef{opt@framed.sty}{}
\makeatother
\usepackage{minted}
\begin{document}
Minimum Working Example
\end{document}
```

I will have to think about whether it makes sense to add a `minted` package option that disables `framed`.

**Comment by cbourke** [comment]
Thank you for the temporary workaround.  The problem is really with the exam class--it uses code from the framed.sty package, but does not rename environments.  Even loading the framed.sty package itself leads to the same problem.  I've contacted the author of the exam class to ask for a solution/update.  I'd definitely welcome a larger solution to the other issues involving framed and bgcolor that don't allow you to page break a minted environment.  Thanks for the awesome latex package!

**Comment by cbourke** [comment]
An update, I've been in correspondence with the author of the exam class and he has developed an update solution that does not have the naming conflicts with the framed package.  The update should be going through CTAN at some point in the future.  Once it has I can close the issue.

**Comment by cbourke** [comment]
A compatible update has been incorporated into the exam class as version 2.601beta (http://www-math.mit.edu/~psh/#ExamCls) but has not yet been finalized and pushed to CTAN.  I've verified that it works, however.  When complete I'll post again and close the issue.

**Comment by gpoore** [comment]
Thanks for the update!

**Comment by cbourke** [comment]
The latest version of the exam class has been pushed out to CTAN as of 2017/11/16 (https://ctan.org/pkg/exam) which resolves the incompatibility issue.  I'm closing this issue in response.
