### ISSUE TITLE
How do I pass extra arguments to pygmentize in 2.5?

### ISSUE THREAD

**Issue by brabalan** [gpoore/minted#182]
I have updated minted and the code that worked before (see #49) no longer works. What is the way to declare extra arguments for pygmentize in 2.5?

**Comment by gpoore** [comment]
The new option handling doesn't have anything built-in for a filter that doesn't take arguments. The code below should do what you need, and I will look into adding more filter support as part of `minted` 3.0. Note that I haven't actually fully tested the code below, because I'm currently getting errors when running the filter tests. There was an indentation error, and when I fixed that, it the symbol substitution doesn't seem to be working.

```latex
\makeatletter
\newcommand{\minted@def@optcl@filterswitch}[2]{%
  \define@booleankey{minted@opt@g}{#1}%
    {\minted@addto@optlistcl{\minted@optlistcl@g}{#2}%
      \@namedef{minted@opt@g:#1}{true}}
    {\minted@addto@optlistcl{\minted@optlistcl@g}{}%
      \@namedef{minted@opt@g:#1}{false}}
  \define@booleankey{minted@opt@g@i}{#1}%
    {\minted@addto@optlistcl{\minted@optlistcl@g@i}{#2}%
      \@namedef{minted@opt@g@i:#1}{true}}
    {\minted@addto@optlistcl{\minted@optlistcl@g@i}{}%
      \@namedef{minted@opt@g@i:#1}{false}}
  \define@booleankey{minted@opt@lang}{#1}%
    {\minted@addto@optlistcl@lang{minted@optlistcl@lang\minted@lang}{#2}%
      \@namedef{minted@opt@lang\minted@lang:#1}{true}}
    {\minted@addto@optlistcl@lang{minted@optlistcl@lang\minted@lang}{}%
      \@namedef{minted@opt@lang\minted@lang:#1}{false}}
  \define@booleankey{minted@opt@lang@i}{#1}%
    {\minted@addto@optlistcl@lang{minted@optlistcl@lang\minted@lang @i}{#2}%
      \@namedef{minted@opt@lang\minted@lang @i:#1}{true}}
    {\minted@addto@optlistcl@lang{minted@optlistcl@lang\minted@lang @i}{}%
      \@namedef{minted@opt@lang\minted@lang @i:#1}{false}}
  \define@booleankey{minted@opt@cmd}{#1}%
      {\minted@addto@optlistcl{\minted@optlistcl@cmd}{#2}%
        \@namedef{minted@opt@cmd:#1}{true}}
      {\minted@addto@optlistcl{\minted@optlistcl@cmd}{}%
        \@namedef{minted@opt@cmd:#1}{false}}
}
\minted@def@optcl@filterswitch{kwrename}{-F kwrenamefilter}
\makeatother
```

**Comment by brabalan** [comment]
Thanks a lot. Unfortunately, it does not seem to do anything. My filter works from the command line, so I would like to see the command line that minted creates. Is it possible?

**Comment by gpoore** [comment]
Around line 783 in `minted.sty` there's a line with `\immediate\typeout{\minted@cmd}`. If you uncomment this line, then the Pygments command will be written in the LaTeX command line output.

**Comment by brabalan** [comment]
I've been able to make it work. I downloaded the current .sty from here (I did not have the typeout command in my texlive 2015 version). This lead me to identify a pygments specific problem: I cannot use my filter with escapeinside. Everything now works. Thanks again!

**Comment by jeeger** [comment]
Awesome, this works for me as well with the current minted version. 
Would it be possible to include this in the standard minted style file? 

In my case, I wanted to add the `-x` argument so I could use a local lexer python file.
Using `\begin{minted}{./support/n3lexer.py:N3Lexer}` works fine with the `-x` argument, and doesn't require me to upstream my lexer into pygments.
