### ISSUE TITLE
File ended while scanning use of \\inputminted. \input{./Appendices/appendixA}

### ISSUE THREAD

**Issue by s7jones** [gpoore/minted#190]
I am trying to use input minted to add code with highlighting into my appendices. But I get the following error:

> File ended while scanning use of \\inputminted. \input{./Appendices/appendixA}

I have copied the files into the same folder as the `appendixA.tex`. In `appendixA.tex` I have:

```latex
\inputminted[]{cuda]{CUDAfile.cu}
\inputminted[]{matlab}{Matlabfile.m}
```
I am running TeXStudio and I have added a custom command:
`latexmk -e '$pdflatex=q/pdflatex %O -shell-escape %S/' -pdf`
which is set to "repeat contained compilation commands".

The default compiler is then set to the custom command.

Any ideas?

**Comment by gpoore** [comment]
I expect you have a main document that brings in `appendixA.tex`? If so, have you tried something like `\inputminted[]{cuda]{Appendices/CUDAfile.cu}`?

**Comment by s7jones** [comment]
@gpoore I just tried that but it still came up with the same error.

What does it mean by file ended?

**Comment by gpoore** [comment]
This may be a syntax issue. I just noticed that there's a curly brace *before* `cuda`, but a square bracket *after*.

**Comment by s7jones** [comment]
I think it was a syntax issue. I managed to fix it in the end. It also needed the Appendices path in front of the file too.

Thanks.
