### ISSUE TITLE
breaklines doesn't work with \mintinline when other options are set

### ISSUE THREAD

**Issue by ArchLinuxTux** [gpoore/minted#194]
When I use this command to set bgcolor as global option

```
\setmintedinline{
    bgcolor=lightgray,
}
```

Or when I set the option directely

`\mintinline[breaklines, bgcolor=lightgray]{java}{test test test test test test test test test test test test test test test test test test test test test test test}`

It does not wrap the lines, when I use the command `\mintinline`. With `\begin{minted} `it works.

**Comment by gpoore** [comment]
The documentation mentions this as a limitation of `bgcolor`. The standard ways to put a background behind inline text don't work with line wrapping.

**Comment by arch-linux-tux** [comment]
Do you have a workaround?

**Comment by arch-linux-tux** [comment]
Thanks for the hint. I looked in the documentation, but there is only a hint about `tcolorbox`. Is there an alternative to `bgcolor` for `\mintinline`? Or can I use `tcolorbox` for `\mintinline`? If yes, how so I can use `breaklines` and have a backgroundcolor?

**Comment by gpoore** [comment]
I am not aware of any workarounds. When I looked at this last, I came to the conclusion that it should be possible, but would likely be difficult to implement.

**Comment by muzimuzhi** [comment]
Text background color is similar to text underline, and having it work for multi-line text is truly non-trivial. Among the current underline implementations, the luatex package [`lua-ul`](https://ctan.org/pkg/lua-ul) is much preferable than others, when luatex engine is used.
