### ISSUE TITLE
strange unnecessary formatting

### ISSUE THREAD

**Issue by Golovanov399** [gpoore/minted#195]
I use the latest minted.sty and fvextra.sty. The [following](https://pastebin.com/usqVvVDs) .tex source produces a pdf which contains this fragment:

![image](https://user-images.githubusercontent.com/8750641/37687107-55ed182e-2cab-11e8-97e2-c2dda12eaec1.png)

Why is idx formatted like this?

**Comment by gpoore** [comment]
I'm getting the same result. Somehow the Pygments lexer for C++ is treating `idx` as a special token, but I just took a quick look at the Pygments source, and `idx` isn't showing up literally anywhere.

This is a Pygments issue. One workaround would be to use the `text` lexer instead (no highlighting). You might also try using a lexer for C or a similar language to see if that eliminates this.

**Comment by Golovanov399** [comment]
Thank you, it seems that pygments treats a token as a label as long as there is a colon after it. For example, in the same pdf there is a range-based for near the end, and `x` is considered as a label too.

I'll try to fix this, but this issue is indeed not about minted.

**Comment by gpoore** [comment]
Another option would be to customize the Pygments highlighting macros. An example is https://tex.stackexchange.com/a/348144/10742. In this case, the first of the two macro arguments is `n+nl` for the situations where `idx` is treated as a special token.

**Comment by Golovanov399** [comment]
Well ok, I created a [pull request](https://bitbucket.org/Golovanov399/pygments-main/pull-requests/1/fix-false-label-recognition-in-cases-of/diff) in pygments, while it's not applied one can make these changes (watch diff) locally somewhere like `/usr/local/lib/python2.7/dist-packages/pygments/lexers/c_cpp.py`. I forgot about colon after a class constructor, but apparently it's being parsed well (because when we reach the colon in that case we can't apply the label rule as there is no alphanumeric token between closing parenthesis and the colon).
Anyways, I think that this issue can be closed, thank you again for your help.

**Comment by muzimuzhi** [comment]
The latest pygments still has this problem in lexing c++ code containing ternary operator (`a ? b : c`), for example try
```cpp
a = val == 0 ? val : -1
```
on https://pygments.org/demo/#try

@Golovanov399 Do you remember if your PR ever got merged? It seems both the `pygments` repo and your fork have been deleted on Bitbucket hence the link
```
https://bitbucket.org/Golovanov399/pygments-main/pull-requests/1/fix-false-label-recognition-in-cases-of/diff
```
to your PR is dead. `pygments` is now on Github: https://github.com/pygments/pygments and I don't find any related PRs in its GitHub repo. Maybe you want to re-post it?

**Comment by Golovanov399** [comment]
@muzimuzhi I have filed an issue there: https://github.com/pygments/pygments/issues/1996. I don't want to post a pull-request (at least, right now), because I don't remember the details of how they parse rules, and I also do not have pygments installed right now, so fixing the issue on my side would take more time and resources than I am ready to provide.

**Comment by muzimuzhi** [comment]
@Golovanov399 Thanks!
