### ISSUE TITLE
\inputminted omits first blank lines

### ISSUE THREAD

**Issue by zengxu-yang** [gpoore/minted#198]
V2.4.1 on Debian 9.4. \inputminted with option firstline ignores the first blank lines. If I create a source file with the first few blank lines and specify firstline=1, then it loads the line from the first non-blank line, instead of the first line. This behavior is different from other text editors. I have not tried V2.5 but have not seen any reports of this problem.

**Comment by gpoore** [comment]
You want the option `stripnl=false`.

**Comment by hellotigercn** [comment]
Thanks a lot. Now I know the reason. Just some thoughts. Most text editors don't strip blank lines and this baffled me. It is not easy to find this option without knowing it. So maybe it is better to set `stripnl=false` by default?

**Comment by gpoore** [comment]
Yes, I think it's worth reconsidering the defaults. Leading blank lines seem rare, but I was also surprised by this. Trailing blank lines are more common, and people do often want them stripped. However, Pygments doesn't provide an option to strip only leading or only trailing newlines. Adding separate options for leading and trailing might be nice.
