### ISSUE TITLE
how to half the height of an empty line

### ISSUE THREAD

**Issue by emeth69** [gpoore/minted#199]
Dear Minted Developers,
I'm trying to substitute in my LaTeX documents the use of listings with minted to get the benefit of using pygmentize.

I was able to do most of what I want but still have one thing that I would like to tweak but I can't solve it (yet).

I would like to replace every empty line in the listing with an empty line with another empty line but with half of its height. This to preserve the beauty of a little bit more space between some concept and to save some space. To make my intentions clear in listing I get this behavior with:

 ` \lst@AddToHook{OnEmptyLine}{\vspace{\dimexpr-\baselineskip+\smallskipamount}`

Of course this doesn't work with minted and I've tried to hack the `\FancyVerbFormatLine` command as suggested by minted documentation but with any luck. The problem seems to be that the line is not empty when passed to `\FancyVerbFormatLine`. As you can verify in this minimal example where `\FancyVerbFormatLine` is supposed to replace the empty lines with the string "It's empty" but this never happens (here [minted-emptyline.pdf](https://github.com/gpoore/minted/files/1978175/minted-emptyline.pdf) the result I get).

```
   \documentclass[a4paper]{article}

   \usepackage{minted}
   \usepackage{ifmtarg}

   \makeatletter
   \renewcommand{\FancyVerbFormatLine}[1]{%
      \@ifmtarg{#1}{It's empty}{1#1{}2}%
   }
   \makeatother

   \begin{document}
   \begin{minted}{python3}
   def plus(x, y): return x+y
   plus.code = "add"

   def subtract(x, y): return x-y
   subtract.code = "sub"
   \end{minted}

   \end{document}
```
I'm using ifmtarg to check if a parameter is empty and the problem could be in there as well but I don't know how to check the emptiness of the line otherwise.

I hope that you could help me to solve this issue.

If you have suggestions about a better way than the one I use in listing to achieve line height reduction they are welcome.

Thank you in advance for your help.

**Comment by gpoore** [comment]
`\FancyVerbFormatLine` and the new `\FancyVerbFormatText` (from `fvextra`) receive both the line content and some formatting macros, so they aren't suitable for checking for empty lines. Here's some code that does work, using `fancyvrb` internals. However, I don't think this will allow you to modify line heights with `\FancyVerbFormatLine`, because I think `fancyvrb` is enforcing that at a different level. You might need to search the `fancyvrb` source for `\FV@Line` and look into modifying one of the higher-level macros for that.
```latex
\documentclass[a4paper]{article}

\usepackage{minted}

\makeatletter
\renewcommand{\FancyVerbFormatLine}[1]{%
  \ifx\FV@Line\empty
    It's empty
  \else
    #1
  \fi
}
\makeatother

\begin{document}
\begin{minted}{python3}
def plus(x, y): return x+y
plus.code = "add"

def subtract(x, y): return x-y
subtract.code = "sub"
\end{minted}

\end{document}
```

**Comment by emeth69** [comment]
Thank you for your reply.

Indeed this correctly test the emptiness of the line and print the test but as you supposed it doesn't work when you want to enlarge/reduce the vertical space.

I dug a little into the minted/fancyvrb packages and seems (to me) that the problem is that every line is put in a `\hbox` before passing it to the `\FancyVerbFormatLine` command.

I have tried to remove it from `\FV@BProcessLine` but it doesn't work as well. Evidently my TeX-fu (and also my Google-fu) are quite limited and I can't solve it.

Do you have any further suggestion? Or better another macro to solve directly the issue?

Thank you

**Comment by gpoore** [comment]
I just tried modifying `\FV@ListProcessLine`. I think this may do what you want:

```latex
\documentclass[a4paper]{article}

\usepackage{minted}

\makeatletter
\let\FV@ListProcessLineOrig\FV@ListProcessLine
\def\FV@ListProcessLine#1{%
  \ifx\FV@Line\empty
    \hbox{}\vspace{-5pt}%
  \else
    \FV@ListProcessLineOrig{#1}%
  \fi}
\makeatother

\begin{document}
\begin{minted}{python3}
def plus(x, y): return x+y
plus.code = "add"

def subtract(x, y): return x-y
subtract.code = "sub"
\end{minted}

\end{document}
```

**Comment by gpoore** [comment]
If you need `breaklines`, then the `fvextra` macros need to be customized instead of the `fancyvrb` one. Probably something like this:
```latex
\makeatletter
\let\FV@ListProcessLine@NoBreak@Orig\FV@ListProcessLine@NoBreak
\let\FV@ListProcessLine@Break@Orig\FV@ListProcessLine@Break
\def\FV@ListProcessLine@NoBreak#1{%
  \ifx\FV@Line\empty
    \hbox{}\vspace{\dimexpr-\baselineskip+\smallskipamount}%
  \else
    \FV@ListProcessLine@NoBreak@Orig{#1}%
  \fi}
\def\FV@ListProcessLine@Break#1{%
  \ifx\FV@Line\empty
    \hbox{}\vspace{\dimexpr-\baselineskip+\smallskipamount}%
  \else
    \FV@ListProcessLine@Break@Orig{#1}%
  \fi}
\makeatother
```

**Comment by emeth69** [comment]
Ditto, thank you. This solves this issue but still many more to go I'm afraid. To be read as: this doesn't free you from my silly questions :-)
