### ISSUE TITLE
Failure to generate pygments input hash files?

### ISSUE THREAD

**Issue by saTrilogy** [gpoore/minted#203]
Using Minted 2.5 with ActivePython 3.5.4 on a Windows 10 box, XeLaTeX via MiKTeX 2.9.6643-x64. 

Minted output for blocks and inline usage is fine when using draft=true as a package option. However, for "final", as far as I can tell, none of the @hash files are being generated in the (default) cache dir. I've manually tested the incovocation (as specified in the log) via the likes of:

pygmentize -l fsharp -f latex -P commandprefix=PYG -F tokenmerge -o _minted-Master/tmp.pygtex temp.pyg

That is not executed by the script (it simply shows the help output and does not display any error). Curiously, if I omit the -P commandprefix=PYG option then the output file is generated (using the default pygments prefix of PY).

I suspect that this is an issue with the pygments script given that draft=true works fine. I also suspect this is something obvious that I have overlooked and I wonder if it may be a conflict between the pygments script and ActivePython. What python do you generally use?

**Comment by gpoore** [comment]
In your example command, you have `temp.pyg` and `tmp.pygtex`. Is there any possibility of a `tmp` vs. `temp` issue in your command testing?

You might check which version of pygmentize you have (`pygmentize -V`), and make sure you don't have multiple versions on your PATH, perhaps with different Python installations (`where pygmentize`).

You could try downloading the `minted.sty` for minted 2.2, put that in your document directory, and see if anything changes. I think that's the last release before some modifications that affect XeTeX, though I doubt that's the issue.

I usually use the latest Anaconda Python, which comes with Pygments bundled.
