### ISSUE TITLE
can't get autogobble to work

### ISSUE THREAD

**Issue by derlin** [gpoore/minted#205]
I was using minted version 2.1 and all was fine. But with the latest version (minted v2.5), `autogobble`  has no effect. I tried it on Linux, Mac and Windows, same output. Here is my simple test setup:

```
\documentclass{article}
\usepackage{lipsum}
\usepackage[outputdir="out"]{minted}

%% minted global options
\setminted{
    autogobble,
    fontsize=\small,
    breaklines,
    showspaces,
}

\begin{document}
\lipsum[2]

\begin{minted}[autogobble]{python}
    def a_simple_func:
        print("autogobble is not working")
\end{minted}

\begin{listing}[!h] 
    \begin{minted}{python}
            # same inside a listing
            svc_params = [
                {'kernel': ['rbf'], 
                    'gamma': [1e-3, 1e-4],
                    'C': [1, 10, 100, 1000]
                },
                {'kernel': ['linear'], 
                    'C': [1, 10, 100, 1000]
                }
            ]
    \end{minted}
    \caption{indented code.}
    \label{lst:1}
\end{listing}

\lipsum[2]
\end{document}
```

The result is:

![image](https://user-images.githubusercontent.com/5463445/40680171-85f16f1e-6385-11e8-8627-a5d9f42e28bd.png)

Again, the same code **using minted 2.1 works** (but not with the penultimate version either).

**Comment by gpoore** [comment]
Version 2.2 changed how directory quoting is handled and introduced a quoting-related bug for `autogobble`. Try using `outputdir=out` (no quotes on `out`). I'll fix the quoting in the next release.

**Comment by derlin** [comment]
That was it: removing the quotes made it work. Thank you for the quick answer !
