### ISSUE TITLE
Missing key for choosing the output font encoding

### ISSUE THREAD

**Issue by eg9** [gpoore/minted#208]
The `minted` package provides the keys `fontfamily`, `fontseries`, `fontshape` and `fontseries`, but no `fontencoding`.

A document using `fontspec` on XeLaTeX or LuaLaTeX might want to have a legacy monospaced font in a `minted` environment, but with `fontspec` the output font encoding is set to TU and legacy 8 bit fonts don't support it. See, for example, https://tex.stackexchange.com/q/442174/4427

I was able to make it by patching `\FV@FontSetup` to do `\fontencoding{T1}` at the beginning. Probably patching it is necessary anyway, but I guess that the machinery of `fvextra` can deal with this.

I tried with `\setminted{formatcom=\fontencoding{T1}\selectfont}` and also by specifying `formatcom=\fontencoding{T1}\selectfont` as an option to a `minted` environment, but with no result. 

An interface such as

```latex
\setminted{fontencoding=T1}
```

would be much better.

**Comment by gpoore** [comment]
Thanks for this! I'll try to add something in the next release of `fvextra`, and then add `minted` support.

**Comment by gpoore** [comment]
This is now in `fvextra`, so `\fvset{fontencoding=T1}` works. Next, I'll add it to the `minted` options.
