### ISSUE TITLE
is there a standalone/CLI version to produce a .eps file from a code listing?

### ISSUE THREAD

**Issue by UnixJunkie** [gpoore/minted#212]
Hello,
That would be nice to be able to ship manuscripts in latex without requiring
the person who compiles the manuscript to have minted installed
(very often, publishers compile manuscripts automatically in a latex env
you have no control over).
Thanks,
F.

**Comment by gpoore** [comment]
Take a look at the `frozencache` option. This saves all the macros and highlighted code, so you can compile without `-shell-escape` and without having Pygments installed. You still do need `minted`, but if it isn't available on the system, you might try bundling `minted.sty` with the rest of your source files.

There isn't a standalone/CLI variant that generates static files for this sort of situation. While I can see how that could be useful, I don't have the time to develop or support those sorts of features.

**Comment by UnixJunkie** [comment]
I found a hack:
- load the code in emacs
- htmlize the buffer
- save the resulting html file then open it in firefox and print it as a pdf
- optionally, pdfcrop the resulting pdf
Et voila! You get your prettyfied code as pdf, which can be converted to eps or used as is. :smile:

**Comment by pablgonz** [comment]
Hello, if the document is not very complicated you can use a _perl script_ `ltximg`:

`ltximg -e --nopdf --srcenv --imgdir=myeps -o test-out test-in.ltx`

It will generate the images you need and an output file (using `pdflatex`) with the replacement code for these, to convert to `html` or what you want. The _script_ is part of `TexLive` and you can see the documentation using `texdoc ltximg`.
regards

**Comment by UnixJunkie** [comment]
ok, thanks for the info
