### ISSUE TITLE
'highlightlines' option not working properly in a 'column' environment

### ISSUE THREAD

**Issue by RdNetwork** [gpoore/minted#216]
Hi,

I'm working on beamer slides to display code using minted. I want to use 'highlightlines' to highlight two lines in particular in my code, yet the color box seems to set itself in the wrong place. And if I try to move margins (using either \hspace{} or the 'xleftmargin' option), the box moves too.

![image](https://user-images.githubusercontent.com/4118704/45950327-9d371a80-bfff-11e8-8bf3-4d812e06cfa4.png)

I'd like the color box to fit the line it highlights. Here, it is either too long on both sides (such as in the attached picture), or too short (if I try to high line 4 on the code on the left panel, for example).

Sample LaTeX code:

```
  \begin{frame}[fragile]
  	\frametitle{Example}
  	\begin{columns}
  		\begin{column}{0.5\textwidth}
  	  		\begin{minted}[tabsize=2,highlightcolor=yellow!60,highlightlines=3,xleftmargin=-1.5cm]{sparql}
				SELECT ?ad
				WHERE {
					?u	a	tcl:User.
					?u	vcard:hasAddress	?ad.
				}
			\end{minted}
		\end{column}
		
  		\begin{column}{0.5\textwidth}
  			\begin{minted}[tabsize=2,highlightcolor=yellow!60,highlightlines=3,xleftmargin=-1.5cm]{sparql}
				SELECT ?u ?age
				WHERE {
					?u	a	tcl:User.
					?u	foaf:age	?age.
				}
			\end{minted}
  		\end{column}
  	\end{columns}
  \end{frame}
```

Is there a way to control the size of the highlighting box to make it the text or at least the column size?

Thanks in advance

**Comment by gpoore** [comment]
I'd suggest removing `xleftmargin` and trying `autogobble` to eliminate the indentation. That seems to work for me. Depending on your beamer configuration, you might also reduce the font size a little. At least with beamer defaults, I need `\small` to make the lines of code short enough to prevent them from going over column margins.

```latex
\documentclass{beamer}
\usepackage{minted}
\setminted{autogobble}
\begin{document}


 \begin{frame}[fragile]
  	\frametitle{Example}
        \small
  	\begin{columns}
  		\begin{column}{0.5\textwidth}\
  	  		\begin{minted}[tabsize=2,highlightcolor=yellow!60,highlightlines=3]{sparql}
				SELECT ?ad
				WHERE {
					?u	a	tcl:User.
					?u	vcard:hasAddress	?ad.
				}
			\end{minted}
		\end{column}
		
  		\begin{column}{0.5\textwidth}
  			\begin{minted}[tabsize=2,highlightcolor=yellow!60,highlightlines=3,]{sparql}
				SELECT ?u ?age
				WHERE {
					?u	a	tcl:User.
					?u	foaf:age	?age.
				}
			\end{minted}
  		\end{column}
  	\end{columns}
\end{frame}

\end{document}
```


![untitled](https://user-images.githubusercontent.com/1660328/45967403-838fd600-bff3-11e8-84c0-79e291497bf7.png)

**Comment by RdNetwork** [comment]
Thanks, this works perfectly! Not sure how that option works but it solves it perfectly in my Beamer configuration.
