### ISSUE TITLE
Loading minted break fancyvrb environments using obeytabs

### ISSUE THREAD

**Issue by khyox** [gpoore/minted#221]
Without loading minted, the following fancyvrb environment works fine:
```
\DefineVerbatimEnvironment{OutVrb}{Verbatim}{obeytabs, baselinestretch=0.7, commandchars=\\\{\}, formatcom=\color{RedViolet}}
```

This is an example of the final output:
![image](https://user-images.githubusercontent.com/4109713/49327476-a219cc80-f562-11e8-8b8e-914a3f2e0295.png)

If I load minted (for using it in another part of the doc), then the output becomes:
![image](https://user-images.githubusercontent.com/4109713/49327499-076dbd80-f563-11e8-9f1c-5aa66321476e.png)

It seems minted patches fancyvrb so that the `obeytabs` option is no longer observed for fancyvrb environments. This is for minted 2017/07/19 v2.5. Thanks!

**Comment by gpoore** [comment]
Can you provide a complete minimal document, not just a screenshot?

**Comment by khyox** [comment]
Sure.
```
\documentclass[12pt,a4paper,notitlepage]{letter}
\usepackage{fancyvrb} 
\DefineVerbatimEnvironment{OutVrb}{Verbatim}{obeytabs, baselinestretch=0.7}
%\usepackage{minted}  % Uncomment to check issue
\begin{document}
\begin{OutVrb}
		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	1	137	137	0	3	1
Maximum:	1	260	260	36	17	134206
Mean:		1	252.457	252.457	0.18893	4.55994
\end{OutVrb}
\end{document}
```

**Comment by gpoore** [comment]
There is a conflict between the `calc` package, which is loaded by `minted`, and the `fvextra` package, which `minted` loads to extend `fancyvrb` functionality, due to the way that `calc` redefines `\setcounter`. Adding this to your preamble after loading `minted` should fix it. This fix or something like it will be in the next version of `fvextra`.
```latex
\makeatletter
\def\FV@@ObeyTabs#1{%
  \let\FV@Space@Orig\FV@Space
  \let\FV@Space\FV@Space@ObeyTabs
  \edef\FV@currentgrouplevel{\the\currentgrouplevel}%
  \setcounter{FV@TrueTabGroupLevel}{\FV@currentgrouplevel}%
  \addtocounter{FV@TrueTabGroupLevel}{1}%
  \setbox\FV@TabBox=\hbox{#1}\box\FV@TabBox
  \let\FV@Space\FV@Space@Orig}
\makeatother
```

**Comment by khyox** [comment]
It is working now. Thank you very much for your support, Geoffrey.
