### ISSUE TITLE
`highlightlines` too long for `frame=single`

### ISSUE THREAD

**Issue by APaganini** [gpoore/minted#222]
The colored box generated by `highlightlines` overlaps the frame generated by `frame=single`.

Minimal example:

```
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[frame=single,highlightlines={1}]{python}
the highlighting of this lines is too long, look here --------->
\end{minted}
\end{document}
```
and corresponding result:

<img width="948" alt="screen shot 2018-12-06 at 18 24 14" src="https://user-images.githubusercontent.com/20994366/49603828-367d9800-f984-11e8-8b8f-dd365b8bedee.png">

**Comment by gpoore** [comment]
This is already fixed in the development version of [`fvextra`](https://github.com/gpoore/fvextra), which `minted` loads internally. To use the fixed version now, before it is released, you can download `fvextra.sty` and put it in the same directory as your document.

**Comment by APaganini** [comment]
Many thanks for the quick and precise answer. Issue solved.
