### ISSUE TITLE
ubuntu MiKTeX 2.9.6840 \minted@apppathifexists=

### ISSUE THREAD

**Issue by qiuzhu** [gpoore/minted#223]
I compile the minted sample on ubuntu using the Miktex(6840) and it shows error:

```
Package ifplatform Warning: 
    I can't tell if this is Windows or *nix; you appear to be neither.

) (/home/lotus/.miktex/texmfs/install/tex/latex/xstring/xstring.sty
(/home/lotus/.miktex/texmfs/install/tex/generic/xstring/xstring.tex))
(/home/lotus/.miktex/texmfs/install/tex/latex/framed/framed.sty)
(/home/lotus/.miktex/texmfs/install/tex/latex/float/float.sty))/bin/sh: 1: Syntax error: end of file unexpected (expecting "then")
/bin/sh: 1: Syntax error: Bad for loop variable

\minted@apppathifexists=
```

**Comment by gpoore** [comment]
This is very strange. I don't think this should be able to happen unless your system doesn't have `/dev/null`. I assume you do have `/dev/null`?

If you do have `/dev/null`: Are you using `-shell-escape`? Can you post the entire log? Also, is this a virtual machine, or is there anything else unusual about it?

**Comment by gpoore** [comment]
The log didn't really help. Can you post the complete document, or at least the complete preamble (`\documentclass` through `\begin{document}`)? Also, you might try adding `\windowsfalse` right before `\begin{document}`, just to see if it does anything.

**Comment by bradrn** [comment]
I'm getting this error as well on Ubuntu, which is odd because I've always been able to build my document on Windows. Adding `\windowsfalse` does work, but it would be nice to have a solution.

**Comment by gliptak** [comment]
A possible workaround is described at https://tex.stackexchange.com/a/473224

```tex
\ProvidesFile{ifplatform.sty}
\newif\ifwindows\windowsfalse
```

**Comment by gpoore** [comment]
This issue seems to have only occurred under Linux and OS X when using MiKTeX. There have been no recent reports of this issue, so I am closing it. I suspect that there may have been issues with MiKTeX under non-Windows operating systems at the time this was reported.
