### ISSUE TITLE
Do not hightlight empty line.

### ISSUE THREAD

**Issue by ghost** [gpoore/minted#226]
Hi,

if after highlighted line there is an empty one - it's highlighted too.

Maybe someone know how to fix it?

**Comment by lx-931203** [comment]
And, can labels be used for highlighted lines interval specification?

**Comment by gpoore** [comment]
Can you provide a minimal example?

**Comment by gpoore** [comment]
That's a bug. It only occurs with `numberblanklines=false`, so you can disable that for now to fix highlighting.

**Comment by gpoore** [comment]
The bug is in `fvextra`. Simple example:
```
\begin{minted}[highlightlines=2,numberblanklines=false]{python}
# line 1
# line 2
  
\end{minted}
```

**Comment by gpoore** [comment]
This is fixed in `fvextra`. The development version of `fvextra.sty` with the fix can be [downloaded](https://github.com/gpoore/fvextra), or a new release with the fix will be on CTAN within a few days.
