### ISSUE TITLE
`bw` style doesn't applied on default fonts

### ISSUE THREAD

**Issue by lx-931203** [gpoore/minted#227]
Issue can be fixed by using `courier` package, but that font is ugly, and it's interesting how to make default fonts look ok.

Does someone knows it?

**Comment by gpoore** [comment]
That's a limitation of the default font. If you want to use `bw`, take a look at http://www.tug.dk/FontCatalogue/typewriterfonts.html, or consider using XeLaTeX or LuaLaTeX with system fonts.

**Comment by lx-931203** [comment]
It's sad.

I love precisely default fonts, it with default text font looks matching each other and form beautiful design system.

***

Ok, if I choose `Nimbus 15 Mono` - how can I use it?

**Comment by gpoore** [comment]
If you like the default, try `lmodern`.

For `Nimbus 15 Mono`, see the instructions in the linked page.
