### ISSUE TITLE
escapeinside fails in Prolog mode

### ISSUE THREAD

**Issue by jpellegrini** [gpoore/minted#229]
The following document: 

```
\documentclass{article}  

\usepackage{minted}

\begin{document}

\begin{minted}[escapeinside=\|\|,mathescape=true]{prolog}
f(x\|$\sqrt{Y}$\|).
\end{minted}

\end{document}
```

does not produce the expected result. The \|#\sqrt{Y}$\| is printed verbatim (and colorized):

![tcb-output](https://user-images.githubusercontent.com/4349360/55445618-9a127d80-5592-11e9-9728-0f9bf3d39187.png)

The output is correct if I switch to other languages, like Python or Scheme instead of Prolog.

**Comment by gpoore** [comment]
The way that Pygments implements `escapeinside` is fragile and doesn't work well with some lexers. This looks like one of those cases. See https://github.com/gpoore/minted/issues/70#issuecomment-111729930 for an example of how this sort of thing can be worked around in some instances.
