### ISSUE TITLE
Using PHP in \mintinline or \mint should default to startinline=true

### ISSUE THREAD

**Issue by Ceremony64** [gpoore/minted#23]
Normally, PHP code only gets properly highlighted if its within <?php echo "PHP in here!"; ?>  tags.

However, when using the \mint and especially the new \mintinline feature, one probably isn't using these tags and instead referring to functions, methods, objects or variables directly, so it should default the startinline option to true, instead of false (see page 15 of the minted.pdf).

Just a minor suggestion to improve this awesome package!

**Comment by gpoore** [comment]
I now finally have the capability to create inline settings separately from other settings. `\mintinline` now uses `startinline=true` by default. I'm not changing the behavior of `\mint` for backward-compatibility reasons.
