### ISSUE TITLE
Message "you must have pygmentize installed" while Pygments is already installed

### ISSUE THREAD

**Issue by bjce** [gpoore/minted#231]
I'm try to use the `minted` package in latex to display code in latex document. From Texstudio, I get an error message "you must have pygmentize installed to use this package". However, if I type `pip3 install pygments` I get `Requirement already satisfied: pygments in /usr/local/lib/python3.7/site-packages (2.3.1)` which means that `pip3` has installed it on the machine

What am I doing wrong?

Thank you very much!

**Comment by NobbZ** [comment]
Can you call the `pygmentize` executable? It needs to be in your `PATH` that `minted` can find it.

**Comment by bjce** [comment]
Thank you very much for your quick answer @NobbZ. 

So from Pyhton3 i get the following message:
```
>>> import sys
>>> sys.path
['', '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', 
'/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7', 
'/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', 
'/Users/mymac/Library/Python/3.7/lib/python/site-packages', '/usr/local/lib/python3.7/site-packages', 
'/usr/local/Cellar/numpy/1.15.4_1/libexec/nose/lib/python3.7/site-packages']
```

how can I find and call the `pygmentize` executable? Sorry for the basic question

**Comment by mbaz** [comment]
Just call `pygmentize` from the command line.

```
$ pygmentize -V
Pygments version 2.3.1, (c) 2006-2017 by Georg Brandl.
$
```

**Comment by bjce** [comment]
ok 
I get the following (copy carbon of your output)

```
$ pygmentize -V
Pygments version 2.3.1, (c) 2006-2017 by Georg Brandl.
```

**Comment by mbaz** [comment]
Are you running Latex with the `-shell-escape` option? Without it, Latex can't call outside programs. I don't use TexStudio, but it must have an option to let you configure options passed to the latex engine.

**Comment by bjce** [comment]
ok I found the answer: 

you have to run the following line in the .tex file: 

```
% !TeX TXS-program:compile = txs:///pdflatex/[--shell-escape]
```

**Comment by intractabilis** [comment]
I run LaTeX with `-shell-escape` and still have this problem. LuaHBTeX, Version 1.15.0 (TeX Live 2022). `pygmentize` is installed, in the PATH, and is runnable from command line. It seems `-shell-escape` like has no effect:
```
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `which pygmentize && mylatexfile(prev).aex'
```

**Comment by muzimuzhi** [comment]
@intractabilis I would suggest to open a new issue rather than commenting under a closed one. Same error message may be caused by different reasons.

It seems your issue is caused by the `(` and `)` in `mylatexfile(prev).tex`, which hold special meaning for the shell. 
 `\minted@jobname` need to be quoted as well, like what have been done to `pygmentize` command-line options in https://github.com/gpoore/minted/commit/25e1f300159c3e7848026688415141508248d113.

**Comment by intractabilis** [comment]
I am going to check first if it is a luatex's problem. I have a suspicion xelatex will work.

**Comment by HolgerGerhardt** [comment]
I was facing the same issue: Compiling with LuaLaTeX from the command line worked but it did not when I used TeXstudio. The solution was to tell TeXstudio the path to the `pygmentize` binary (in my case, _/Library/Frameworks/Python.framework/Versions/3.11/bin_) in the TeXstudio Preferences, section “Build”, subsection “Additional Search Paths”, field “Commands ($PATH)”.

**Comment by isx2015** [comment]
Just want to add that this this option of “Additional Search Paths” is by default hidden and you have to check the "Show Advanced Options" box at the bottom left corner to see it.
