### ISSUE TITLE
minted does not work from hevea

### ISSUE THREAD

**Issue by peterjc** [gpoore/minted#234]
Using the sample from https://www.overleaf.com/learn/latex/Code_Highlighting_with_minted saved as ``overleaf.text``,

```bash
$ hevea -version
hevea 1.10+9 of 2008-12-17
library directory: /home/xxx/lib/hevea
$ hevea  overleaf.tex 
./overleaf.tex:8: Warning: Command not found: \minted
./overleaf.tex:38: Warning: Command not found: \endminted
```

While having this work with syntax coloring would be ideal, I appreciate the shell calls may well be impossible from hevea.

Instead, I would be happy with a fallback on verbatim mode, but haven't managed to work out how.

Example file,

```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
 
\usepackage{minted}
 
\begin{document}
\begin{minted}{python}
import numpy as np
 
def incmatrix(genl1,genl2):
    m = len(genl1)
    n = len(genl2)
    M = None #to become the incidence matrix
    VT = np.zeros((n*m,1), int)  #dummy variable
 
    #compute the bitwise xor matrix
    M1 = bitxormatrix(genl1)
    M2 = np.triu(bitxormatrix(genl2),1) 
 
    for i in range(m-1):
        for j in range(i+1, m):
            [r,c] = np.where(M2 == M1[i,j])
            for k in range(len(r)):
                VT[(i)*n + r[k]] = 1;
                VT[(i)*n + c[k]] = 1;
                VT[(j)*n + r[k]] = 1;
                VT[(j)*n + c[k]] = 1;
 
                if M is None:
                    M = np.copy(VT)
                else:
                    M = np.concatenate((M, VT), 1)
 
                VT = np.zeros((n*m,1), int)
 
    return M
\end{minted}
\end{document}
```

**Comment by peterjc** [comment]
Some experimentation later, this seems to work,

```latex
\usepackage{minted}
% Minted fails on hevea, https://github.com/gpoore/minted/issues/234
% silently fall back on verbatim - ignore the language argument:
%HEVEA \newenvironment{minted}[1]{\verbatim}{\endverbatim}
```

This uses the special comment syntax, see http://hevea.inria.fr/doc/manual007.html

**Comment by gpoore** [comment]
Your solution is probably the best option. `minted` also has a `draft` mode that uses `fancyvrb`'s `Verbatim` and doesn't involve shell calls, but that is more complex than your solution. 

`minted` uses Pygments to do syntax highlighting, and Pygments can produce HTML output. However, I have no idea about what would be involved in getting hevea to do a shell call and then treat the output as raw HTML.

If you really need the highlighting, you might consider [Pandoc](https://pandoc.org/).

**Comment by peterjc** [comment]
I wasn’t optimistic about you being able to add hevea support, but this workaround will do for now.

I should try pandoc for LaTeX to HTML, it might be comparable and the tool chain is much easier to install.

Thank you. Feel free to close this as out of scope / won’t fix.
