### ISSUE TITLE
Solidity syntax

### ISSUE THREAD

**Issue by tonypottera24** [gpoore/minted#236]
Is it possible to add Solidity syntax?
Thank you!

**Comment by gpoore** [comment]
`minted` uses [Pygments](http://pygments.org/) to do the actual syntax highlighting. So adding another language means creating a new lexer for Pygments. You might do a search to see if anyone else has created a Solidity lexer. Otherwise, you might try to create one yourself.

**Comment by muzimuzhi** [comment]
@Tony-HSU 
This python package [pygments-lexer-solidity](https://pypi.org/project/pygments-lexer-solidity/) may help.
