### ISSUE TITLE
\inputminted with red box laxer errors?

### ISSUE THREAD

**Issue by TieWay59** [gpoore/minted#243]
I'm using inputminted to import a large amount of c++ code files into one document. Most of them work out fine, but some of witch has a little defect.

![example1](https://user-images.githubusercontent.com/40034603/66652050-4383ab80-ec67-11e9-8650-be7acdd6e967.png)

![图片](https://user-images.githubusercontent.com/40034603/66652231-c573d480-ec67-11e9-993d-d6c540fb8ed5.png)

In general, I meet 2 types of error,
1. "#define" used within "{ }".
2. Chinese characters unwrapped in comment line.

The second one is caused by my unreasonable file writing, I can correct it manually, but there a lot work to do then. (I really hope that there might be one solution to avoid fixing all the files. ORZ)  
As for the first, I still have no idea how to deal with it.

I've checked similar issues below, but not helping in my situation.(Maybe it's because I use inputminted.)

#238 
#69 

 
My tex file write like below:
``` tex
\documentclass[a4paper,11pt]{article}
\usepackage{fontspec}
\setmonofont{Consolas} 
\usepackage[a4paper,left=18mm,right=18mm,top=15mm,bottom=15mm]{geometry} 
\usepackage{CHIsupport}  % Simplified Chinese Support using my own settings.


\usepackage{minted}   
\setminted{
    linenos=true,
    breaklines=true,
    encoding=utf8,
    fontseries=heiti,
    % autogobble=true,
    frame=lines
}      
%\usemintedstyle{rainbow_dash}


% learned from issue #238 #69 
\makeatletter
\AtBeginEnvironment{minted}{\dontdocolorbox}
\def\dontdofcolorbox{\renewcommand\fcolorbox[4][]{##4}}
\AtBeginEnvironment{minted}{\renewcommand{\colorbox}[3][]{#3}}
\makeatother

% some other elements

\inputminted[autogobble]{c++}{D:/tmplz/templates/其它/IO/fread2.cpp}
```

problem code fitting my first error.
```cpp
namespace IO{ 
    #define BUF_SIZE 100000 
    #define OUT_SIZE 100000 
    #define ll long long 
    //fread->read 
 
    bool IOerror=0; 
    inline char nc(){ 
        static char buf[BUF_SIZE],*p1=buf+BUF_SIZE,*pend=buf+BUF_SIZE; 
        if (p1==pend){ 
            p1=buf; pend=buf+fread(buf,1,BUF_SIZE,stdin); 
            if (pend==p1){IOerror=1;return -1;} 
            //{printf("IO error!\n");system("pause");for (;;);exit(0);} 
        } 
        return *p1++; 
    } 
    #undef ll 
    #undef OUT_SIZE 
    #undef BUF_SIZE 
};
 

```

**Comment by gpoore** [comment]
The easiest option is probably to disable the red boxes. For one way to do that, see https://tex.stackexchange.com/a/343506/10742.

**Comment by TieWay59** [comment]
Thank you, really helped.
