### ISSUE TITLE
Add option to disable console set messages

### ISSUE THREAD

**Issue by evandrocoan** [gpoore/minted#244]
When I run this, I got a bunch of set messages on the console. Can you add a verbose option for this package, allowing to disable these verbose messages?
```
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6400)
entering extended mode

D:\monograph>set  /p x=F:\Python\Scripts\pygmentize.exe 0<nul: 1>>main.aex

D:\monograph>set  /p x= 0<nul: 1>>main.aex

D:\monograph>set  /p x= 0<nul: 1>>main.aex
gross execution time: 59786 ms
```

**Comment by evandrocoan** [comment]
These set messages can be disabled by adding `@echo off`:
```latex
  \ifwindows
    \DeleteFile{\minted@jobname.aex}
    \ShellEscape{for \string^\@percentchar i in (#1.exe #1.bat #1.cmd)
      do set > \minted@jobname.aex <nul: /p
      x=\string^\@percentchar \string~$PATH:i>> \minted@jobname.aex}
    %$ <- balance syntax highlighting
```
-->
```latex
  \ifwindows
    \DeleteFile{\minted@jobname.aex}
    \ShellEscape{@echo off
      for \string^\@percentchar i in (#1.exe #1.bat #1.cmd)
      do set > \minted@jobname.aex <nul: /p
      x=\string^\@percentchar \string~$PATH:i>> \minted@jobname.aex}
    %$ <- balance syntax highlighting
```
1. https://superuser.com/questions/1078866/how-to-hide-commands-in-the-prompt-of-windows-10-from-a-batch-file

**Comment by evandrocoan** [comment]
On linux it is also polluting the console:
```latex
\ShellEscape{which #1 && touch \mintedjobname.aex}
-->
\ShellEscape{which #1 > /dev/null 2>&1 && touch \mintedjobname.aex}
```

**Comment by gpoore** [comment]
Are you running MiKTeX with `-quiet` or a similar option? If that's the case, then I can see how modifying things to hide the output could be helpful...TeX Live doesn't have `-quiet`, so I haven't run across this particular issue before. I'm happy to look into changing this for the next version of `minted`, but I have no idea when that will be released.

**Comment by evandrocoan** [comment]
Yes, I use quiet mode on both Miktex (windows) and Texlive (linux) and these messages keep popping. May be they should be moved to some option like debug mode of `minted`?

I use TexLive 2017 (Debian 9) and pdflatex with `--interaction=nonstopmode` and it makes latex quiet. This is my makefile which works with both TexLive and Miktex: https://github.com/evandrocoan/ufscthesisx-setup/blob/master/makerules.mk#L121-L152

**Comment by gpoore** [comment]
These console messages are no longer present in `minted` v3.0, which is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon.
