### ISSUE TITLE
How to configure the `listing` environment spacings?

### ISSUE THREAD

**Issue by evandrocoan** [gpoore/minted#247]
Usually, for any memoir like list, I can redefine spacing as `\cftLISTNAMEnumwidth`, but trying to redifine `\cftlistingnumwidth` results in `Undefined control sequence. argument> \cftlistingnumwidth`

References:
1. https://tex.stackexchange.com/questions/63856/how-to-increase-the-numwidth-for-a-part-in-toc
1. https://tex.stackexchange.com/questions/514715/how-to-fix-minted-and-listings-hyphen-alignment-on-my-list-of-codes

**Comment by gpoore** [comment]
The `listing` environment is created with the `float` package by default, or with the `newfloat` package if you use the `newfloat` package option when loading `minted`. There may be some sort of incompatibility between one or both of those and `memoir`. If there is an incompability, it will probably be easier to define your own float using whatever `memoir` recommends.
