### ISSUE TITLE
When using helvatica or other font families, some special characters in latex syntax give weird output

### ISSUE THREAD

**Issue by ywwry66** [gpoore/minted#250]
Tested platforms: Windows 10, MacOS Catalina
Versions: Pygments 2.5.2, LaTeX2e <2020-02-02>, minted 2.5

Minimal example:
```
\documentclass{article}

\usepackage{minted}

\begin{document}
\begin{minted}[fontfamily=helvetica]{c}
_{}\
\end{minted}
\end{document}
```
Expected output:
_{}\

Actual output:
˙–˝“

**Comment by gpoore** [comment]
Try adding `\usepackage[T1]{fontenc}`.

Ideally, `fancyvrb` (which `minted` uses internally for typesetting code) would check for this sort of thing. I may add a note to the `minted` documentation.

**Comment by ywwry66** [comment]
Thanks for answering.

Adding `\usepackage[T1]{fontenc}` did solve my issue. It would be nice to have some reference on this in the documentation.
