### ISSUE TITLE
Standard gap between normal text flow and minted code.

### ISSUE THREAD

**Issue by ghost** [gpoore/minted#256]
Hello!

There is some code.

```tex
  Some text here.
  \begin{minted}[linenos]{text}
40xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  \end{minted}
  And some text here.
```

And a screenshot.

![Screenshot from 2020-03-27 12-30-05](https://user-images.githubusercontent.com/61045198/77741942-be2e6080-7026-11ea-8031-41adcf09a563.png)

Can someone help to reduce space before and after minted code? To make coded looks like normal text.

**Comment by muzimuzhi** [comment]
The gap is the normal list gap added by `fancyvrb` package. You can use `fancyvrb` option `listparameters` to eliminate it. Unfortunately, this option is undocumented in `fancyvrb`'s doc, and not inherited by `fvextra`, nor `minted`. In short, you can use `\fvset{listparameters=...}` to alter the gap and you can only use this way. 

To get to know what dimensions affect "list gap", the picture in https://latexref.xyz/list.html#list and Figure 1 in doc of `enumitem` package both help.

Full example:
```tex
\documentclass{article}
\usepackage{minted}

\begin{document}
\subsection*{Before}
Some text here.
\begin{minted}[linenos]{text}
40xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
\end{minted}
And some text here.

\fvset{listparameters=\setlength{\topsep}{0pt}\setlength{\partopsep}{0pt}}

\subsection*{After}
Some text here.
\begin{minted}[linenos]{text}
40xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
\end{minted}
And some text here.
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/77760528-77198d00-7071-11ea-9ee7-f9dcb64c051f.png)

PS: What a coincidence that I have just found that option (from `fanvyvrb`'s source code) one hour ago and then encountered corresponding questions both on [TeX.SX](https://tex.stackexchange.com/a/534447/79060) and at here.

**Comment by gpoore** [comment]
@muzimuzhi Thanks for that! I will add `minted` support for `listparameters` in `\setminted`. I will also look into adding `listparameters` to the `fvextra` documentation of undocumented `fancyvrb` features. It might also be worth contacting the `fancyvrb` maintainer to see about getting it added to the official documentation...there have been a few `fancyvrb` updates recently, so it might get added.

**Comment by muzimuzhi** [comment]
@gpoore 
> I will add `minted` support for `listparameters` in `\setminted`. I will also look into adding `listparameters` to the `fvextra` documentation of undocumented `fancyvrb` features.

Maybe this is a chance to finish #208 altogether. Currently option `fontencoding` is added to `fvextra` but not `minted`.

> It might also be worth contacting the `fancyvrb` maintainer to see about getting it added to the official documentation...there have been a few `fancyvrb` updates recently, so it might get added.

There might be more undocumented `fancyvrb` options, for example `formatcom*`. It can be used to append code to `formatcom=<code>`. 

I will contact the `fancyvrb` maintainer after a thorough source reading. Also, I have mailed to hvoss (his tug email address) about some problems including [this one](https://tex.stackexchange.com/q/499833) at July 2019 and have not received any response till now. I will try again.

**Comment by gpoore** [comment]
`listparameters` is now supported in `minted` v3.0, which is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon. It's also documented in the next `fvextra` release.
