### ISSUE TITLE
Input stack exceeded on certain number of lines.

### ISSUE THREAD

**Issue by Myrdden** [gpoore/minted#257]
Hi, new to TeX, I've been writing a document with a lot of code examples. I have an enviroment defined in the preamble, `\newminted[code]{js}`, then I have loads of `\begin{code}...\end{code}` blocks throughout the document. When I exceed a certain number of lines within code blocks, seemingly regardless of what's in them, I've tried with just two characters spaced by a bunch of newlines, the stack exceeds, and no amount of increasing it helps. So I get the feeling I'm not using this package in at all the way it was intended.

**Comment by muzimuzhi** [comment]
If you are using `bgcolor` option, this is similar to #224.

**Comment by Myrdden** [comment]
I am indeed, and #224 fixed it. Thanks!
