### ISSUE TITLE
How to pass optional argument to \newminted

### ISSUE THREAD

**Issue by Ynjxsjmh** [gpoore/minted#259]
I want to use minted to extend the `Codex` environment to support C++ syntax highlighting. 

```latex
\documentclass[11pt]{article}

\usepackage{fancyvrb}


\DefineVerbatimEnvironment%
  {Codex}{Verbatim}
  {fontsize=\small,baselinestretch=0.9,xleftmargin=3mm,%
  frame=lines,labelposition=all,framesep=5pt}


\begin{document}

\begin{Codex}[label=bfs\_template.cpp]
#include "bfs_common.h"

vector<state_t> bfs(state_t &start, const vector<vector<int>> &grid) {
    queue<state_t> q;
    unordered_set<state_t> visited;
    unordered_map<state_t, state_t> father; 

    auto state_is_target = [&](const state_t &s) { /*...*/ };

    assert (start.level == 0);
    q.push(start);

    return vector<state_t>();
    //return 0;
}
\end{Codex}

\end{document}
```

Looking through the [documentation](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/minted/minted.pdf), I decide to use `\newminted`. I came across the `Codex` extension:

```latex
\newminted[mcodex]{cpp}
{
  fontsize=\small,
  baselinestretch=0.9,
  xleftmargin=3mm,
  frame=lines,
  labelposition=all,
  framesep=5pt,
}

\newenvironment{Codex}[1][]
{%
  \VerbatimEnvironment
  \begin{mcodex}[#1]%
}
{%
  \end{mcodex}
}
```

Replacing the former `Codex`  with it gives me the error:

<details>
<summary>
After replacing
</summary>

```latex
\documentclass{article}

\usepackage{fancyvrb}
\usepackage{minted}


\newminted[mcodex]{cpp}
{
  fontsize=\small,
  baselinestretch=0.9,
  xleftmargin=3mm,
  frame=lines,
  labelposition=all,
  framesep=5pt,
}

\newenvironment{Codex}[1][]
{%
  \VerbatimEnvironment
  \begin{mcodex}[#1]%
}
{%
  \end{mcodex}
}

\begin{document}

\begin{Codex}[label=bfs\_template.cpp]
#include "bfs_common.h"

vector<state_t> bfs(state_t &start, const vector<vector<int>> &grid) {
    queue<state_t> q;
    unordered_set<state_t> visited;
    unordered_map<state_t, state_t> father; 

    auto state_is_target = [&](const state_t &s) { /*...*/ };

    assert (start.level == 0);
    q.push(start);

    return vector<state_t>();
    //return 0;
}
\end{Codex}

\end{document}
```

</details>

```
FancyVerb Error:
  Extraneous input `[label=bfs\_template.cpp]' between \begin{Codex}[<key=value>] and line end
```

The problem might be that I pass an optional argument `[label=bfs\_template.cpp]` to `Codex` environment.

I think `8.8 Command shortcuts` in the documentation might help, but I don't understand what does @ and ## mean.

> Now, we define two environments. The first takes no further arguments. The second, starred version, takes an extra argument that specifies option overrides.

```latex
\newenvironment{\minted@envname}
{\VerbatimEnvironment
\begin{minted}[#3]{#2}}
{\end{minted}}
\newenvironment{\minted@envname *}[1]
{\VerbatimEnvironment\begin{minted}[#3,##1]{#2}}
{\end{minted}}}
```

**Comment by gpoore** [comment]
When you are defining custom verbatim environments, it's usually best to have no arguments or only mandatory arguments. Maybe try `\newenvironment{Codex}[1]` and then use `\begin{Codex}{}` when there are no options. It is possible to use optional arguments with custom verbatim environments, but only if you use some custom argument parsing macros (for example, see https://tex.stackexchange.com/q/9035/10742).

**Comment by Ynjxsjmh** [comment]
Thank you for your reply. I actually don't know what's the term of `[label=bfs\_template.cpp]`, I look at the fanvrb's document. It's referred as optional argument in one place.

`Codex` environment must take and take only a `[label=xxx]` argument to add a title to the code blocks like the image below with some hacking. Another `Code` environment handles the no options situation.

![image](https://user-images.githubusercontent.com/40143136/80313576-423e5880-881e-11ea-899c-f5bc8589f2b8.png)

Your link is really helpful. But I'm new to LaTeX, I have no idea how to use their solution.

Now I'm trying to find a solution to just display the label=xxx as caption.

**Comment by Ynjxsjmh** [comment]
I came up with a solution using [keyval](http://ctan.org/pkg/keyval) to parse `[label=xxx]`

```
\newminted[mcodex]{cpp}
{
  linenos,
  fontsize=\small,
  baselinestretch=0.9,
  xleftmargin=3mm,
  frame=lines,
  labelposition=all,
  framesep=5pt,
}

\newenvironment{longlisting}{\captionsetup{type=listing}}{}

\usepackage{keyval}

\makeatletter
% ========= KEY DEFINITIONS =========
\define@key{mymacro}{label}{\def\mm@label{#1}}

\newenvironment{Codex}[1][]
{%
  \VerbatimEnvironment
  \begin{longlisting}
  \begingroup%
  \setkeys{mymacro}{label={FIRST arg},#1}%
  \caption{\mm@label}%
  \endgroup%
  \begin{mcodex}%
}
{%
  \end{mcodex}
  \end{longlisting}
}
\makeatother
```
