### ISSUE TITLE
Working well till Anaconda reinstall

### ISSUE THREAD

**Issue by phsheth** [gpoore/minted#261]
The minted package was working very well till one day the Anaconda package broke due to other reasons and I had to do a fresh install of the Anaconda installation and Pygments library from conda.

After that - any new code included on the file is not accepted and an error is thrown. Incidentally, any old code written before the crash, even if copy+pasted ahead of the book, gets printed, but any new code simply gives an error. Can you help me here? Have also posted on SO.

https://tex.stackexchange.com/questions/541805/new-code-cannot-be-written-by-pdflatex-error-due-to-pygmentize-output

**Comment by phsheth** [comment]
Ok - sorry this is not staged, but I found a work around.

Pygments installed using Conda is not working. I remember that in my earlier install - i had installed pygments using pip.

To test this, I created a virtual environment and installed only Python using conda and Pygments using pip and it works well again!


Ideally - pygments installed using conda should also work.

**Comment by gpoore** [comment]
The old code is probably working because of the cache (`_minted` directory). This sounds like an issue with conda's packaging of pygments. If that's the case, there probably isn't anything I can help with, since I don't have any involvement with conda or pygments.

**Comment by phsheth** [comment]
I understand sir. We have found a work around anyways. Thanks a lot for creating and maintaining the minted package sir! Stay Safe!
