### ISSUE TITLE
Linebreak after hyphen

### ISSUE THREAD

**Issue by jendrikw** [gpoore/minted#263]
When using `breakafter={ :.}`, I still get a linebreak after a hyphen. How can I prevent that?

### Code to reproduce:

```latex
\documentclass{article}
\usepackage{showframe} % for this demo
\usepackage{minted}
\setmintedinline{
	breaklines=true,
	breakafter={ :.},
}
\begin{document}
	\mintinline{text}{abcabcabc -abcabcabc -abcabcabc -abcabcabc -abcabcabcabcabcab -abcabcabc -abcabcabc}
\end{document}
```

Result:

![image](https://user-images.githubusercontent.com/12938023/82317608-d25f6000-99ce-11ea-940c-3d9532672549.png)

**Comment by gpoore** [comment]
I can't get your example to reproduce the issue under TeX Live 2020. The hyphen is never left by itself. Which TeX distribution and version are you using? It's possible something is out of date.

**Comment by jendrikw** [comment]
Thanks for investigating. I'm using minted `2017/07/19 v2.5` from texlive 2019.52575 as distributed by Arch Linux (https://www.archlinux.org/packages/extra/any/texlive-latexextra/) with Python 3.8.2 and Pygments 2.6.1.

**Comment by gpoore** [comment]
I'm using the same minted and Pygments.

I just found that I can reproduce the issue by using lualatex instead of pdflatex (which is what I tried before). It seems that the Pygments hyphen definition is causing issues. Try adding this to your preamble, after loading minted. It hooks into an existing Pygments patch to modify the hyphen
```latex
\makeatletter
\let\minted@patch@PYGZsq@orig\minted@patch@PYGZsq
\expandafter\def\expandafter\minted@patch@PYGZsq\expandafter{%
  \minted@patch@PYGZsq@orig
  \gdef\PYGZhy{\mbox{-}}}
\makeatother
```

**Comment by jendrikw** [comment]
I don't know why the behaviour is different between pdfLaTeX and LuaLaTeX, but  your fix works. Thanks a lot.

**Comment by muzimuzhi** [comment]
Alternatively, you can use `\apptocmd` from `etoolbox` package, which is already loaded by `minted`.

```tex
\apptocmd\minted@patch@PYGZsq
  {\gdef\PYGZhy{\mbox{-}}}
  {}{\fail}
```

PS: Having no idea why the pygments default definition ``\gdef\PYGZhy{\char`\-}`` does not work for lualatex.

**Comment by gpoore** [comment]
I finally tracked down the source of the difference between pdfLaTeX and LuaLaTeX. LuaLaTeX needs `\automatichyphenmode=2` to give pdfLaTeX behaviour for hyphens, so for now that will probably be the best workaround for line breaks around hyphens.

This needs to be addressed in `fvextra`, which `minted` uses internally for code typesetting. I'm closing this issue. Further progress can be tracked at https://github.com/gpoore/fvextra/issues/14.
