### ISSUE TITLE
outputdir alternative?

### ISSUE THREAD

**Issue by thomaslepoix** [gpoore/minted#264]
Hi there, thank you for minted!

I am currently wrapping a latex project into CMake and trying to do it properly, that is to say with a proper separation between source tree and build tree which is not so easy with latex.

Things were good but when I tried to use minted and the `--output-directory` latex compiler argument, here came the `outputdir` issue.

I read these issues https://github.com/gpoore/minted/issues/13 https://github.com/gpoore/minted/issues/27 https://github.com/gpoore/minted/issues/141 and my question is :

Is there a real need for minted to _know_ the location of its temporary files (calling pygments maybe?) ?

Doesn't it avoid the problem to simply letting it write its files to the `--output-directory` specified dir and assuming there are also accessible to the latex compiler? So that at compile time the user could add the output directory to the compiler input locations using the [`TEXINPUTS` variable](https://tex.stackexchange.com/questions/93712/definition-of-the-texinputs-variable), just as we do to include images or tex files located _elsewhere_.

I am thinking of something like this (which do not work at this time) :

```sh
<build_dir> $

    TEXINPUTS=<out_dir>: xelatex --shell-escape --output-directory=<out_dir> <source_dir>/main.tex
```

**Comment by muzimuzhi** [comment]
The value passed to command line option `-output-directory` cannot be retrieved from inside (La)TeX.

**Comment by thomaslepoix** [comment]
Yes, I understand. My question is precisely : Is there for minted a particular need to know the output directory?

Because if the only thing we want to achieve is to include back temporary files produced here, the `TEXINPUTS` mechanism allows it without hardcoding the output directory in the source files

**Comment by gpoore** [comment]
The problem is that minted needs to tell pygmentize where the output directory is, so that pygmentize can open temp files containing code and highlight them. All of the LaTeX things--writing temp files and reading back output--work fine automatically.

**Comment by thomaslepoix** [comment]
I see.. okay.

I just found a way to specify it at build time. Looks quite ugly but in fact it's not so bad.

```sh
xelatex --shell-escape --output-directory=<out_dir> "\def\outputdir{<out_dir>} \input{<source_dir>/main.tex}"
```

```tex
\usepackage[outputdir=\outputdir]{minted}
```

**Comment by gpoore** [comment]
@thomaslepoix That looks like a nice solution for your case. That is an advantage of a build system--since you know the directory, you can pass it on to both LaTeX and minted.

**Comment by TakingItCasual** [comment]
This can be automated with `currfile-abspath`, see https://tex.stackexchange.com/a/548869. Perhaps this functionality should be merged into minted?

**Comment by gpoore** [comment]
@TakingItCasual Thanks for mentioning that! That looks like it might be a way to automate `outputdir` handling, at least in some cases. I've opened a new issue to look into this further in the future: https://github.com/gpoore/minted/issues/268. Unfortunately, `currfile-abspath` has different behavior under MiKTeX (path data may not exist or can be outdated), so using it won't be a simple process and some sort of fallback mechanisms would have to be implemented.
