### ISSUE TITLE
Consider `currfile-abspath` to manage `outputdir` automatically

### ISSUE THREAD

**Issue by gpoore** [gpoore/minted#268]
See https://github.com/gpoore/minted/issues/264#issuecomment-642442238 and https://tex.stackexchange.com/a/548869/10742. `currfile` documentation: https://ctan.org/pkg/currfile.

A few limitations with this approach:
* Requires `-recorder`.
* TeX Live apparently works fine (at least under Windows and Linux according to the documentation). MiKTeX apparently can't access data during the first compile, and path changes aren't accessible for two compiles. So some sort of fallback to disable highlighting would probably be needed during compiles when data is not available or is outdated (and there would need to be a way to check for being outdated).

**Comment by ysalmon** [comment]
I find that with LuaLaTeX it is possible to get access to the command line and therefore to the output directory. I have set
```latex
\usepackage{iftex}
\ifluatex
  \usepackage{shellesc, luacode}
  \begin{luacode*}
    function parseargv()
      local rep = {}
      for k, x in pairs(arg) do
          local kw, vw = string.match(x, "([^=]+)=?([^=]*)")
          rep[kw] = vw
      end
      return rep
    end
    local arguments = parseargv()
    
    local outputdir = arguments["--output-directory"]
    if outputdir ~= nil then
      tex.print([[\PassOptionsToPackage{outputdir={]]..outputdir..[[}}{minted}]])
    end
  \end{luacode*}
\fi
```

**Comment by gpoore** [comment]
The output directory is now detected automatically in `minted` v3.0, when used with TeX Live 2024 which adds better output directory support with the `TEXMF_OUTPUT_DIRECTORY` environment variable. `minted` v3.0 is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon.
