### ISSUE TITLE
Add note to documentation about Python version

### ISSUE THREAD

**Issue by kernie** [gpoore/minted#269]
Hi there,

this is a question on how compatible this package is with Python3 and python3-pygments ?

With Debian 10 I discovered that installing python-pygments would install Python2 stuff, but the shell executable _pygmentize_ wouldn't be around. With _python3-pygments_ the shell executable _pygmentize_ is in place and seems to work without problems.

Is there experience with Python3 and _minted_ ?

Thanks!

**Comment by gpoore** [comment]
Python 3 works fine. I'm not sure why Debian would handle pygmentize that way.
