### ISSUE TITLE
Can't get minted to work on Mac with TexMaker ("Missing Pygments output;"

### ISSUE THREAD

**Issue by adrifoster** [gpoore/minted#270]
Hi, 

I know others have had this issue but I can't seem to solve it in the ways they have. I am trying to use minted and keep getting this error:

```
! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9 \end{minted}
                
This could be caused by using -output-directory or -aux-directory 
without setting minted's outputdir, or by using a build tool that 
changes paths in ways minted cannot detect, 
or using frozencache with a missing file.

(./test_doc.aux)
runsystem(rm test_doc.pyg)...executed.

 ) 

```

I have installed Pygments and also have pygmentize.

```
acfoster@Adriannas-MacBook-Pro ~ % which pygmentize
/usr/local/bin/pygmentize
acfoster@Adriannas-MacBook-Pro ~ % which python
/usr/bin/python
acfoster@Adriannas-MacBook-Pro ~ % python --version
Python 2.7.16
```
I'm not sure if the problem is not being able to see the correct version of python/pygmentize. Here is the simple latex script I tried:

```
\documentclass{article}
\usepackage{minted}

\begin{document}
\begin{minted}{c}
int main() {
printf("hello, world");
return 0;
}
\end{minted}
\end{document}

```
I also tried` \usepackage[outputdir=.texpadtmp]{minted}` but that resulted in the same errors.

If anyone has any solutions that would be really helpful!

**Comment by gpoore** [comment]
My guess is that this is some sort of Python configuration issue with TexMaker. Does TexMaker give you any additional feedback besides the log? Or are there any additional errors earlier, before the one you copied here? Sometimes there is an earlier error that is the real problem, but things don't stop until a later error.

**Comment by adrifoster** [comment]
Hmm, I can't seem to find anything but here is my full log file.
[test_doc.log](https://github.com/gpoore/minted/files/4949964/test_doc.log)

**Comment by gpoore** [comment]
Are you using any kind of build tool like latexmk or arara? Or using `-output-directory`?

You might also try deleting the `_minted-*` directory in the document directory if it exists. Perhaps also try deleting any temp files.

**Comment by adrifoster** [comment]
I don't believe I am using any extra build tools - just TexMaker (sorry I am somewhat new to Latex). The command I'm using is:

`"pdflatex" -synctex=1 --shell-escape -interaction=nonstopmode %.tex` Should I try using -output-directory? I deleted the _minted* directories and any temp files and still got the same issue...

**Comment by muzimuzhi** [comment]
Does it work ok if you run `pdflatex -synctex=1 -shell-escape -interaction=nonstopmode test_doc.tex` manually in terminal/shell?

**Comment by adrifoster** [comment]
No, but I do get a more interesting error!

```
(./test_doc.aux)
(/usr/local/texlive/2018/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 11, in <module>
    load_entry_point('Pygments==2.6.1', 'console_scripts', 'pygmentize')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/cmdline.py", line 161
    print("%s not found!" % what, file=sys.stderr)
                                      ^
SyntaxError: invalid syntax
system returned with code 256
 (./.texpadtemp/_minted-test_doc/default-pyg-prefix.pygstyle)Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 11, in <module>
    load_entry_point('Pygments==2.6.1', 'console_scripts', 'pygmentize')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/cmdline.py", line 161
    print("%s not found!" % what, file=sys.stderr)
                                      ^
SyntaxError: invalid syntax
system returned with code 256

(./.texpadtemp/_minted-test_doc/default.pygstyle)Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 11, in <module>
    load_entry_point('Pygments==2.6.1', 'console_scripts', 'pygmentize')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/cmdline.py", line 161
    print("%s not found!" % what, file=sys.stderr)
                                      ^
SyntaxError: invalid syntax
system returned with code 256


! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...            
```                      

It seems to be an issue with the python script cmdline.py. There is a "syntax error". Do you think it's my python environment? That script works when I run it using python3.8 but not python 2.7.1, which is what I think Latex is seeing...

**Comment by muzimuzhi** [comment]
>   File "/Library/Python/2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/cmdline.py", line 161
>     print("%s not found!" % what, file=sys.stderr)

You are running `pygments` 2.6.1 with python 2.7, which is not supported.

From [`pip` page of `pygments`](https://pypi.org/project/Pygments/), its latest version 2.6.1 requires python 3.5 at least, and doesn't support python 2.x anymore.

**Comment by muzimuzhi** [comment]
Another potential problem:

From the following lines in your uploaded [test_doc.log](https://github.com/gpoore/minted/files/4949964/test_doc.log), it seems you have editor Texpad installed (note the directory `.texpadtmp`).

```
runsystem(mkdir -p .texpadtmp/_minted-test_doc)...executed.
...
 (./.texpadtmp/_minted-test_doc/default-pyg-prefix.pygstyle)
(./.texpadtmp/_minted-test_doc/default.pygstyle)
runsystem(pygmentize -l c -f latex -P commandprefix=PYG -F tokenmerge -o .texpa
dtmp/_minted-test_doc/E5B7FCB460DA1505834679098F3A71AF.pygtex .texpadtmp/test_d
oc.pyg)...executed.
```

From Texpad's [helper page for `minted`](https://www.texpad.com/support/macos/typesetting/typesetting-minted), you need to load `minted` with `\usepackage[outputdir=.texpadtmp]{minted}`. Or

> by opening preferences, choosing the typesetting pane, and unchecking “Hide Intermediate Files”.

**Comment by adrifoster** [comment]
Hi there,

Yeah the .texpadtmp didn't work for me but I was finally able to get it to work! I had to do 

The problem was that the python3 version of pygments/pygmentize wasn't in my $PATH and I hadn't realized that macOS doesn't use .bash_profile anymore but .zshrc....  So adding `PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"` to my .zshrc got pygmentize to work. Latex still couldn't find it so I then did a symlink of the pygmentize script to usr/local/bin and now it works.  Phew...

Thanks for the help!

**Comment by PhillipPflaum** [comment]
Hi,

can you please explain what you did in a bite more detail. I'm not really a pc expert.
I use MacTex not Texmaker but MacOs too. I get the same error all the time and I don't know how to fix this. I just barely understand what you're saying and it would be nice if you could explain me how I could fix this.
Or maybe if someone else does know what you did in detail would it be nice if they'd let me know.

thanks for that

**Comment by muzimuzhi** [comment]
@PhillipPflaum Hi, I suggest to post your problem as a new issue or a question on tex.stackexchange.com (it's more responsive than here) with specific example and/or version info accompanied.
