### ISSUE TITLE
Minted uses `python` rather than `python3` (when available) for `autogobble`

### ISSUE THREAD

**Issue by yves-chevallier** [gpoore/minted#277]
I am aware this issue has plenty answers on `tex.stackexchange.com` [this](https://tex.stackexchange.com/q/516417/85416) or [this](https://tex.stackexchange.com/questions/494711/minted-error-missing-pygments-error) but they don't really address the problem with a simple reproducible example. 

So, I am using this simple example (in the file `toto.tex`) :

    \documentclass{article}
    \usepackage{fontspec}
    \usepackage{minted}
    \usepackage[most,minted]{tcolorbox}
    
    \begin{document}
    \usemintedstyle{bw}
    \begin{tcblisting}{listing only, listing options={language=c}}
    int main(int argc, char * argv[]) {
        printf("hello, world!\n");
    }
    \end{tcblisting}
    \end{document}

With this simple command: 

    docker run -it -v$(pwd):/home -w/home nowox/latex:2.0 xelatex -shell-escape toto.tex

And I get this error: 

    (./_minted-toto/default-pyg-prefix.pygstyle) (./_minted-toto/bw.pygstyle)sh: 1: python: not found
    system returned with code 32512
    Error: cannot read infile: [Errno 2] No such file or directory: './toto.pyg'
    system returned with code 256
    
    ! Package minted Error: Missing Pygments output; \inputminted was
    probably given a file that does not exist--otherwise, you may need 
    the outputdir package option, or may be using an incompatible build tool,
    or may be using frozencache with a missing file.

As I've read `minted` uses `pygmentize` behind the scenes, I checked its existence: 

    $ docker run -it -v$(pwd):/home -w/home nowox/latex:2.0 pygmentize --version | head -n3
    Usage: /usr/local/bin/pygmentize [-l <lexer> | -g] [-F <filter>[:<options>]] [-f <formatter>]
              [-O <options>] [-P <option=value>] [-s] [-v] [-x] [-o <outfile>] [<infile>]

However I don't have Python 2.7 installed, only Python 3 so `python` doesn't exist, only `python3`. But as read everywhere, minted doesn't care since it relies on `pygmentize`, not `python`. 

That said, if I create a symlink on my Docker with `ln -s /usr/bin/python3 /usr/bin/python`, then everything works... But it is a really bad workaround...

Is this a bug with `minted` ?

**Comment by muzimuzhi** [comment]
I have no experience using Docker, so basically the following are just guessing. Does the executable `pygmentize` work as expected, for example, when you call
```bash
pygmentize -S default -f latex
# and/or
pygmentize -l python -f latex -F tokenmerge <arbitrary python file>
```

**Comment by yves-chevallier** [comment]
Here the result : 

```
$ docker run -it -v$(pwd)/_build/latex:/home/latex -w/home/latex nowox/latex:2.0 pygmentize -S default -f latex | head -n10

\makeatletter
\def\PY@reset{\let\PY@it=\relax \let\PY@bf=\relax%
    \let\PY@ul=\relax \let\PY@tc=\relax%
    \let\PY@bc=\relax \let\PY@ff=\relax}
\def\PY@tok#1{\csname PY@tok@#1\endcsname}
\def\PY@toks#1+{\ifx\relax#1\empty\else%
    \PY@tok{#1}\expandafter\PY@toks\fi}
\def\PY@do#1{\PY@bc{\PY@tc{\PY@ul{%
    \PY@it{\PY@bf{\PY@ff{#1}}}}}}}
```

And 

```
$ docker run -it -v$(pwd)/_build/latex:/home/latex -w/home/latex nowox/latex:2.0 pygmentize -l python -f latex -F tokenmerge  /usr/lib/python3/dist-packages/setuptools/wheel.py | head -n10
\begin{Verbatim}[commandchars=\\\{\}]
\PY{l+s+sd}{\PYZdq{}\PYZdq{}\PYZdq{}Wheels support.\PYZdq{}\PYZdq{}\PYZdq{}}

\PY{k+kn}{from} \PY{n+nn}{distutils.util} \PY{k+kn}{import} \PY{n}{get\PYZus{}platform}
\PY{k+kn}{from} \PY{n+nn}{distutils} \PY{k+kn}{import} \PY{n}{log}
\PY{k+kn}{import} \PY{n+nn}{email}
\PY{k+kn}{import} \PY{n+nn}{itertools}
\PY{k+kn}{import} \PY{n+nn}{os}
\PY{k+kn}{import} \PY{n+nn}{posixpath}
\PY{k+kn}{import} \PY{n+nn}{re}
write /dev/stdout: broken pipe
```

**Comment by muzimuzhi** [comment]
Try this:
```tex
\documentclass{article}
\usepackage{fontspec}
\usepackage{minted}
\usepackage[most,minted]{tcolorbox}

\usepackage{xpatch}
\makeatletter
% replace executable python with python3
\xpatchcmd\minted@pygmentize
  {python -c}
  {python3 -c}
  {}{\fail}
\xpatchcmd\minted@autogobble
  {python -c}
  {python3 -c}
  {}{\fail}
\makeatother

\begin{document}
\usemintedstyle{bw}

\begin{tcblisting}{listing only, listing options={language=c}}
int main(int argc, char * argv[]) {
    printf("hello, world!\n");
}
\end{tcblisting}

\end{document}
```

`tcolorbox`'s `minted` library uses option `autogobble` by default, which runs a hardcoded `python` executable. This can be made into a new `minted` package option.

**Comment by yves-chevallier** [comment]
With this it works !

**Comment by muzimuzhi** [comment]
BTW, the right way to specify `minted` highlighting language in `tcblisting` environment is `\begin{tcblisting}{listing only, minted language=c}`. `listing options={language=c}` is not used in your example.

**Comment by muzimuzhi** [comment]
Here is a patch for `minted.sty` (sorry I didn't touch dtx), which adds a new package option `pyexecutable=<executable name>`. This option has initial value `python`.

```diff
diff --git a/source/minted.sty b/source/minted.sty
index 1ca7336..6d5b522 100644
--- a/source/minted.sty
+++ b/source/minted.sty
@@ -52,6 +52,10 @@
 \DeclareVoidOption{chapter}{\def\minted@float@within{chapter}}
 \DeclareVoidOption{section}{\def\minted@float@within{section}}
 \DeclareBoolOption{newfloat}
+\edef\minted@pyexecutable{\detokenize{python}}
+\define@key{minted}{pyexecutable}{%
+  \edef\minted@pyexecutable{\detokenize{#1}}%
+}
 \DeclareBoolOption[true]{cache}
 \StrSubstitute{\jobname}{ }{_}[\minted@jobname]
 \StrSubstitute{\minted@jobname}{*}{_}[\minted@jobname]
@@ -808,7 +812,7 @@
             %Cheating a little here by using ASCII codes to write `{` and `}`
             %in the Python code
             \def\minted@hashcmd{%
-              \detokenize{python -c "import hashlib; import os;
+              \minted@pyexecutable\detokenize{ -c "import hashlib; import os;
                 hasher = hashlib.sha1();
                 f = open(os.path.expanduser(os.path.expandvars(\"}\minted@tmpfname@esc.mintedcmd\detokenize{\")), \"rb\");
                 hasher.update(f.read());
@@ -878,7 +882,7 @@
         \detokenize{for /f "usebackq tokens=*" }\@percentchar\detokenize{a in (`kpsewhich} #1\detokenize{`) do}\space
       \fi
     \fi
-    \detokenize{python -c "import sys; import os;
+    \minted@pyexecutable\detokenize{ -c "import sys; import os;
     import textwrap;
     from io import open;
     fname = }%
```

A minimal example:
```tex
\documentclass{article}
% change python executable from "python" to "python3"
\usepackage[pyexecutable=python3]{minted}

\begin{document}
\begin{minted}[autogobble]{c}
  int main(int argc, char * argv[]) {
      printf("hello, world!\n");
  }
\end{minted}
\end{document}
```

It seems `minted` can auto switch to executable name `python3` if each of the following is true: i) non-restricted shell escape is on, ii) `autogobble` is used, and) `pyexecutable` has its default value but `python` is not callable (by using its internal macro `\TestAppExists`). A draft implementation can be found here https://github.com/gpoore/minted/compare/master...muzimuzhi:change-python-executable.

**Comment by krumeich** [comment]
@muzimuzhi That is an excellent solution! Thank you! 

Might I suggest that you create a pull request to make it as easy as possible for @gpoore to include this patch? An updated release would save me from having to add additional symlinks to my Docker image. Much appreciated.

**Comment by krumeich** [comment]
@gpoore Any chance of this patch being incorporated into the main branch and shipped in the next release? I'm kind of struggling with different versions of Python and this would be a very elegant solution to my problem. Thank you

**Comment by gpoore** [comment]
@krumeich There will be a fix for `python3` issues in the next release, whenever the next release happens. This patch isn't a general fix, because it doesn't handle the case of systems where `python` is still the correct executable.
