### ISSUE TITLE
Intelligent (context-sensitive) fontsize argument

### ISSUE THREAD

**Issue by FabianWolff** [gpoore/minted#279]
I am writing a document with custom fonts, and I've noticed that using `\mintinline` with the default font size doesn't look good; the code is too large relative to the surrounding text. No problem, thanks to `\mintinline`'s `fontsize` argument, I thought, but consider the following MWE, where the inline code will end up having the same font size in both regular text and the footnote:
```LaTeX
\documentclass{article}

\usepackage{minted}

\begin{document}
\newmintinline[textinline]{Text}{fontsize=\small}

\textinline{This works!}
\footnote{\textinline{This is too big!}
  (\textinline[fontsize=\footnotesize]{This is how it should be.})}
\end{document}
```
In other words, I would like `\mintinline` to use a custom font size for _regular_ text, but still respect special contexts, such as footnotes, and use the appropriate font size there.

Maybe there is a different/smarter way of achieving this, in which case I'd be happy to hear about it, but if not, perhaps you could consider implementing the behavior I've just described; I think it would be very helpful!

Thanks.

**Comment by FabianWolff** [comment]
> perhaps you'd prefer relsize package then use `\smaller` so it's always a bit smaller than the current text font.

Thanks for pointing this possibility out to me! Unfortunately it doesn't seem to work properly:
```LaTeX
\documentclass{article}

\usepackage{minted}
\usepackage{relsize}

\begin{document}
\newmintinline[textinline]{Text}{fontsize=\smaller}

\textinline[fontsize=\normalsize]{normal size}
\textinline[fontsize=\small]{small}
\textinline{smaller}

\footnote{\textinline[fontsize=\normalsize]{normal size}
  \textinline[fontsize=\footnotesize]{footnote size}
  \textinline{smaller}
}
\end{document}
```
In this example, the "smaller" text is always one step smaller than it is supposed to be, even though `\smaller`, from my understanding, reduces the font size by one step (e.g. `\normalsize` to `\small`). What am I doing wrong?


> If only those predefined font size commands `\normalsize`, `\footnotesize`, etc. are used to issue a font size changing, then the following `\IfFontSize` will work:
> [...]

This works really well, thanks, @muzimuzhi!

Would you consider adding something like this to the documentation? I can't be the only one with this question, and I think it would fit well e.g. into the "FAQ and Troubleshooting" section.

**Comment by muzimuzhi** [comment]
@FabianWolff 
1. There was some naming inconsistency in https://github.com/gpoore/minted/issues/279#issuecomment-678788776, now the new command is named `\IfFontSizeContextTF`.
1. `\IfFontSizeContextTF` fits more general use cases, and perhaps it can be provided by some package or latex2e kernel. I'm not sure.
