### ISSUE TITLE
[Feature request] New option "envname" for configuring verbatim env name

### ISSUE THREAD

**Issue by muzimuzhi** [gpoore/minted#281]
By default, `pygments` puts highlighted tex codes in `Verbatim` environment. This is configurable by CLI option `-P envname=<name>` (see related [doc of `pytments`](https://pygments.org/docs/formatters/#LatexFormatter)), and packages like `tcolorbox` seem to need this, see https://github.com/T-F-S/tcolorbox/issues/2#issuecomment-695112384.

The implementation could be as simple as
```ted
\minted@def@optcl{envname}{-P envname}{#1}
```

**Comment by muzimuzhi** [comment]
see also #215 and #133

**Comment by muzimuzhi** [comment]
Just find `minted` uses `\RecustomVerbatimEnvironment{Verbatim}{BVerbatim}{}%` to do the trick

https://github.com/gpoore/minted/blob/5d72859d714a6f2f6a42eec524476994d954b960/source/minted.dtx#L3152-L3157

(`\minted@inline@iii` if not in draft mode)
https://github.com/gpoore/minted/blob/5d72859d714a6f2f6a42eec524476994d954b960/source/minted.dtx#L3209-L3216

**Comment by gpoore** [comment]
The latest `minted` v3 beta now has an `envname` option and some backward compatibility fixes so that `tcolorbox` will work. This requires the dev version of `fvextra`; a new `fvextra` release will be out within the next few days.

**Comment by muzimuzhi** [comment]
Thanks. I've informed the of `tcolorbox` of this change, see https://github.com/T-F-S/tcolorbox/issues/2#issuecomment-2309539142.
