### ISSUE TITLE
YAML highlighting doesn't nest correctly

### ISSUE THREAD

**Issue by rybern** [gpoore/minted#282]
I have this snippet of YAML:
```
   model 5:
     Successes: Proportional
     P: AngleAndDistance
       PAngle: PAngle
       PDistance: PDistance
         DistanceModel: Parametric

```

Here's how it looks in Emacs:
![yaml-emacs](https://user-images.githubusercontent.com/4982341/95596672-b3b04300-0a1b-11eb-93b7-1da6c16af65d.png)

Here's how it looks in a pdf produced with latex and minted:
![minted-yaml](https://user-images.githubusercontent.com/4982341/95596512-7a77d300-0a1b-11eb-83e2-4ba37457a493.png)

Minted doesn't seem to highlight past the first two levels of nesting.

**Comment by gpoore** [comment]
minted uses [Pygments](https://pygments.org/) to do the highlighting. There's probably some sort of limitation in the Pygments YAML lexer.

**Comment by muzimuzhi** [comment]
> ```
>    model 5:
>      Successes: Proportional
>      P: AngleAndDistance
>        PAngle: PAngle
>        PDistance: PDistance
>          DistanceModel: Parametric
> ```

https://yaml-online-parser.appspot.com/ complains:
```
ERROR:

mapping values are not allowed here
  in "<unicode string>", line 4, column 14:
           PAngle: PAngle
                 ^
```

I think if the value of a key is a dict, then the key itself should not have any other values. Which structure of json do you expect from this yaml snippet?

**Comment by rybern** [comment]
Ah, of course. Sorry for my mistake, thank you for figuring it out!
