### ISSUE TITLE
Error occurs when using "%" in "mintinline" environment with Python language.

### ISSUE THREAD

**Issue by soih** [gpoore/minted#284]
When I use "%"  in a paper, as following:

```...The meaning of \colorbox[rgb]{0.92,0.92,0.92}{\mintinline{python}|% 10|} is ...```

The compiled result will break at the position of "%", which means the code after "%" is not compiled at all.

**Comment by muzimuzhi** [comment]
### Explanation

In `\colorbox[...]{...}{\mintinline{python}|% 10|}`, the `\mintinline` part is firstly treated, hence _tokenized_, as the second mandatory argument of `\colorbox`. When being tokenized, the `%` still has the category code of "comment", hence every thing at the same line and after that `%` is ignored, including the trailing `}`.

### Workaround

To set a background color for `\mintinline`, you can use `minted` option `bgcolor`.

```tex
\documentclass{article}
\usepackage{minted}
\usepackage{xcolor}

\definecolor{mintbg}{rgb}{0.92,0.92,0.92}

\begin{document}
\mintinline[bgcolor=mintbg]{python}|% 10|
\end{document}
```

If what you want is to (automatically) set every inline python code with gray background, use
```tex
% preamble
\setmintedinline[python]{bgcolor=mintbg}

% usage
\mintinline{python}|% 10|
```

**Comment by muzimuzhi** [comment]
@soih This can be closed.
