### ISSUE TITLE
Autogobble not working on Debian testing

### ISSUE THREAD

**Issue by seyaryuki** [gpoore/minted#286]
Hi,

The `autogobble` option doesn't work on my machine running Debian testing.
However, it works fine on another machine running Debian stable.

Here is a MWE on which my Debian testing machine compiles but without removing the extra spaces:

```
\documentclass{article}

\usepackage{minted}
\setminted{linenos,autogobble,frame=single}

\begin{document}

\begin{minted}{python}
  def foo(bar):
      return 0
\end{minted}

\end{document}
```

On both machines, the packages `texlive-full` and `python3-pygments` are installed.
Here are the differences:

Debian stable:
- Texlive version: `2018.20190227-2`
- minted version: `2.5` (installed with `texlive-full`)
- pygmentize -V: `2.3.1`

Debian testing:
- Texlive version: `2020.20201129-2`
- minted version: `2.5` (installed with `texlive-full`)
- pygmentize -V: `2.7.1`

I tried installing pygmentize version `2.3.1` via `pip install Pygments==2.3.1` or `pip3 install Pygments==2.3.1` but it didn't fix the problem.

Thank you for reading this!

**Comment by gpoore** [comment]
Does your Debian testing have a `python` executable? Or only `python3`?

**Comment by seyaryuki** [comment]
You're right, I had `python2` and `python3` but no `python`.

Running `ln -s /usr/bin/python3 /usr/bin/python` fixed it.

Thanks!

**Comment by gpoore** [comment]
Thanks for reporting this. I've created a new issue (#287) to fix this so that `python3` will work.
