### ISSUE TITLE
Switch autogobble to use python3 under Linux

### ISSUE THREAD

**Issue by gpoore** [gpoore/minted#287]
See #286.

**Comment by muzimuzhi** [comment]
See also #277, in which I [provided a patch](https://github.com/gpoore/minted/issues/277#issuecomment-670493218) to add package option `pyexecutable=<python executable>`. Of course the current issue might want to apply some auto detection.

**Comment by MakisH** [comment]
> Since Python 2 has reached the end of its life cycle, newer releases of Debain / Ubuntu will not have an executable named `python`. The temporary solution is:
> 
> ```shell
> sudo ln -sf /usr/bin/python3 /usr/bin/python
> ```

Instead of manually adding this link, you can also install the `python-is-python3` package:

```
sudo apt install python-is-python3
```
