### ISSUE TITLE
Double Hashtag in Beamer Overlays

### ISSUE THREAD

**Issue by FranzAtGithub** [gpoore/minted#288]
Hello,

I hope this has not been reported already.

When `\mintedinline` is used inside of a beamer overlay (not the first on frame) any hashtag (`#`) in the displayed code is duplicated.

I created a MWE in this GitLab repository: https://gitlab.com/FranzAtGitLab/double-hastags-in-beamer-overlays-with-minted
The produced PDF and the log file can be found here: https://gitlab.com/FranzAtGitLab/double-hastags-in-beamer-overlays-with-minted/-/jobs/941176692/artifacts/browse

**Comment by muzimuzhi** [comment]
This is a documented limitation, see package manual for `minted` v2.5, the first footnote on page 8

> <sup>1</sup> For example, `\mintinline` works in footnotes! The main exception is when the code contains
the percent `%` or hash `#` characters, or unmatched curly braces.

**Comment by FranzAtGithub** [comment]
Oh ... I am really sorry for not reading the manual properly.

You mention the current version explicitly, so it is planned to remove this limitation in future releases?

**Comment by muzimuzhi** [comment]
I think a workaround like the `\EscVerb` or `\SaveVerb` followed by `\UseVerb` in `fvextra` package is possible. I will try in a few days.

Meanwhile, I'm not the maintainer so ...

**Comment by gpoore** [comment]
There isn't a way to get `\mintinline` to work with `#` or `%` or unpaired curly braces inside a command like `\footnote` due to the way that LaTeX processes commands. The typical workaround would be `\savebox`. For example,
```latex
\newsavebox\mybox
\begin{lrbox}{\mybox}
\mintinline{cpp}{std::cout}
\end{lrbox}

\section{Text \usebox{\mybox}}
```
It should also be possible to create a `\escmintinline` or similar command in which characters like `#` and `%` can always be used as long as they are escaped by a backslash. `\EscVerb` from `fvextra` could be the basis for creating such a command, which is what @muzimuzhi was probably suggesting. I've created a number of features in `fvextra` that can reduce limitations on `\mintinline` and allow new variations like an `\escmintinline` that can work around the remaining limitations...unfortunately the pandemic and other events have prevented me from doing any LaTeX programming for a while.

**Comment by muzimuzhi** [comment]
I didn't fully understand the implementations of `\EscVerb` and its internals, but welcome to test the following code, which defines `\EscMintedinline`.

```tex
\documentclass{article}
\usepackage{minted}

\makeatletter
%
% Similar to \EscVerb.
%
% \EscMintinline[options]{<language>}{<backslash-escaped text>}
%
\def\EscMintinline{%
  \FVExtraRobustCommand
  \RobustEscMintinline
  \FVExtraUnexpandedReadOArgMArgEscVArg}

\NewExpandableDocumentCommand \FVExtraUnexpandedReadOArgMArgEscVArg { o m m } {%
  \IfNoValueTF{#1}
    {\FVExtraAlwaysUnexpanded
      {\FVExtraUnexpandedReadOArgMArgEscVArg{#2}{#3}}}
    {\FVExtraAlwaysUnexpanded
      {\FVExtraUnexpandedReadOArgMArgEscVArg[#1]{#2}{#3}}}%
}

\newrobustcmd\RobustEscMintinline[2][]{%
  % similar to \mintinline
  \begingroup
  \setboolean{minted@isinline}{true}%
  \minted@configlang{#2}%
  \setkeys{minted@opt@cmd}{#1}%
  \minted@fvset
  \begingroup
  \@ifnextchar\bgroup
    {\FVExtraDetokenizeREscVArg{\minted@inline@iii}}%
    {\PackageError{minted}%
     {\string\EscMintinline\space delimiters must be paired curly braces in this context}%
     {Delimit argument with curly braces}}}
\makeatother

\begin{document}
% normal
\mintinline[bgcolor=gray!20]{python}{a = 10 % 3 # comment}
\mintinline{python}{a = 10 % 3 # comment}

% outside argument
\EscMintinline{python}{a = 10 \% 3 \# comment}
\EscMintinline[bgcolor=gray!20]{python}{a = 10 \% 3 \# comment}

% inside argument
\fbox{\EscMintinline{python}{a = 10 \% 3 \# comment}}
\fbox{\EscMintinline[bgcolor=gray!20]{python}{a = 10 \% 3 \# comment}}

% inside \edef
\edef\xxx{\EscMintinline{python}{a = 10 \% 3 \# comment}}
\fbox{\xxx}
\edef\yyy{\EscMintinline[bgcolor=gray!20]{python}{a = 10 \% 3 \# comment}}
\fbox{\yyy}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/103950326-a5d3a080-5177-11eb-8883-e496b9a97dc0.png)

**Comment by muzimuzhi** [comment]
`minted` v1.5 reimplemented `\mintinline`.  Here's a new, adapted `\EscMintInline` that _happens to work_.  This time I  understand nothing about both why I defined `\EscMintInline` that way and how the new `\mintineline` is working.
```tex
\documentclass{article}
\usepackage[draft=false]{minted}

\makeatletter
%
% Similar to \EscVerb.
%
% \EscMintinline[options]{<language>}{<backslash-escaped text>}
%
\def\EscMintInline{%
  \FVExtraRobustCommand
  \RobustEscMintInline
  \FVExtraUnexpandedReadOArgMArgEscVArg}

\NewExpandableDocumentCommand \FVExtraUnexpandedReadOArgMArgEscVArg { o m m } {%
  \IfNoValueTF{#1}
    {\FVExtraAlwaysUnexpanded
      {\FVExtraUnexpandedReadOArgMArgEscVArg{#2}{#3}}}
    {\FVExtraAlwaysUnexpanded
      {\FVExtraUnexpandedReadOArgMArgEscVArg[#1]{#2}{#3}}}%
}

% similar to \RobustMintInline
\newrobustcmd{\RobustEscMintInline}[2][]{%
  \ifbool{FVExtraRobustCommandExpanded}%
   {\@ifnextchar\bgroup
     {\FVExtraDetokenizeREscVArg{\RobustMintInlineProcess{#1}{#2}}}%
     {\PackageError{minted}%
       {Inline delimiters must be paired curly braces in this context}%
       {Use curly braces as delimiters}}}%
   {\FVExtraDetokenizeREscVArg{\RobustMintInlineProcess{#1}{#2}}}}
\makeatother

\begin{document}
% normal
\mintinline[bgcolor=gray!20]{python}{a = 10 % 3 # comment}
\mintinline{python}{a = 10 % 3 # comment}

% outside argument
\EscMintInline{python}{a = 10 \% 3 \# comment}
\EscMintInline[bgcolor=gray!20]{python}{a = 10 \% 3 \# comment}

% inside argument
\fbox{\EscMintInline{python}{a = 10 \% 3 \# comment}}
\fbox{\EscMintInline[bgcolor=gray!20]{python}{a = 10 \% 3 \# comment}}

% inside \edef
\edef\xxx{\EscMintInline{python}{a = 10 \% 3 \# comment}}
\fbox{\xxx}
\edef\yyy{\EscMintInline[bgcolor=gray!20]{python}{a = 10 \% 3 \# comment}}
\fbox{\yyy}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/230859068-15fce74a-557b-48ad-a740-05dc88656972.png)
