### ISSUE TITLE
Minted incorrectly modifies reStructuredText titles in its output

### ISSUE THREAD

**Issue by SeSodesa** [gpoore/minted#289]
I am attempting to use minted to display reStructuredText source documents, and it does an admirable job most of the time. However, when it comes to titles underlined with hyphens (`-`), the characters used to underline titles of over certain length are cropped, as seen in the below images, the first of which is the original source and the second is the output presented by Minted:

![minted-rest-title-input](https://user-images.githubusercontent.com/19917000/104167377-e3009280-5404-11eb-96b8-4778a71b2626.png)
![minted-rest-title-output](https://user-images.githubusercontent.com/19917000/104167368-ded47500-5404-11eb-82ad-546380a8caba.png)

This should not happen, as the output presented by Minted in the case of reST titles is not valid reStructuredText. The underlining of reST titles needs to be exactly as long as the title text.

**Comment by muzimuzhi** [comment]
Sounds like a `pygments` problem. Which language do you choose in `\begin{minted}{<language>}`? It would help others to help you if you could provide a complete copyable tex example.

Also, https://pygments.org/demo/ can be used to test the `pygments` output.

**Comment by SeSodesa** [comment]
@muzimuzhi
The language used to import the file was `rst`. I assume it is the correct one for reStructiredText, as most everything is higjlighted correctly. The inky weird things are the cropped underlines of titles, when using hyphens to underline them.

**Comment by muzimuzhi** [comment]
The simple minted example below works ok. Perhaps it is the specific fonts used that enables ligature (changing two consecutive hyphen dashes to an em-dash). Can you provide an example that do reproduces the problem?
```tex
\documentclass{article}
\usepackage{minted}

\begin{document}
\begin{minted}{rst}
Title here. I am quite long...
------------------------------
\end{minted}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/104218317-87bbb800-5477-11eb-8be2-063f5726758f.png)

**Comment by gpoore** [comment]
This works correctly with current `minted` and Pygments, so I'm closing the issue. It was likely font-related.
