### ISSUE TITLE
pipenv support

### ISSUE THREAD

**Issue by lewiswolf** [gpoore/minted#290]
Is there any support for pipenv, so that pygments can be installed only in the project folder?

**Comment by lewiswolf** [comment]
Thanks for your quick respone, but I'm afraid I'm still having trouble. In my tex file I have:

```latex
\renewcommand{\MintedPygmentize}{pipenv run pygmentize}
```

and the error I'm getting is `Package minted: You must have 'pygmentize' installed to use this package.`

**Comment by gpoore** [comment]
Are you running LaTeX with the environment activated? If that doesn't work, it's possible that `\MintedPygmentize` would need to both activate the environment and run pygmentize. I don't know what all LaTeX's shell escape, which is used to invoke pygmentize, inherits.

**Comment by lewiswolf** [comment]
This was exactly what I needed to hear. For any future reference, to use pipenv to compile pygments/minted, run your latex commands with `pipenv run pdflatex` and you don't need to redefine `\MintedPygmentize`.

Thanks so much for your help!
