### ISSUE TITLE
PHP syntax highlighting breaks with escapeinside and without startinline

### ISSUE THREAD

**Issue by jacopo-j** [gpoore/minted#291]
Hello,

consider the following code snippet:

```
\begin{minted}[linenos, escapeinside=!!]{php}
<?php
$myvariable = 42;
$anothervariable = 'Lorem ipsum';
?>
\end{minted}
```

This is the expected result:

<img width="671" alt="Schermata 2021-02-08 alle 21 23 23" src="https://user-images.githubusercontent.com/9914547/107277032-2a099400-6a54-11eb-99bc-c814a2875342.png">

This is the actual result:

<img width="678" alt="Schermata 2021-02-08 alle 21 22 51" src="https://user-images.githubusercontent.com/9914547/107277049-34c42900-6a54-11eb-9c9e-cc9c32cd132e.png">

Further details I discovered while experimenting:

* Adding the `startinline` options solves the problem. However that shouldn't be required since the code is wrapped in PHP tags
* Removing the `escapeinside` option also solves the problem
* Using different characters for the `escapeinside` option doesn't make any difference
* Using `mathescape` instead of `escapeinside` also solves the problem

**Comment by muzimuzhi** [comment]
I cannot reproduce your problem with the following minimal full example, complied with any one of pdf-, xe-, and lua-latex:
```tex
\documentclass{article}
\usepackage{minted}

\begin{document}
\begin{minted}[linenos, escapeinside=!!]{php}
<?php
$myvariable = 42;
$anothervariable = 'Lorem ipsum';
?>
\end{minted}
\end{document}
```

So a full example which can reproduce the problem is required.

**Comment by jacopo-j** [comment]
I could reproduce the problem with your example. I did some more testing and it looks like the problem was with my specific version of Pygments. Using the latest release, minted works as expected. Sorry about that.
