### ISSUE TITLE
global tab size

### ISSUE THREAD

**Issue by lewiswolf** [gpoore/minted#292]
Hi,

I'm trying to redefine the default tab size for all languages. I tried ```\setminted{tabsize=2}``` but it didn't change anything. 

I also tried a language specific approach

```
\newminted{cpp}{tabsize=2}

\begin{cppcode*}
    ...
\end{cppcode*}
```

but still nothing.

Thanks,
Lewis

**Comment by muzimuzhi** [comment]
I didn't test, but maybe you can try `obeytabs=true, tabsize=<num>`.

**Comment by lewiswolf** [comment]
Still nothing... I tried with both methods shown above.

**Comment by muzimuzhi** [comment]
Could you provide a complete example? I tested locally and it seems to work.

**Comment by lewiswolf** [comment]
I'm using [this template](https://github.com/lewiswolf/personal-latex-template), and I've tried adding the above lines to all three .tex files. 

So for example, template.tex includes the line ```\setminted{tabsize=2}```

And then in document.tex I've added something along the lines of:

```
\begin{minted}{cpp}
class OnePole {
    public:
        float calculateOrder(float x, float a_0) {
            // calculate y
            float y = (b_0 * x + b_1 * previousX - previousY) * a_0 + previousY;
            // set previous values and return y
            previousX = x;
            previousY = y;
            return y;
        }
    private:
        // constants
        float b_0 = 1 / 1.3;
        float b_1 = 0.3 / 1.3;
        // previous values
        float previousX = 0.0;
        float previousY = 0.0;
};
\end{minted}
```
where each line indent is a tab, but it does not format correctly.

When I use ```\begin{minted}[tabsize=2]{cpp}```, it works just fine. I just want to save myself writing it every time.

**Comment by muzimuzhi** [comment]
Perhaps the tabs in your code are replaced with spaces automatically, by your editors.

**Comment by lewiswolf** [comment]
🙏🙏🙏 thanks so much! The problem is never where you think...
