### ISSUE TITLE
MatLab string highlight error

### ISSUE THREAD

**Issue by CameraEngineer** [gpoore/minted#293]
I would like to use MatLab code in a document to highlight and I noticed an issue when it references a string.  If the string is between apostrophes, it appears to be correctly highlighted.  However, if a string is in between quotation marks, minted doesn't recognize that the command is a string.  If you simply change to the language "octave" this error is resolved.  

Using Matlab language we see the error on line 10 in the string definition:
![image](https://user-images.githubusercontent.com/65438903/109214117-aa2b3b80-776e-11eb-9dfb-d71905001509.png)

Using Octave language:
![image](https://user-images.githubusercontent.com/65438903/109214472-1c038500-776f-11eb-924b-11a689400954.png)

Thanks!

**Comment by muzimuzhi** [comment]
This is mostly a pygments issue, and it doesn't reproduce here with Pygments v2.8.0.

**Comment by CameraEngineer** [comment]
Thanks so much.  I just updated pygments from 2.6.1 to 2.8 and the error is
now gone.

**Comment by muzimuzhi** [comment]
According to the related [changelog of pygments](https://github.com/pygments/pygments/blob/ad55974ce83b85dbb333ab57764415ab84169461/CHANGES#L311), this _is_ a pygments problem and has been fixed (in https://github.com/pygments/pygments/pull/1278) since v2.5.2.

_Edit:_ Or should have been?

```
Version 2.5.2
-------------
(released November 29, 2019)

[...]
- Recognize double-quoted strings in Matlab (PR#1278)
[...]
```
