### ISSUE TITLE
Build failure with Pygments 2.8.0 due to it stylesheet being loaded with character `-` having catcode letter

### ISSUE THREAD

**Issue by jfbu** [gpoore/minted#294]
Perhaps the relevant code lines are
https://github.com/gpoore/minted/blob/5d72859d714a6f2f6a42eec524476994d954b960/source/minted.dtx#L2448-L2458

If the reason is that the `-` character is used in some control sequence name internal to minted, it can always be used inside  `\@nameuse` with its normal catcode 12.

As Pygments 2.8.0 stylesheet for LaTeX contains a length assignment which uses `-`, it breaks due to the wrong catcode setting.

MWE: the one of first linked issued below.

Related:

https://github.com/pygments/pygments/issues/1734

https://github.com/pygments/pygments/issues/1731

**Comment by gpoore** [comment]
minted needs to have multiple copies of the stylesheet, one for each style that is used in a document. Currently, these use macro names of the form `\PYG<style_name>`. The catcode changes were introduced to make this continue to work with Pygments styles with names like `paraiso-light`, `paraiso-dark`, and `algol_nu` (https://github.com/gpoore/minted/issues/111). The solution will be to introduce a sanitization step, so that macro names will be `\PYG<sanitized_style_name>`, where `<sanitized_style_name>` has all `-` and `_` stripped out or otherwise replaced. And then minted will need to run all user style settings through the sanitization to find the correct macros.

I'm in the midst of trying to release updated versions of all my LaTeX packages, so I'll try to release a new version sometime soon.

**Comment by jfbu** [comment]
my two cents, but I don't know the code base: with `\csname...\endcsname` encapsulation (`\@namedef`, `\@nameuse`), and if those macros where (if I understand correctly), you store the stylesheet contents, are purely of internal usage, there may be a simpler way than assigning locally catcode letter to the hyphen char. Then you would not need to strip out the `-` and `_`. The `_` can be used in `\csname...\endcsname` directly as long as it has its normal catcode (8: math subscript)

**Comment by jfbu** [comment]
oh sorry, I understand now from #111 that it seems you do this so that Pygments can use a command prefix using `-`  or `_` !!!

Yes, stripping out from the style names things such as `-` and `_`  is way to go. And imagine some style name one day uses a digit.

Pygments should perhaps document that the command prefix must be as is allowed in LaTeX at user level. I can not see a bug of Pygments here, only a feature which perhaps should be documented.

To fix this on Pygments side, they would not only have to modify their stylesheet to use only `\@namedef` (2.8.0 uses it partially to shorten the definition lines in the stylesheet) but also in output for example for the various macros doing character escapes to be using `\nameuse` (`\let` to be same as `\@nameuse`). This would give very bulky mark-up only to allow the Pygments user-specified command prefix to contain characters usually not allowed in TeX macro names.

**Comment by jfbu** [comment]
To honour @davidcarlisle, you could perhaps use `ZZZ` as replacement for `-` and `ZZZZ` for `_` etc...

**Comment by gpoore** [comment]
Yes, it was a simple way to use a command prefix that covers all current style names. I agree that trying to work around this on the Pygments side would make the LaTeX unnecessarily complicated.

**Comment by muzimuzhi** [comment]
A random attempt, trying restricting catcode changes for hyphen and underscore in an extra level of group.  (I admit I don't know the code base well either.)

Code
https://github.com/gpoore/minted/compare/master...muzimuzhi:hyphen-and-underscore-in-pygsty

Test file
```tex
\documentclass{article}
\usepackage{minted}

\begin{document}

% test \setlength{\fboxsep}{-\fboxrule} in pygsty
% from https://github.com/pygments/pygments/issues/1734#issue-822934408
\begin{minted}{http}
abc
\end{minted}

% test hyphen in style name
% from https://github.com/gpoore/minted/issues/111#issuecomment-219458960
\begin{minted}[style=paraiso-dark]{yaml}
abc-xyz: -22
\end{minted}

% test understore in style name
\begin{minted}[style=algol_nu]{yaml}
abc-xyz: -22
\end{minted}
\end{document}
```

**Comment by jfbu** [comment]
@muzimuzhi I can not really comment as I am not familiar enough with minted codebase. I realized too late minted.pdf had some relevant code comments which if I had read them yesterday would have helped me better understand the minted context.

Pygments will make a hotfix release which simply prefixes `-` with `\string` in the `\setlength` assignment for border highlight (they have to be careful to use `\string<space>-` else the "`-` is a letter" bites back.

https://github.com/pygments/pygments/pull/1737

So there is no urgency here. My feeling is that it is definitely better to not query Pygments for a stylesheet constructed with  a LaTeX command prefix which contains not normally accepted characters in TeX macros.
