### ISSUE TITLE
With appendix, listings have an additional point in their label

### ISSUE THREAD

**Issue by akorb** [gpoore/minted#295]
It seems to result from an interdepedency among packets. I hope this is the right one.

In my document, the caption of all tables, figures and listings should have the structure:
Table 1: My table
Figure 1: My figure
Listing 1: My listing

But as soon as I add the `newfloat` option to the minted package, there is suddenly an additional period behind the continous number of listings:
Listing 1.: My listing
Listing 2.: Another listing

I could shrink it down to a minimal working example:

```latex
\documentclass{scrartcl}

\usepackage[newfloat]{minted}

\begin{document}

\begin{listing}
\begin{minted}{text}
Some code
\end{minted}
\caption{Code sample}
\end{listing}

\appendix

\section{First appendix}

\end{document}
```

This problem does not appear, if:
- using `article` instead of `scrartcl`
- removing the `section` from the `appendix`

I am completely stumped here and am glad about each idea.

Thanks!

**Comment by gpoore** [comment]
It looks like there is a conflict between `newfloat` and `scrartcl` (or something else in KOMA-Script). One option would be to create a new environment for code, using something like KOMA-Script's `tocbasic` package with command `\DeclareNewTOC[<options>]{<extension>}`. I don't have any experience with this, though.

**Comment by akorb** [comment]
Unfortunately, me neither. But it turned out that when I'm using the scrreprt as the document class, at least it is consistent:
 `1.2.: Figure 1`
 `1.2.: Table 1`

That's good enough for me. Thanks!
