### ISSUE TITLE
Using framesep without frame

### ISSUE THREAD

**Issue by akorb** [gpoore/minted#296]
I'd like to have some padding in front and behind my code. But within the box and thus increasing the area of the background color. I can achieve this with using `framesep` and for example `frame=single`. But I don't want a frame line.

My goal would be achieved if this would work:

```latex
\begin{listing}[H]

\begin{minted}
[frame=none,
framesep=20mm,
bgcolor=LightGray]{python}

mycode

\end{minted}

\end{listing}
```

Unfortunately, `framesep` doesn't have an effect if `frame=none`. Is there a way to force the `framesep` with an invisible frame line?

**Comment by gpoore** [comment]
You could try `framerule=0pt` to give it zero width or `rulecolor=LightGray` to make it blend with `bgcolor`.

**Comment by akorb** [comment]
I can't believe I didn't think of it myself. So simple and elegant.
Works perfectly. Thank you so much!

With using `frame=single` vs. `frame=lines` I can even decide where the padding is. Only top and bottom or also left and right.
