### ISSUE TITLE
TeXstudio seems not finding pygmentize on linux

### ISSUE THREAD

**Issue by clonyjr** [gpoore/minted#300]
On linux when trying to build a thesis project (with sub), in TeXstudio throws the following error:

``Package minted Error: You must have 'pygmentize' installed to use this package. \begin{document}``

Pygmentize is installed. I've got this when typing pygmentize --version on command line:
```
for formatter <formatter>. The argument given by -a is formatter
dependent.

The -L option lists lexers, formatters, styles or filters -- set
which to the thing you want to list (e.g. "styles"), or omit it to
list everything.

The -N option guesses and prints out a lexer name based solely on
the given filename. It does not take input or highlight anything.
If no specific lexer can be determined "text" is returned.

The -H option prints detailed help for the object <name> of type <type>,
where <type> is one of "lexer", "formatter" or "filter".

The -s option processes lines one at a time until EOF, rather than
waiting to process the entire file.  This only works for stdin, and
is intended for streaming input such as you get from 'tail -f'.
Example usage: "tail -f sql.log | pygmentize -s -l sql"

The -v option prints a detailed traceback on unhandled exceptions,
which is useful for debugging and bug reports.

The -h option prints this help.
The -V option prints the package version.
```

Does anyone know how to solve this? 

Thanks in advance

**Comment by davidcarlisle** [comment]
check it is in the path as used by the editor, the usual reason for failure
there is that you set the PATH in  a shell used on your command line but
start the editor from the desktop that doesn't have your personal
environment settings.

**Comment by clonyjr** [comment]
Thanks for your attention. 

Pygmentize is at:
``/usr/bin/pygmentize`` 
and my $PATH is:
``/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin``

I think it is ok, isn't it?

**Comment by CsatiZoltan** [comment]
@clonyjr I had the same problem today. Add `/usr/bin/` to the *Commands ($PATH)* field, found on the *Build* tab in the TeXstudio settings.
