### ISSUE TITLE
[MATLAB] Wrong comment performance after for ... end

### ISSUE THREAD

**Issue by syvshc** [gpoore/minted#301]
Here is the code 
```latex
\documentclass{article}
\usepackage{minted}
\begin{document}
    \begin{minted}{matlab}
        for i = 1:5
            N = 2.^i * 100;
        end
        % a comment
        % another comment
    \end{minted}
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/116366776-3aeaca00-a839-11eb-8bbe-31e5fef41f6b.png)
We can see that two comments perform differently. Is it a feature or a bug?

**Comment by muzimuzhi** [comment]
Works OK with [`pygments`](https://pygments.org/) v2.8.1. Which version of `pygments` (run `pygmentize -V`) do you use?

**Comment by syvshc** [comment]
Well, I'm away from my computer these days，I'll check it after I get my computer :)



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 28, 2021 19:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gpoore/minted] [MATLAB] Wrong comment performance after for ... end (#301)




 
Works OK with pygments v2.8.1. Which version of pygments (run pygmentize -V) do you use?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---Original---
From: ***@***.***&gt;
Date: Wed, Apr 28, 2021 19:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gpoore/minted] [MATLAB] Wrong comment performance after for ... end (#301)




 
Works OK with pygments v2.8.1. Which version of pygments (run pygmentize -V) do you use?

**Comment by syvshc** [comment]
> Works OK with [`pygments`](https://pygments.org/) v2.8.1. Which version of `pygments` (run `pygmentize -V`) do you use?

After  updating `pygments`  to `2.8.1`. the problem is solved.
