### ISSUE TITLE
change font style for strings and comments from italics to slanted

### ISSUE THREAD

**Issue by kberry** [gpoore/minted#306]
I want to use \sl rather than \it for strings and comments, for latex, xml, python. How? I couldn't find anything in the minted doc, on the pygments web site, or on the web. In fact I don't see any examples for changing the style of any kind of token or class of syntax, beyond the global options like fontsize, just statements that "anything can be customized". I don't doubt it, but how? Thanks.

**Comment by kberry** [comment]
This is with \usemintedstyle{bw}, hence the string constants being in italics. Sorry, I didn't realize that was relevant orignally. (It alsoseems like a strange choice to me, but that's another issue.)

BTW, the minted doc links to pygments.com/demo to define new styles, but as far as I can tell, the demo doesn't explain anything ... any additional specifics or pointers would be helpful. Thanks.

**Comment by gpoore** [comment]
All styling is hard-coded in the Pygments style definitions. If you want to customize things, you can do something like `\AtBeginEnvironment{minted}{\let\textit\textsl}`.

**Comment by kberry** [comment]
How about a pointer in the doc to how to do anything with the "Pygments style definitions"? I had no luck on the pyg web site. I'm sure it's just me, but ...

Anyway, thanks much for the \AtBeginEnvironment. That will get the job done.
