### ISSUE TITLE
italics in comments -> pound sign in output instead of dollar sign

### ISSUE THREAD

**Issue by kberry** [gpoore/minted#307]
Input:
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{latex}
% $10 off.
\end{minted}

output ihas a pound sign instead of a dollar sign (because that's what Knuth did in his italic fonts, unfortunately).

Typewriiter italic considered harmful ...

**Comment by gpoore** [comment]
`\usepackage[T1]{fontenc}`

**Comment by kberry** [comment]
Indeed. Thanks.
