### ISSUE TITLE
Custom style not applied to some tokens using the `BashSessionLexer`

### ISSUE THREAD

**Issue by JensDll** [gpoore/minted#308]
Hi, I'm trying to use minted to highlight some console output in my latex document.
I'm using the `BashSessionLexer` (alias `console`) together with a custom style:
```py
from pygments.style import Style
from pygments.token import Text, Generic

class CustomShellStyle(Style):
    styles = {
        Text: "#ff0000", #red
        Generic.Output: "#ff0000", #red
        Generic.Prompt: "#0000ff" #blue
    }
```
When I compile the following file using `latexmk -pdf -shell-escape index.tex`

`index.tex`
```tex
\documentclass{article}

\usepackage[cache=false]{minted}
\usemintedstyle[console]{customshell}

\begin{document}
\begin{minted}{console}
$ text
output
\end{minted}
\end{document}
```
this is the output:
![with_style](https://user-images.githubusercontent.com/56021306/129248073-e36bf862-c566-4aeb-9ae7-4ac23fa842a0.png)

### The Problem
No matter what styles are applied, nothing seems to be affecting the text coming after the `$` symbol. I would expect
the text to be Red also.

### Confirming the Pygments Tokens
Looking at the tokens generated by the `BashSessionLexer`

`testing.py`
```py
from pygments.lexers import get_lexer_by_name

lexer = get_lexer_by_name("console")

for tokens in lexer.get_tokens("$ text"):
    print(tokens)
for tokens in lexer.get_tokens("output"):
    print(tokens)
```
we can see that the text gets correctly recognized as `Token.Text`:
```py
>>> python testing.py
(Token.Generic.Prompt, '$ ')
(Token.Text, 'text')
(Token.Text, '\n')
(Token.Generic.Output, 'output\n')
```
For comparison here is the same document compiled without any style applied:
![without_style](https://user-images.githubusercontent.com/56021306/129248093-19bc57bf-919a-44cd-9815-a7c2a8a9265b.png)
I'm on Windows using MiKTeX 21.8

**Comment by gpoore** [comment]
Have you tried using your custom style to generate HTML? This might be a way to determine if there is an issue in the LaTeX generation or if the issue is somehow related to the custom style itself. I can probably only help if the issue is LaTeX-specific.

**Comment by JensDll** [comment]
Looking good for HTML

`input.txt`
```
$ text
output
```

```bash
$ pygmentize -f html -O full,style=customshell -l console -o out.html input.txt
```

`out.html`
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<!--
generated by Pygments <https://pygments.org/>
Copyright 2006-2021 by the Pygments team.
Licensed under the BSD license, see LICENSE for details.
-->
<html>
<head>
  <title></title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <style type="text/css">
/*
generated by Pygments <https://pygments.org/>
Copyright 2006-2021 by the Pygments team.
Licensed under the BSD license, see LICENSE for details.
*/
pre { line-height: 125%; }
td.linenos .normal { color: inherit; background-color: transparent; padding-left: 5px; padding-right: 5px; }
span.linenos { color: inherit; background-color: transparent; padding-left: 5px; padding-right: 5px; }
td.linenos .special { color: #000000; background-color: #ffffc0; padding-left: 5px; padding-right: 5px; }
span.linenos.special { color: #000000; background-color: #ffffc0; padding-left: 5px; padding-right: 5px; }
body .hll { background-color: #ffffcc }
body { background: #ffffff; color: #ff0000 }
body .go { color: #ff0000 } /* Generic.Output */
body .gp { color: #0000ff } /* Generic.Prompt */
body .w { color: #ff0000 } /* Text.Whitespace */

  </style>
</head>
<body>
<h2></h2>

<div class="highlight"><pre><span></span><span class="gp">$ </span>text
<span class="go">output</span>
</pre></div>
</body>
</html>
```

**Comment by gpoore** [comment]
It looks like this is an issue in Pygments: https://github.com/pygments/pygments/issues/604.

You can probably use something like the code below in your preamble to work around it. If you are using multiple languages with `minted`, things will be more difficult, though, since this would apply to everything from `minted`.
```latex
\AtBeginEnvironment{minted}{\color{red}}
```

**Comment by JensDll** [comment]
Alright I am using multiple languages but the following does seem to work (at least for colours):
```tex
\newminted{console}{
  style=customshell
}
\AtBeginEnvironment{consolecode}{\color{red}}
```
My original goal was to make everything in the console prompt bold and the rest normal font but doing the following will make the whole output bold:
```tex
\AtBeginEnvironment{consolecode}{\bf}
```
And something like
```py
class CustomShellStyle(Style):
    styles = {
        Comment: "nobold italic #000000",
        Generic.Prompt: "nobold #000000",
        Generic.Output: "nobold #000000",
    }
```
has no effect.

I guess I can settle on using different colours as it also looks good.
