### ISSUE TITLE
Linebreaks for a single \mintinline

### ISSUE THREAD

**Issue by tsdh** [gpoore/minted#31]
Is there a way to have a \mintinline|...| that wraps around?  I don't really care if it's automatic linebreaks, or if I specify manually where to add a linebreak.

I've read the item **I want automatic line breaks for long lines** in the documentation, but if I put the first hack given there into my preamble, minted environments are ok but every \mintinline|code here| is rendered so that it's is followed by a newline.  (I didn't try the second hack as I don't have linenos installed).

Aside from that, I don't need nor want global auto-linebreaks.  What I'd like to have is just something like

```` tex
\mintinlineautowrap|foo(bar, baz, quux, bla, x, y, z)|
````

which would automatically wrap around if the line is too short, or

```` tex
\mintinlinemanualwrap|foo(bar, baz,\\quux, bla, x, y, z)|
````

which would be printed with "foo(bar, baz," on one line, and "quux, bla, x, y, z)" on the next.

**Comment by gpoore** [comment]
The `breaklines` option now works for `\mintinline`.

**Comment by gembez** [comment]
@gpoore how can I define the option?

**Comment by gpoore** [comment]
@gembez For all inline content: `\setmintedinline{breaklines}`.  For individual commands: `\mintinline[breaklines]{<lang>}{<code>}`.

**Comment by gembez** [comment]
```The following dependencies are used by every application: \mintinline[breaklines]{xml}{spring-boot-starter-web} and \mintinline[breaklines]{xml}{spring-boot-starter-test}.```

![image](https://user-images.githubusercontent.com/25324059/28316762-648ea724-6bc4-11e7-9f43-1eadb81c9fde.png)

doesn't seem to work for me. I get a ```Overfull \hbox (40.09329pt too wide) in paragraph```warning. 

Best & thanks!

**Comment by gpoore** [comment]
@gembez The default `breaklines` only inserts breaks at spaces. If you don't have spaces, you need to use `breakanywhere`, or specify particular characters to break before/after with `breakbefore` and `breakafter`. Details are in the documentation.

**Comment by benkuly** [comment]
I've the same problem as @gembez 
His "\mintinline[breaklines]{xml}{spring-boot-starter-test}" should be in a new line as well as a pure string "spring-boot-starter-test" is.

**Comment by gpoore** [comment]
@benkuly I was forgetting that all of the special `breaklines` options like `breakbefore` and `breakafter` and `breakanywhere` don't work with `\mintinline`. Here's a patch you can add to your preamble that should get it working. You will want something like `\mintinline[breaklines, breakafter=-]{xml}{spring-boot-starter-test}`. I will probably need to refine this a little before releasing it in a future version of `minted`.

```latex 
\usepackage{minted}
\makeatletter
\renewcommand{\minted@inputpyg}{%
  \expandafter\let\expandafter\minted@PYGstyle%
    \csname PYG\minted@get@opt{style}{default}\endcsname
  \VerbatimPygments{\PYG}{\minted@PYGstyle}%
  \ifthenelse{\boolean{minted@isinline}}%
   {\ifthenelse{\equal{\minted@get@opt{breaklines}{false}}{true}}%
    {\let\FV@BeginVBox\relax
     \let\FV@EndVBox\relax
     \def\FV@BProcessLine##1{%
       \FancyVerbFormatLine{%
         \FV@BreakByTokenAnywhereHook
         \FancyVerbFormatText{\FancyVerbBreakStart##1\FancyVerbBreakStop}}}%
     \minted@inputpyg@inline}%
    {\minted@inputpyg@inline}}%
   {\minted@inputpyg@block}%
}
\makeatother
```
You can change the symbol that appears at the break using `breakaftersymbolpre`.

**Comment by benkuly** [comment]
Hm okay, but this only works when I want to break within the `\mintinline`. If I e.g. have a long class-name like `\mintinline[breaklines]{java}{AbstractSecurityInterceptor}` I don't want a break within the name. I want it completely on a new line if it dont fit on the same line. But actually I get the message `Underfull \hbox (badness 4819) in paragraph`. The command `\emergencystretch 3em` helps that it is on a new line, but that is only a workaroud. Maybe I missed something?

**Comment by gpoore** [comment]
@benkuly If you're dealing with a case where a break within the `\mintinline` isn't an option and you're getting `\hbox` messages, then you will have to use paragraph-level commands like `\emergencystretch` to get things to look acceptable. `\mintinline` doesn't have any information about its position in the line or overall paragraph layout, so it can't really turn these kinds of things on automatically. At that point, dealing with `\mintinline` is just like dealing with something like a very long number that can't be hyphenated, and thus requires manual adjustment to paragraph layout using `\emergencystretch`, `\sloppy`, or something similar, depending on the document context.

**Comment by benkuly** [comment]
Thank you very much 👍 👍

**Comment by arch-linux-tux** [comment]
When I try to use the code given by gpoore:

```
\usepackage{minted}
\makeatletter
\renewcommand{\minted@inputpyg}{%
  \expandafter\let\expandafter\minted@PYGstyle%
    \csname PYG\minted@get@opt{style}{default}\endcsname
  \VerbatimPygments{\PYG}{\minted@PYGstyle}%
  \ifthenelse{\boolean{minted@isinline}}%
   {\ifthenelse{\equal{\minted@get@opt{breaklines}{false}}{true}}%
    {\let\FV@BeginVBox\relax
     \let\FV@EndVBox\relax
     \def\FV@BProcessLine##1{%
       \FancyVerbFormatLine{%
         \FV@BreakByTokenAnywhereHook
         \FancyVerbFormatText{\FancyVerbBreakStart##1\FancyVerbBreakStop}}}%
     \minted@inputpyg@inline}%
    {\minted@inputpyg@inline}}%
   {\minted@inputpyg@block}%
}
\makeatother
```

This does not make `\mintinline[breaklines, breakbefore=.]{java}{tesssssssssssssssssssssssssssssssssssssssssssssssssssst.breaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak}` break for me. So it **doesn't work for me**.

Anyways, I can't find the work `breakafter` in the code.

**Comment by gpoore** [comment]
@arch-linux-tux The code does usually work, but your particular example is failing due to TeX's hyphenation system. `minted` uses `fvextra` internally for the line breaking. The break itself uses `\discretionary`, which involves TeX's hyphenation system. By default, hyphenation won't work for such a long string of text with only a single possible hyphenation point (the period in this case). You would need to modify hyphenation settings. Using something like `\setlength{\rightskip}{0pt plus 1 fil}` works. However, this will change hyphenation for the rest of the document. To limit it to a single paragraph, you probably want something like this:
```latex
\begingroup
\setlength{\rightskip}{0pt plus 1 fil}
<paragraph with \mintedinline that won't normally break>
\endgroup
```

**Comment by zhanwenchen** [comment]
By accident, I discovered a strange combination that worked. Up top, I declared `\` . Whole example below:

```latex
\documentclass{article}
\usepackage[utf8]{inputenc}

\usepackage{minted}
\usemintedstyle{borland}

\setmintedinline{breaklines} % necessary for breakanywhere to work later on.

\title{EECE5354 Computer Vision: Assignment 1}
\author{Zhanwen Chen}
\date{January 27, 2019}

\begin{document}

\maketitle

\section{Introduction}

This assignment requires implementation of three image processing functions: separation filter with a Gaussian kernel, and two more with my choosing. In addition, other deliverables include a function to limit all image processing functions to only process a sub-region specified by a rectangle, and an example video output with specific operations.

\vspace{5mm}

In my solution, I first refactored the assignment starter script, \mintinline[breakanywhere]{python}{testcv_mt_vid.py}, to use object-oriented approach where I replaced with state attributes all global variables that the program modifies during running.

\section{Implementation of Separation Filter}


1. \mintinline[breakanywhere]{python}{sepFilter2D()} with a Gaussian Kernel that you generate using \mintinline[breakanywhere]{python}{getGaussianKernel()}. (Note that you can get the same results using the module called \mintinline{python}{GaussianBlur()}. But I want you to use \mintinline{python}{sepFilter2D} with a Gaussian Kernel so that you learn how to apply an arbitrary separable filter to an image.)

\end{document}
```

**Comment by caniko2** [comment]
What about documents with custom margins?

**Comment by gpoore** [comment]
@caniko2 Custom margins shouldn't affect `breaklines`, unless the custom margins are used to define very narrow columns that make hyphenation difficult. In that case, you may need to work with `breakbefore`, `breakafter`, or custom hyphenation settings in addition to just using `breaklines`. All line breaking is using TeX's normal hyphenation, so `breaklines` should work anywhere that hyphenation would.
