### ISSUE TITLE
Docker image for minted

### ISSUE THREAD

**Issue by fortierq** [gpoore/minted#310]
I would like to use a GitHub action to compile LaTeX with minted.  
I tried the following docker image :
```
FROM texlive/texlive:latest

USER root

RUN apt update -y --allow-releaseinfo-change && \
    apt install -y python3-pygments build-essential

```
This is working locally. 
However, I keep getting those error messages when using this image with a GitHub action :
```
Error: cannot read infile: [Errno 2] No such file or directory: 'resume.pyg'
(./_minted-resume/default.pygstyle)

! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.
```
I spent many hours trying to solve minted-related problems.  
Does anybody have a working GitHub action with minted that I could use?

**Comment by XuehaiPan** [comment]
> ```
> ! Package minted Error: Missing Pygments output; \inputminted was
> probably given a file that does not exist--otherwise, you may need 
> the outputdir package option, or may be using an incompatible build tool,
> or may be using frozencache with a missing file.
> ```

I have encountered the same issue.

Did you use `minted` package with option `autogobble`? Have a look at issue #287.

I think you could add the following line to your Dockerfile:

```dockerfile
RUN ln -sf /usr/bin/python3 /usr/bin/python
```
