### ISSUE TITLE
`autogobble` does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by MakisH** [gpoore/minted#318]
I am trying to narrow down why `autogobble` works on one system, but not on another.

**Minimal working example:**
```tex
% file test.tex
% build with pdflatex -shell-escape -pdf test.tex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[frame=single, autogobble]{c}
    int main() {
      printf("hello, world");
      return 0;
    }
\end{minted}
\end{document}
```

**Generated output:**
![Screenshot from 2021-12-19 19-16-33](https://user-images.githubusercontent.com/4943683/146686115-1865e81f-e5b3-4fbf-b09e-6133abdc9243.png)

**Expectation:**

I would expect that the code starts directly after the left line of the frame, but currently there are four spaces (the indentation in the code, which `autogobble` is supposed to remove) .

**Context:**

This system is using:
- Ubuntu 20.04
- TeXLive 2019 from APT ([details](https://packages.ubuntu.com/focal/texlive-full))
-  minted 2017/07/19 v2.5
- Pygments 2.10.0 installed via PIP (Python 3.8)
- fancyvrb 2020/01/13 v3.5

The system where this is working is using:
- Ubuntu 21.04
- TeXLive 2020 from APT ([details](https://packages.ubuntu.com/hirsute/texlive-full))
-  minted 2017/07/19 v2.5
- Pygments v2.7.1 installed via APT (Python 3.9.5)
- fancyvrb 2021/01/20 v3.7

Is there anything I can try on the Ubuntu 20.04 system to fix it?

Potentially related to #196, #315

**Comment by muzimuzhi** [comment]
Related: #287

**Comment by MakisH** [comment]
Thank you very much for your quick reply! :heart: 

Indeed, installing `python-is-python3` solved this for me. Apparently, I had the package installed on the system where is works, but not on the system where is fails.

Closing as duplicate of #287.
