### ISSUE TITLE
Fonts not embedded in the pdf

### ISSUE THREAD

**Issue by benabel** [gpoore/minted#319]
Hi, and first thanks for this really handy package.

I was quite confused when I created a beautiful pdf with the help of `minted` via `lualatex`. The pdf is perfect on my pdf reader and if I print it from my computer, but when I'd go to my work and printed it, my students were quite surprised seeing a lot of `à` and other weird characters on the code blocks.

After struggling with this issue exploring encoding , I discovered that I needed to force embedding all fonts in my pdf with ghostscript to get a perfect pdf at work too.

```sh
gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -dEmbedAllFonts=true -sOutputFile=${name}_embedded.pdf -f ${name}.pdf
```

I don't know much about tex, but do you think it is possible to inform the pdf engine that you need those fonts embedded.

**Comment by gpoore** [comment]
`lualatex` should embed all the font data a PDF needs automatically. There may be some sort of issue with your LaTeX installation or document setup, and it might also be worth checking whether the LaTeX installation is relatively recent and up to date. `minted` doesn't have any control over font processing; all of that is taken care of by `lualatex` and perhaps font-related packages. You might ask a question at https://tex.stackexchange.com/ if you continue to have issues.

**Comment by benabel** [comment]
Thank you for your quick answer, in fact I also changed the monofont when switching to minted it is maybe related to this change:

```
\setmonofont{SourceCodePro}[Scale=MatchLowercase]
```

It is really difficult to investigate this bug because everything seems fine on my computer and I need to print it at work.

Thanks again for your answer and this package, I close the issue.
