### ISSUE TITLE
Filenames with commas in them `,` seem to break compilation (Windows/MikTeX/pdflatex.exe)

### ISSUE THREAD

**Issue by masq** [gpoore/minted#322]
## Problem
As stated in the title, filenames with commas in them `,` seem to break compilation (at least on Windows with MikTeX using pdflatex.exe as the compiler)

## Reproduction Steps

1. Create a file called `minted,comma,test.tex`
2. Write the following into the file:

```latex
\documentclass{report}
\usepackage{minted}

\begin{document}
This is a minted comma test.
\end{document}
```

3. Compile the PDF with the following:

```powershell
PS C:\Users\REDACTED\reports> pdflatex.exe '.\minted,comma,test.tex' --shell-escape --quiet
'comma' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\REDACTED\reports>set ,comma,test.aex  /p x=C:\Users\REDACTED\AppData\Roaming\Python\Python38\Scripts\pygmentize.exe,comma,test.aex 0<nul: 1>>minted 

C:\Users\REDACTED\reports>set ,comma,test.aex  /p x=,comma,test.aex 0<nul: 1>>minted

C:\Users\REDACTED\reports>set ,comma,test.aex  /p x=,comma,test.aex 0<nul: 1>>minted
:10: Emergency stop
:10:  ==> Fatal error occurred, no output PDF file produced!
```

4. See that the output has failed to compile a PDF and that the shell commands seem to have broken up the filename with the comma as a delimiter.

I've not tinkered too closely with the codebase here, but based on what I'm seeing, I'm guessing that what's happening here is something along the lines of minted calling `\OSShell{pygmentize \filename{}}` which is expanding to `\OSShell{pygmentize minted, comma, test.tex}` where the OSShell macro/command is being passed 3 parameters instead of one. This might have to do with LaTeX argument expansion, and the order in which that happens. I know there are tricks to change how that behavior works, so maybe one of those could be employed here in order to fix this issue from happening.

In the meantime, I'll alter some of my filenames to avoid commas, but it would be nice if I didn't have to do that. I thankfully have that option as a workaround, but others might not.

## Version Info
* Windows 10 Enterprise 20H2
* Minted v2.5 (implied by MiKTeX Console's package DB showing package date of 2017-07-19)
```powershell
> pdflatex.exe --version
MiKTeX-pdfTeX 4.4 (MiKTeX 21.2)
© 1982 D. E. Knuth, © 1996-2021 Hàn Thế Thành
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.8, 13-Jul-2019
compiled with curl version 7.72.0; using libcurl/7.72.0 Schannel
compiled with expat version 2.2.10; using expat_2.2.10
compiled with jpeg version 9.4
compiled with liblzma version 50020052; using 50020052
compiled with libpng version 1.6.37; using 1.6.37
compiled with libressl version LibreSSL 3.1.4; using LibreSSL 3.1.4
compiled with MiKTeX Application Framework version 4.1; using 4.1
compiled with MiKTeX Core version 4.4.1; using 4.4.1
compiled with MiKTeX Archive Extractor version 4.0; using 4.0
compiled with MiKTeX Package Manager version 4.2.1; using 4.2.1
compiled with uriparser version 0.9.4
compiled with xpdf version 4.02
compiled with zlib version 1.2.11; using 1.2.11
```

**Comment by muzimuzhi** [comment]
> ```powershell
> PS C:\Users\REDACTED\reports> pdflatex.exe '.\minted,comma,test.tex' --shell-escape --quiet
> 'comma' is not recognized as an internal or external command,
> operable program or batch file.
> ```

https://stackoverflow.com/q/11990688 will solve the first problem, but you may soon encounter other problems caused by comma(s). I would suggest to not use comma in filename, and if you really want to do that, renaming before and after latex compilation is always a choice.

**Comment by muzimuzhi** [comment]
> [...] so it shouldn't be a powershell-based issue of expansion.

But the lines I quoted in https://github.com/gpoore/minted/issues/322#issuecomment-1034802075 indicate the comma _is_ mis-interpreted hence powershell ran `comma` and only found `'comma' is not recognized as an internal or external command, operable program or batch file.`

**Comment by gpoore** [comment]
In this case, `\ShellEsc` should quote the path. I think there was a point in the past where it did quote the path, but then that was interfering with shell expansion for Linux, so the quoting was removed. I believe spaces in files paths worked for a while, but then one or more of the packages `minted` relies on changed its quoting behavior, and now there are errors under some circumstances (https://github.com/gpoore/minted/issues/276). There are a lot of issues with path handling in LaTeX when shell escape is involved. As far as I know, there is no existing package/library for working with paths and no standardized approach, so no existing easy solution.

**Comment by gpoore** [comment]
This entire class of issues is eliminated in `minted` v3.0, which is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon.
