### ISSUE TITLE
Minted mintinline not reading arg verbatim

### ISSUE THREAD

**Issue by sra-minshall** [gpoore/minted#327]
Macros defined with `\newmintinline` do not read their args as verbatim. We end up not being able to write something common such as `\inlinetext{scratch_test.js}` because a "not in math mode" error occurs. Using the underscore package helps but prevents us from writing `\jsfile{scratch_test.js}` without generating errors. 

It'd be great to have both use cases implemented without using the underscore package!

        \documentclass{beamer}
        
        % \usepackage[strings]{underscore}
        \usepackage{minted}
        \newmintedfile{js}{linenos} % \jsfile{} ...
        \newmintinline[txt]{inlinetext}{} % \txt{foo}
        
        \begin{document}
        
        \jsfile{scratch_test.js}     % this errors *with* \usepackage[strings]{underscore}
        \inlinetext{scratch_test.js} % this errors *without* \usepackage[strings]{underscore}
        
        \end{document}

**Comment by gpoore** [comment]
I think this will do what you want (there is no Pygments lexer called `inlinetext`):

```latex
\documentclass{beamer}

\usepackage{minted}
\newmintedfile{js}{linenos}
\newmintinline[txt]{text}{}

\begin{document}

\jsfile{scratch_test.js}
\txt{scratch_test.js}

\end{document}
```
There may be some edge cases where `\newmintinline` commands don't give exactly the same behavior as `\mintinline`, but this seems to work fine.

**Comment by sra-minshall** [comment]
Thanks Geoffrey, 

It works, I was mistaken.

Simon
