### ISSUE TITLE
breakanywhere does not work

### ISSUE THREAD

**Issue by damnms** [gpoore/minted#328]
i have something like \mintinline[breakanywhere]{bash}|keepassxc-cli add -q -g -lUnse -L 16 -u 'studium33@xxx.xxx' $DB_FILE tutanota|
this goes way above the page ending, unfortunately it does not break, even with spaces
i also tried 'breakafter= ' but seems like that also did not help (to tell to break after spaces)

**Comment by gpoore** [comment]
`breakanywhere` and `breakafter` allow breaks at locations other than spaces, but only when line breaking has already been turned on. Try something like `\mintinline[breaklines, breakanywhere]`, or `\setminted{breaklines}` if you want breaking for the entire document.
