### ISSUE TITLE
firstnumber=\ref*{marker} not working

### ISSUE THREAD

**Issue by duzy** [gpoore/minted#330]
Wish the firstnumber to use value like \ref*{line-in-a-file}:

```latex
\begin{minted}[firstnumber=\ref*{marker-from-foo-js}]{javascript}
function foo() {
}
\end{minted}

\inputmintedfile{foo.js}
```

foo.js:
```javascript
...

function foo() {//$label{marker-from-foo-js}$
}

...
```

**Comment by muzimuzhi** [comment]
Several steps are needed:
 - for `foo.js`, use `|\label{\detokenize{<label>}}|`  to add a label, then use minted option `escapeinside=||` when inputting. 
   - Vert `|` is used as delimiter, to reserve dollar `$` for minted option `mathescape`.
   - The `\detokenize` is needed for allowing `-` in label names, see #312.
 - for `firstnumber=<number>`, use an expandable way to extract the (Arabic) value of a label. That's what `\getrefnumber{<label>}` from `refcount` package for. Note `\ref(*)` is not expandable.

Full example. I deliberately make the value of label different from 1, so it's easier to check if `firstnumber=\getrefnumber{...}` works.
```tex
\begin{filecontents}[noheader,force]{foo.js}
function foo() {
} |\mintlabel{marker-from-foo-js}|
\end{filecontents}

\documentclass{article}
\usepackage{minted}
\usepackage{refcount}

\newcommand\mintlabel[1]{%
  \label{\detokenize{#1}}%
}

\begin{document}
Use the value of label \verb|marker-from-foo-js| in setting \verb|firstnumber=<number>|
\begin{minted}[autogobble, firstnumber=\getrefnumber{marker-from-foo-js}, linenos]{javascript}
  function foo() {
  }
\end{minted}

Typeset \verb|foo.js| which defines label \verb|marker-from-foo-js|
\inputminted[escapeinside=||, linenos]{javascript}{foo.js}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/170851938-4b06541f-2d14-4104-877c-496e93ca2346.png)

**Comment by duzy** [comment]
Yes,  `firstnumber=\getrefnumber{...}` works exactly as expected. Thank you!

**Comment by duzy** [comment]
Hi, is it possible to have the similar function for `highlightlines`?
```latex
\inputminted[escapeinside=||, linenos, highlightlines={\getrefnumber{marker-in-foo-js}}]{javascript}{foo.js}
```

This doesn't work for me.

**Comment by muzimuzhi** [comment]
Not possible until you apply some patch, for example one of the two redefinitions below. Note the original definitions live in `fvextra.sty`.

```tex
\makeatletter
% either expand value of `highlightlines` by \edef. This is more useful than the second one.
% before: \define@key{FV}{highlightlines}{\def\FV@HighlightLinesList{#1}}
\define@key{FV}{highlightlines}{\edef\FV@HighlightLinesList{#1}}

% or remove the \detokenize which disables expansion for #1. Is this \detokenize ever required?
\def\FV@HighlightLinesParse@Single#1{%
  % before: \expandafter\let\csname FV@HighlightLine:\detokenize{#1}\endcsname\relax
  \expandafter\let\csname FV@HighlightLine:#1\endcsname\relax}
\makeatother
```

**Comment by muzimuzhi** [comment]
> Hi, is it possible to have the similar function for `highlightlines`?
> 
> ```
> \inputminted[escapeinside=||, linenos, highlightlines={\getrefnumber{marker-in-foo-js}}]{javascript}{foo.js}
> ```
> 
> This doesn't work for me.

Just found this was once asked and answered (by myself) two years ago (Jun 2020) on tex-sx: https://tex.stackexchange.com/a/549882 .
