### ISSUE TITLE
highlightlines uses the line number after setting FancyVerbLine

### ISSUE THREAD

**Issue by tangruize** [gpoore/minted#332]
I want to highlight lines that look like GitHub commit inserted lines. I set the line number of inserted lines to 1001 and 1002. When the line number is 1002, I set it back to 154 to continue numbering. The problem is that highlighting line 1002 does not work, but highlighting 154 works. It seems that `highlightlines` uses the line number after setting `FancyVerbLine`. Is this an expected behavior, or am I using the wrong method to do it?

An example latex file:
```tex
\documentclass{article}

\usepackage{minted}
\setminted{frame=single, linenos=true, escapeinside={||}, autogobble=true}
\usepackage{refcount}

\makeatletter
\define@key{FV}{highlightlines}{\edef\FV@HighlightLinesList{#1}}
\makeatother

\begin{document}
\newcommand\sldots[0]{\scriptsize\ldots}
\renewcommand\theFancyVerbLine{%
\ifnum\value{FancyVerbLine}=1
 \setcounter{FancyVerbLine}{153}\sldots
\else\ifnum\value{FancyVerbLine}=154
\setcounter{FancyVerbLine}{1000}%
\scriptsize{154}%
\else\ifnum\value{FancyVerbLine}=1001
\scriptsize{+}%
\else\ifnum\value{FancyVerbLine}=1002
\setcounter{FancyVerbLine}{154}%
\scriptsize{+}%
\else
\scriptsize\arabic{FancyVerbLine}%
\fi\fi\fi\fi
}

highlightlines \getrefnumber{new2} and \getrefnumber{new3}
\begin{minted}[highlightlines={\getrefnumber{new2},\getrefnumber{new3}}]{python}
# suppressed
hello|\label{new1}|
world|\label{new2}|
hello|\label{new3}|
world|\label{new4}|
\end{minted}

highlightlines \getrefnumber{newa} and \getrefnumber{newb}
\begin{minted}[highlightlines={\getrefnumber{newa},\getrefnumber{newb}}]{python}
# suppressed
hello|\label{newa}|
world|\label{newb}|
hello|\label{newc}|
world|\label{newd}|
\end{minted}

\end{document}
```

Compiled PDF:
![Screenshot_20220612_163849](https://user-images.githubusercontent.com/19245736/173224840-c32beb4b-4375-44bf-9ed7-02551c68df33.png)

**Comment by muzimuzhi** [comment]
> Is this an expected behavior, or am I using the wrong method to do it?

Yes I think that's just the expected behavior.

Currently `FancyVerbLine` is stepped before a line is processed (see `fancyvrb.sty`, definition of `\FV@@PreProcessLine`), and line components are typeset in order of left number, left frame, formatted line (including highlights), right frame, right number (see `fvextra.sty`, definitions of `\FV@ListProcessLine@Break` and `\FV@ListProcessLine@NoBreak`). So it seems too late to update line counter by `\the<cnt>`, and it's even wrong when line number is typeset on both sides.

I find `fancyvrb.sty`'s `\FV@refstepcounter` suitable for setting a customized stepping command:
```tex
%% fancyvrb.sty v4.5, lines 1023--1038
\def\FV@refstepcounter#1{%
  \stepcounter{#1}%
  \protected@edef\@currentlabel{\csname p@#1\endcsname\arabic{FancyVerbLine}}%
}
\def\FV@StepLineNo{%
  \FV@SetLineNo%
  \def\FV@StepLineNo{%
    \if@FV@NumberBlankLines%
      \FV@refstepcounter{FancyVerbLine}%
    \else%
      \ifx\FV@Line\empty%
      \else%
        \FV@refstepcounter{FancyVerbLine}%
      \fi%
    \fi}%
  \FV@StepLineNo}
```

An example:
```tex
\documentclass{article}

\usepackage{minted}
\setminted{frame=single, linenos=true, escapeinside={||}, autogobble=true}
\usepackage{refcount}

\makeatletter
\define@key{FV}{highlightlines}{\edef\FV@HighlightLinesList{#1}}
\makeatother

\begin{document}
\renewcommand\theFancyVerbLine{\scriptsize
  \ifnum\value{FancyVerbLine}=1\relax
    \ldots
  \else\ifnum\value{FancyVerbLine}=154\relax
    \arabic{FancyVerbLine}%
  \else\ifnum\value{FancyVerbLine}=1001\relax
    +%
  \else\ifnum\value{FancyVerbLine}=1002\relax
    +%
  \else
    \arabic{FancyVerbLine}%
  \fi\fi\fi\fi
}

\makeatletter
\pretocmd\FV@refstepcounter
  {\myfv@stepcounter{#1}}
  {}{\PatchFailed}

\def\myfv@stepcounter#1{%
  \ifnum\value{#1}=1\relax
    \setcounter{#1}{153}%
  \else\ifnum\value{#1}=154\relax
    \setcounter{#1}{1000}%
  \else\ifnum\value{#1}=1002\relax
    \setcounter{#1}{154}%
  \fi\fi\fi
}
\makeatother

highlightlines \getrefnumber{new2} and \getrefnumber{new3}
\begin{minted}[highlightlines={\getrefnumber{new2},\getrefnumber{new3}}]{python}
# suppressed
hello|\label{new1}|
world|\label{new2}|
hello|\label{new3}|
world|\label{new4}|
\end{minted}

highlightlines \getrefnumber{newa} and \getrefnumber{newb}
\begin{minted}[highlightlines={\getrefnumber{newa},\getrefnumber{newb}}]{python}
# suppressed
hello|\label{newa}|
world|\label{newb}|
hello|\label{newc}|
world|\label{newd}|
\end{minted}

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/173226549-d5925182-15b4-46bb-bd20-7fad6c30729e.png)

**Comment by muzimuzhi** [comment]
Additions:
 - Using `firstnumber=<number>` will save the condition for `\ifnum\value{...}=1\relax`
 - When the conditionals get longer, you may construct corresponding count register before enter the conditional part to save some time.
    ```tex
    % \myfv@stepcounter{FancyVerbLine}
    \def\myfv@stepcounter#1{%
      \expandafter\myfv@stepcounter@\csname c@#1\endcsname}
    
    % \myfv@stepcounter@\c@FancyVerbLine
    \def\myfv@stepcounter@#1{%
      \ifnum#1=1\relax
        #1=153\relax
      \else\ifnum#1=154\relax
        #1=1000\relax
      \else\ifnum#1=1002\relax
        #1=154\relax
      \fi\fi\fi
    }
    ```

**Comment by tangruize** [comment]
Thank you very much!  I think it is the right way to do it!

The only problem is that the conditionals are repeated twice. one is in `\renewcommand\theFancyVerbLine` to print line number strings such as `+`, the other is in `\def\myfv@stepcounter@#1` to set line counters. The conditionals are very long in my doc, and it is error-prone and cumbersome to maintain in two places. Currently I still use `\renewcommand\theFancyVerbLine` to set all other line counters except those with labels.

**Comment by muzimuzhi** [comment]
The two conditional block is not the same:
 - The one prepended to `\FV@stepcounter` cares about midpoints: if line number == midpoint n, then number = skipped point n.
 - The one in `\theFancyVerbLine` cares about both midpoints and ranges: if line number is in list of ranges a, then typeset +; else if it's in list of ranges b, then typeset -; else if it's one of midpoints, typeset line number in arabic; ... .

Thus their forms are not necessarily the same, for example in your example the real conditional for `\theFancyVerbLine` might be
```python
# represented in python 
if n == 1:
  typeset("\\ldots")
else if n == 154:
  typeset("\\arabic{FancyVerbLine}")
else if 1001 <= n <= 1002: # note this is actually a range
  typeset("+")
```

LaTeX package `ifthen` provides utilities for expressing and, or, and not boolean operations, so can be used to shorten the conditionals a bit.

In general and if it's really needed you can develop a set of preprocessor and postprocessor (in python scripts) for `minted` so it can automatically process, for example `git diff` output and typeset in your desired style, which is loosely related to #193. A preprocessor reads in `.aex` temp file and prepare input for `pygments`, and a postprocessor reads in output of `pygments` (`.pygtex` file, which contains a `Verbatim` env) and updates it. There's an example for postprocessor in https://tex.stackexchange.com/a/623502 .

**Comment by tangruize** [comment]
My code has a lot of lines to skip, and a few lines to highlight. Here is the commands:

```tex
\makeatletter
\renewcommand\theFancyVerbLine{\scriptsize
\ifnum\value{FancyVerbLine}=32
  \setcounter{FancyVerbLine}{98}\ldots
\else\ifnum\value{FancyVerbLine}=100
  \setcounter{FancyVerbLine}{106}\ldots
\else\ifnum\value{FancyVerbLine}=108
  \setcounter{FancyVerbLine}{111}\ldots
\else\ifnum\value{FancyVerbLine}=113
  \setcounter{FancyVerbLine}{117}\ldots
\else\ifnum\value{FancyVerbLine}=121
  \setcounter{FancyVerbLine}{125}\ldots
\else\ifnum\value{FancyVerbLine}=127
  \setcounter{FancyVerbLine}{132}\ldots
\else\ifnum\value{FancyVerbLine}=134
  \setcounter{FancyVerbLine}{145}\ldots
\else\ifnum\value{FancyVerbLine}=147
  \setcounter{FancyVerbLine}{151}\ldots
\else\ifnum\value{FancyVerbLine}=1001
  +%
\else\ifnum\value{FancyVerbLine}=1002
  +%
\else\ifnum\value{FancyVerbLine}=156
  \setcounter{FancyVerbLine}{181}\ldots
\else\ifnum\value{FancyVerbLine}=187
  \setcounter{FancyVerbLine}{188}\ldots
\else\ifnum\value{FancyVerbLine}=191
  \setcounter{FancyVerbLine}{197}\ldots
\else
  \arabic{FancyVerbLine}%
\fi\fi\fi\fi\fi\fi\fi\fi\fi\fi\fi\fi\fi
}

\def\myfv@stepcounter@#1{%
  \ifnum#1=154\relax
    #1=1000\relax
  \else\ifnum#1=1002\relax
    #1=154\relax
  \fi\fi
}
\makeatother
```

I think that it is good enough, and moving `\setcounter` to `\myfv@stepcounter` will  repeat the conditional. May be there are better ways to do git-diff highlight and code line number skipping?

Currently my listings do not have git-diff removed lines, which should be highlighted as red. If I have this need later, I will investigate your method. Thanks a lot!
