### ISSUE TITLE
The chapter name in memoir header/footer gets set to mono.

### ISSUE THREAD

**Issue by nm17** [gpoore/minted#333]
What should I do about it? I tried setting my own header styles with \normalfont added to them, and it still changed my font to sans.

![image](https://user-images.githubusercontent.com/23419131/173898591-72b72cf3-9ee7-401e-a6da-74c52b107836.png)

**Comment by gpoore** [comment]
You will need to provide more information about how you are configuring your document to get help with this. Ideally, you will need to provide a very short, complete, minimal document that reproduces the issue. This may be related more to how you are configuring fonts than specifically to `minted` itself. If that is the case, you may have a better chance of finding a solution by asking a question at https://tex.stackexchange.com/.

**Comment by nm17** [comment]
Fixed with switching from miklatex to texlive.

**Comment by muzimuzhi** [comment]
> Fixed with switching from miklatex to texlive.

The real cause might be different versions of packages they apply or you currently installed.

**Comment by nm17** [comment]
Yep, probably minted's fault
