### ISSUE TITLE
Not enable all ligatures when using FiraCode

### ISSUE THREAD

**Issue by duskmoon314** [gpoore/minted#335]
Hello. I'm trying to use FiraCode with minted but have encountered the problem of not enabling all ligatures.

FiraCode supports a lot of ligatures and I want to use the ligature of `>=>`. But In the `minted` environment, I get `>` and `=>` separately. I also try it in `\texttt{}` and it works.

Example Pic:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/20477228/174752916-aac89076-890b-4525-ba39-fb92eba5322a.png">

The preamble part of my tex file:

```latex
\setmonofont{Fira Code}
\usepackage[cachedir=_minted]{minted}
\setminted[text]{fontsize=\normalsize,breaklines}
\usemintedstyle{default}
```

**Comment by muzimuzhi** [comment]
See https://tex.stackexchange.com/questions/294362/use-fira-code-font-with-ligatures-in-code-listings

**Comment by duskmoon314** [comment]
> See [tex.stackexchange.com/questions/294362/use-fira-code-font-with-ligatures-in-code-listings](https://tex.stackexchange.com/questions/294362/use-fira-code-font-with-ligatures-in-code-listings)

I have already tried this and still have the same problem. So I assume it has something to do with `minted`. BTW, this definitely works when using `verbatim` alone.

**Comment by muzimuzhi** [comment]
Then please provide a complete (and if possible, minimal) example, not code snippet with screenshot[^1]. And you should mention what you tried and what you got, no matter the result is negative or partial.

[^1]: Please never ever post images of code. --- daleif ([link](https://tex.stackexchange.com/questions/640002/the-function-and-meaning-of-variable-afterindenttrue#comment1595225_640002))

**Comment by gpoore** [comment]
The linked answer involves multiple steps. The version toward the end uses `\def\verbatim@nolig@list{}`. This is worth trying if you haven't already.

One additional factor that may be relevant: Pygments, which `minted` uses to do the actual highlighting, converts `>=>` into `\PYGZgt{}=\PYGZgt{}` in the highlighted LaTeX output, where the Pygments style file defines ``\def\PYGZgt{\char`\>}``. It's possible `\PYGZgt` needs to be redefined.

**Comment by duskmoon314** [comment]
> Then please provide a complete (and if possible, minimal) example, not code snippet with screenshot[1](#user-content-fn-1-bfedc704d66c789397141932aeab4502). And you should mention what you tried and what you got, no matter the result is negative or partial.

Sorry, my fault.

I have tried to make a minimal example and I found out the main problem is using `ctex` instead of `fontspec` to write in Chinese. FiraCode works well in the minted environment, even without using `\def\verbatim@nolig@list{}`.

Sorry for my bother. Thanks.
