### ISSUE TITLE
Create cache directory lazily

### ISSUE THREAD

**Issue by t-b** [gpoore/minted#343]
The following document creates an empty folder `_minted-$filename`

```
\documentclass{article}

\usepackage{minted}

\begin{document}
Hello :)
\end{document}
```

but it would be nicer if that folder is only created when it is really needed.

**Comment by gpoore** [comment]
This is fixed in `minted` v3.0, which is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon.
