### ISSUE TITLE
importing mathtools after minted gives errors in amsmath.sty

### ISSUE THREAD

**Issue by julisokay** [gpoore/minted#349]
After updating packages recently i got errors when compiling my latex files. I tracked the error down and got this minimal (not) working example:

```
\documentclass{article}

\usepackage{minted}
\usepackage{mathtools} 

\begin{document}
Test
\end{document}
```

These are the errors i can reproduce on two machines:

> Command \gather already defined. }
> Command \gather* already defined. }
> Command \alignat already defined. }
> Command \alignat* already defined. }
> Command \align already defined. }
> Command \align* already defined. }
> Command \flalign already defined. }
> Command \flalign* already defined. }
> Command \multline already defined. }
> Command \multline* already defined. ...tart@multline\st@rredtrue}{\endmultline}
> Command \equation* already defined. }

all stemming from amsmath.sty

As soon as i swap the import of minted with mathtools, the errors disappear.

**Comment by davidcarlisle** [comment]
See

https://github.com/latex-lineno/lineno/issues/5

an update there is promised, changing the load order is a usable workaround as you say.

**Comment by julisokay** [comment]
Thank you for your incredibly quick answer!
