### ISSUE TITLE
Passing additional flags to `pygmentize` / Using local lexers with the `-x` flag

### ISSUE THREAD

**Issue by schtandard** [gpoore/minted#350]
I sometimes want to use a custom pygments lexer residing in the document directory (i.e. not installed system-wide). This can be achieved using `pygmentize`'s `-x` option. Of course, `minted` is calling `pygmentize` for me, so I have to get it to pass that flag for me. In the past, I could just enter it as part of the "language name". For example, if I have a file named `pygmentsmod.py` in the document directory in which I define a `pygments` lexer `MyTexLexer`, I could say
```latex
\mintinline{./pygmentsmod.py:MyTexLexer -x}{\relax}
```

This no longer works, as `\minted@opt@quote` now quotes my "language", including the `-x`. I can still trick `minted` by using
```latex
\mintinline{./pygmentsmod.py:MyTexLexer" -x"}{\relax}
```
instead (on Windows), but while while I found the previous hack to be somewhat acceptable, this is just ugly.

So, I would like to request
- either explicit support for this use-case (e.g. by detecting the "language" ending with ` -x`)
- or the ability to add arbitrary flags to the command line call performed by `minted` (in the usual key-value fashion)
- or `minted` just setting the `-x` flag for all calls (which could lead to conflicts when there is a file with the same name as a `pygmentize` language, but won't have an effect otherwise).

**Comment by jeeger** [comment]
[This](https://github.com/gpoore/minted/issues/182) used to work, but I can't get it to work with current versions of minted.

**Comment by gpoore** [comment]
`minted` version 3.0 is now under development, thanks to a grant from the [TeX Users Group](https://tug.org/). It will include official support for custom lexers. It will also be able to be extended using Python, not just LaTeX macro programming, which will make possible many new lexer-related features. Progress on custom lexers will be tracked in #372. Initial beta releases of `minted` version 3.0 are expected by early 2024.
