### ISSUE TITLE
breakautoindent option doesn't work with some languages

### ISSUE THREAD

**Issue by j-tai** [gpoore/minted#359]
The `breakautoindent` option doesn't work when the language is `c`, `cpp`, `json`, `yaml`, and possibly others. It works fine for other languages such as `text`, `java`, `kotlin`, `javascript`, `typescript`, `python`, `perl`, `html`, and `latex`.

Reproduce:

```latex
\documentclass{article}
\usepackage{minted}

\setminted{breaklines, breakautoindent}

\begin{document}
\begin{minted}{c}
char* first = "afjeowij f eowa ijfe awo i fejwoai f jeo wiafj eo wijfo";
    char* second = "afjeowij f eowa ijfe awo i fejwoai f jeo wiafj eo wijfo";
        char* third = "afjeowij f eowa ijfe awo i fejwoai f jeo wiafj eo wijfo";
\end{minted}
\end{document}
```

Although I set `breakautoindent` in the preamble's `\setminted`, the feature does not have any effect.

![image](https://user-images.githubusercontent.com/45131430/221302144-2f07dcb6-e981-4862-9481-108f05feff4c.png)

I expected it to look like this (ignore the different colors):

![image](https://user-images.githubusercontent.com/45131430/221304817-8a975a8c-19bd-47c5-ad83-72b0feb79c04.png)

minted version: 2.7 from master branch
Log file: [minted-breakautoindent.log](https://github.com/gpoore/minted/files/10829121/minted-breakautoindent.log)

**Comment by gpoore** [comment]
Are you using the latest version of `fvextra`? It is used internally for line breaking, and the last release improved these sorts of situations. Your example works for me with the latest `minted` and `fvextra`.

**Comment by j-tai** [comment]
Looks like that's it. Thanks!

**Comment by muzimuzhi** [comment]
`minted` could add a soft requirement on the minimum release date of `fvextra` (`\RequirePackage{fvextra}[2022-11-30]`), so users using outdated `fvextra` relative to `minted` will receive a warning. Using `\IfPackageAtLeast{<pkg>}{<date>}{<true code>}{<false code>}` could even issue an error.
