### ISSUE TITLE
`\mintinline{cpp}{#include}` in section title results in error

### ISSUE THREAD

**Issue by zwz** [gpoore/minted#362]
Here is a MWE
```
\documentclass{article}  
\usepackage{minted}
\begin{document}
\section{... \mintinline{cpp}{#include} ...}             %% ! Illegal parameter number in definition of \reserved@a.
Normal text \mintinline{cpp}{#include} works.
\end{document}
```

**Comment by gpoore** [comment]
As mentioned in the documentation, `\mintinline` cannot be used inside other commands when the `#` character is used.

A saved box is probably the best solution:

```
\newsavebox\mybox
\begin{lrbox}{\mybox}
\mintinline{cpp}{#include}
\end{lrbox}

\section{Text \usebox{\mybox}}
```

**Comment by zwz** [comment]
Good to know this.
I have to read the document again.

**Comment by zwz** [comment]
@gpoore
I find I have to deal with font size in saved box, which is quite a burden.
Inspired by https://tex.stackexchange.com/questions/249883/temporarily-changing-catcode-of
something like
```
\catcode`#=11
\section{
\mintinline{cpp}{#include}
}
...
```
also works.

Just share it here, in case it helps improve this package.

**Comment by muzimuzhi** [comment]
@zwz Try my experimental `\EscMintInlin`, which works similar to `\EscVerb` from `fvextra` package, in https://github.com/gpoore/minted/issues/288#issuecomment-1501540637.

**Comment by muzimuzhi** [comment]
> @zwz Try my experimental `\EscMintInlin`, which works similar to `\EscVerb` from `fvextra` package, in [#288 (comment)](https://github.com/gpoore/minted/issues/288#issuecomment-1501540637).

And you may want to restrict the scope of catcode changes locally, mostly in a group, like `{\catcode`\#=11 \section{...}}`.

**Comment by zwz** [comment]
@muzimuzhi  It is great!

Yes, I put `catcode` in a group.
But this trick does not work for `%`, which bothers me for a while before I see your comment and `\EscMintInlin`.

**Comment by muzimuzhi** [comment]
> But this trick does not work for `%`

You need sth like `\catcode`\%=11`.

**Comment by gpoore** [comment]
In the next version of `minted`, I can add a note in the documentation about `catcode` changes as an alternative to saving boxes, and can also look into adding a new variant of `\mintinline` based on `fvextra`'s `\EscVerb`.

**Comment by muzimuzhi** [comment]
The error similar to
```tex
Runaway argument?
{\contentsline {section}{\numberline {2} \FVExtraRobustCommand \RobustMintInline \ETC.
! File ended while scanning use of \@writefile.
<inserted text> 
                \par 
l.6 \begin{document}
```
is caused by writing a direct `%` to `.aux` file.  One further trick is to hide the percent char in a protected macro, but then such macro should be provided before begin document, otherwise you'll get error "Undefined Control Sequence xxx" when `.aux` is read in at that point.  This would be inconvenient if you have many `\mintinline` containing `%` in sectioning titles.

Or if it's ok to typeset plain code in toc and headers, ``{\catcode`\%=11 \section[\EscVerb{3 \%\ 2}]{\mintinline{cpp}{3 % 2}}}``.  Right now I don't have the time to find why the space after `\%` must be escaped to be not gobbled in toc.
```tex
\documentclass{article}
\usepackage{minted}

{\catcode`\%=11
\protected\gdef\mymint{\mintinline{cpp}{3 % 2}}
}

\begin{document}
\tableofcontents

\section{title}
\section{\mymint}

{\catcode`\%=11
\section[\EscVerb{3 \% 2}]{\mintinline{cpp}{3 % 2}}
\section[\EscVerb{3 \%\ 2}]{\mintinline{cpp}{3 % 2}}
}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/231345832-b8387d6b-3f56-4b00-9dbe-ac5b739c6a8d.png)

**Comment by zwz** [comment]
Thank you for looking into the error.
It helps a lot.

**Comment by zwz** [comment]
@gpoore 
I read the document those days.
It says: "Curly braces are required when \mintinline is used in a movable argument, such as in a \section."
I tried something like `\section{Text \mintinline{cpp}|if(0){printf("never");}|}` and it works.
So I am wondering whether `{}` are not required anymore?

**Comment by gpoore** [comment]
@zwz There are some cases where you can use something besides `{}`, but that typically won't work correctly if you need `\tableofcontents`.
