### ISSUE TITLE
Font settings

### ISSUE THREAD

**Issue by goyalyashpal** [gpoore/minted#366]
### Summary

* I am migrating over to <tt>[minted]</tt> package from <tt>[listings]</tt> package due to its limitations 
(bad parsing in html comments, lacking css support, bad text layer rendering), 
* but i can't find fine grained options in the [minted manual].
* and it ain't respecting my document wide font settings either.
* I tried searching the web: [this] and [that], but couldn't narrow down the results to minted package specific

[listings]: https://ctan.org/pkg/listings
[minted]: https://ctan.org/pkg/minted
[minted manual]: https://mirror.niser.ac.in/ctan/macros/latex/contrib/minted/minted.pdf
[setminted]: https://mirror.niser.ac.in/ctan/macros/latex/contrib/minted/minted.pdf#page=15
[365]: https://github.com/gpoore/minted/issues/365#issuecomment-1517794111
[fancyvrb]: https://ctan.org/pkg/fancyvrb
[this]: https://duckduckgo.com/?q=set+font+to+times+new+roman+in+minted+package+latex&t=vivaldi&ia=web "set font to times new roman in minted package latex"
[that]: https://duckduckgo.com/?q=latex+minted+times+new+roman+font&t=vivaldi&ia=web "latex minted times new roman font"

So, i needed some pointers for achieving the same results.

I looked at this issue as well [365] which mentions setting via <tt>[fancyvrb]</tt> package i guess, but couldn't figure out how to use that in <tt>\\[setminted]{}</tt>

### Details

The basic settings I need & couldn't find are:
* font settings:
    * **[MUST]** main: 12pt, times new roman, black (even for keywords)
    * comments: 12 pt, times new roman, gray
    * line number: any smaller font size, times new roman, lighter gray
* source location: to avoid typing complete relative location again and again

+ [DONE] ~~[MUST] `breaklines` to soft wrap the long lines~~

Following are my settings for the listings package:

```tex
\documentclass[12pt,a4paper,oneside,titlepage,final]{report}
\renewcommand*\rmdefault{ptm}
\newcommand{\setfsize}[1]{\fontsize{#1}{
        \dimexpr #1 * 12 / 10}\selectfont}
   ...

% These worked
\setminted{ %
	% Inclusion/Exclusion below
	breaklines=true,
	xleftmargin=10pt,
	numbers=left,                 	% linenos=true,
	numberblanklines=false,
	stepnumber=1,
	% showstringspaces=false,	% showspaces is there, but not showstringspaces
}

% These ERRORED/didn't work
% \setminted{ %
	% Basic Stuff
	% inputpath=\src,
	% language=html,		% language not optional in \inputminted{LANGUAGE}{FILE}
	% otherkeywords=???,
	%
	% Styles Below
	% size's already handled in documentclass option
	% fontfamily=ptm,
	% fontsize=\setfzie{12pt},
	%
	% basicstyle=,%\setfsize{12pt}, 
	% For model: Gray (Integer grayscale)
	% keywordstyle=\mdseries, %\textbf,
	% stringstyle=\normalfont, %\color[gray]{0},
	% commentstyle=\color[gray]{0.6},
	% numberstyle=\scriptsize\color[gray]{0.7},
% }

\lstset{ %
	% Basic stuff
	inputpath=\src,
	language=html,
	% otherkeywords={cin,cout,endl},
	%
	% Inclusion/Exclusion below
	showstringspaces=false,
	breaklines=true,
	xleftmargin=10pt,
	numbers=left,
	stepnumber=1,
	%
	% Styles Below
	% size's already handled in documentclass option
	basicstyle=,%\setfsize{12pt}, 
	% For model: Gray (Integer grayscale)
	keywordstyle=\mdseries, %\textbf,
	stringstyle=\normalfont, %\color[gray]{0},
	commentstyle=\color[gray]{0.6},
	numberstyle=\scriptsize\color[gray]{0.7},
}
```

<p align="center">
LEFT: <tt>minted</tt> , RIGHT: <tt>listings</tt>
<br/><br/>
<img src="https://user-images.githubusercontent.com/19423063/234044491-3c91769f-585f-40b5-aec7-08382a1f976c.png">
</p>

### Versions

* `listings`: 1.9
* `minted`: 2.7

**Comment by gpoore** [comment]
`minted` only provides four font settings: `fontfamily`, `fontsize`, `fontshape`, `fontseries`. These simply pass options on to `fancyvrb` internally; `fancyvrb` actually does the code typesetting. `fancyvrb` only provides built-in support for a few fonts, so you will have to configure it for what you want, which will partly depend on whether you are using pdfTeX, XeTeX, or LuaTeX. [TeX.SE](https://tex.stackexchange.com/) may be helpful.

There is no `minted` equivalent of the `listings` setting `inputpath`.

There is no "cooperation" between `fancyvrb` and `listings`. There are some settings in common, and in some situations they can be used together. But they often have different settings and different approaches.

**Comment by goyalyashpal** [comment]
i am using pdflatex.

also, fancyvrb doesnt have any issue tracker/community post discussions where i can file suggestions to 'em right? like here, gitlab, s_forge, c_berg, s_hunt etc...

**Comment by gpoore** [comment]
For something like Times Roman under pdfTeX, you can try this:
```
\usepackage{mathptmx}
\usepackage{minted}
\setminted{fontfamily=ptm}
```
If you want to customize things further, you'll probably need to go through the respective documentation or perhaps search https://tex.stackexchange.com/.

`fancyvrb` doesn't have a git repo or issue tracker anywhere that I'm aware of.

**Comment by goyalyashpal** [comment]
so, font size to 12, and no formatting for anything (i.e. all black) except comments will still require going to fancyvrb?

**Comment by gpoore** [comment]
Size: `\documentclass[12pt]{article}`, `\setminted{fontsize=\large}`, etc.

Color: `\setminted{style=bw}`. If you really want gray comments, you'll have to customize the comment token macro. You'll need something like this in the preamble:
```
\makeatletter
\appto{\minted@patch@PYGZhy}{%
  \def\PYG@tok@c{\let\PYG@it=\textit\def\PYG@tc##1{\textcolor[rgb]{0.5,0.5,0.5}{##1}}}}
\makeatother
```

**Comment by goyalyashpal** [comment]
thanks for all the help. i had some thoughts related to this in direction of maybe some linking minted API with listings instead of fancyvrb...

but couldnt formalise it very well, so, wiill leave it at that

thabks again.

**Comment by goyalyashpal** [comment]
Just a small note, color mode `gray` also works instead of `rgb`

```diff
- \def\PYG@tok@c{\let\PYG@it=\textit\def\PYG@tc##1{\textcolor[rgb]{0.5,0.5,0.5}{##1}}}}
+ \def\PYG@tok@c{\let\PYG@it=\textit\def\PYG@tc##1{\textcolor[gray]{0.5}{##1}}}}
```

**Comment by goyalyashpal** [comment]
```

**Comment by goyalyashpal** [comment]
> \setminted{fontfamily=ptm}
\- @ gpoore at https://github.com/gpoore/minted/issues/366#issuecomment-1522543607

with `setminted` or `fvset` using `ptm` font; the characters like `_` , `<` etc from the source code are not rendering properly.

<p align="center">
LEFT: <tt>minted</tt> , RIGHT: <tt>listings</tt>
<br/><br/>
<img width=90% src="https://github.com/gpoore/minted/assets/19423063/f801797c-2436-4939-bbf6-f69b8f3ec83c" />
</p>

**Comment by gpoore** [comment]
`\usepackage[T1]{fontenc}`

**Comment by goyalyashpal** [comment]
> `linerange`, `lastline`, `consecutivenumbers`, `firstnumber`

* `firstnumber`
https://github.com/gpoore/minted/blob/13e25d05cd382cf55f66636e0b1a91d94c2b4e4c/source/minted.dtx#L1318-L1320

* `lastline`
https://github.com/gpoore/minted/blob/13e25d05cd382cf55f66636e0b1a91d94c2b4e4c/source/minted.dtx#L1365

* `inputlanglinenos`
https://github.com/gpoore/minted/blob/13e25d05cd382cf55f66636e0b1a91d94c2b4e4c/source/minted.dtx#L917-L918



Only linerange remains now
