### ISSUE TITLE
Is it possible to `/inputminted` a whole github repository or a whole directory?

### ISSUE THREAD

**Issue by vincint-skywalker** [gpoore/minted#369]
Is it possible to `/inputminted` a whole github repository or a whole directory?

**Comment by gpoore** [comment]
LaTeX doesn't have a built-in way to access remote files or work with git repos. And there isn't globbing to process entire directories (but you can use `\ShellEscape` to try to build your own).

You might consider writing something like a Python or shell script that puts all the files you want in a single directory, then creates a `.tex` file that has `\inputminted` for each of these files. Then you could `\input` that `.tex` file in your main document.
