### ISSUE TITLE
Support custom lexers

### ISSUE THREAD

**Issue by gpoore** [gpoore/minted#372]
Track progress of custom lexer support for `minted` v3.0.

**Comment by gnull** [comment]
Is there a way to try out the beta version of 3.0 at the moment?

**Comment by gpoore** [comment]
This is now possible in v3.0.0beta1. If you would like to experiment with the beta version, installation instructions are [here](https://github.com/gpoore/minted/tree/v3-dev) and the [CHANGELOG](https://github.com/gpoore/minted/blob/v3-dev/latex/CHANGELOG.md) includes details about new features (the PDF documentation won't be fully updated until the final v3 release). Otherwise, the final v3 release should be available sometime in June.
