### ISSUE TITLE
Breaking line within \newmintinline throws error

### ISSUE THREAD

**Issue by carlostome** [gpoore/minted#376]
Using `pdflatex -shell-escape` on:
```latex
\documentclass{article}

\usepackage[]{minted}

\newmintinline[hs]{haskell}{}

\begin{document}
\hs\f x = x\
\hs\f x
= x\
\end{document}
```

causes the following error:

```
...
Runaway argument?
f x
! Forbidden control sequence found while scanning use of \FV@ReadVArg@Char@i.
<inserted text>
                \par
l.10 \hs\f x
...
```
I can reproduce this error using versions `2.7` and `2.8` of minted (with TexLive 2023 installed). However, using version `2.6` the above code compiles successfully. 

(I'm not sure if this is a bug or an intended feature)

**Comment by gpoore** [comment]
This is fixed in the [dev version of `fvextra`](https://github.com/gpoore/fvextra/blob/master/fvextra/fvextra.sty). A new `fvextra` release will be out in the next day or so.
