### ISSUE TITLE
[feature] Support for PDDL programming language

### ISSUE THREAD

**Issue by david-alvarez-rosa** [gpoore/minted#381]
I'm recently working with [PDDL programming language](https://en.wikipedia.org/wiki/Planning_Domain_Definition_Language) -- could we get support for fancy syntax highlighting?

Found a gist online for `listings` env https://gist.github.com/morxa/9162dfc62261294621fd that could potentially be migrated.

Open to help here!

**Comment by muzimuzhi** [comment]
The syntax highlighting is actually provided by python package `pygments` https://github.com/pygments/pygments. You can file a feature request there.

**Comment by david-alvarez-rosa** [comment]
That makes sense.  Will do, thanks!

https://github.com/pygments/pygments/issues/2616
