### ISSUE TITLE
breaksymbolleft flush with line numbers

### ISSUE THREAD

**Issue by mstarodub** [gpoore/minted#384]
Using `breaklines`, the break symbol is indented to the level of the preceding line. 
What I would like is the symbol to be aligned with the line numbers instead:
![image](https://github.com/gpoore/minted/assets/23422754/a917f95c-9482-4699-8bfd-54f700c47651)

Additionally, an option to mark the next line as a continuation of the preceding one (like the slightly light background before the word `store` in the image) would be great. This could be e.g. a thin horizontal bar.

**Comment by gpoore** [comment]
The line breaking is implemented in [`fvextra`](https://github.com/gpoore/fvextra). Unfortunately, the line numbering and line breaking are implemented separately, so I don't believe there is a way to get what you want without redesigning much of what currently exists.

**Comment by mstarodub** [comment]
Thanks, I understand. I'll close this then.
