### ISSUE TITLE
Overfull hbox with `mintinline` and `breakanywhere` in enumerate environment 

### ISSUE THREAD

**Issue by janstarke** [gpoore/minted#387]
Dear all,

we observe `overfull hbox` messages when we're using `mintline` in an enumerate environment. We use this situation when when enumerate a set of file paths, which can be really long and can contain where long parts (e.g. hashes or UUIDs), which is why we don't want to break only at token boundaries, but `anywhere`.

I was trying to add some glue at the end of the line as a mitigation, but without success. Does anyone have a solution for this problem?

# Minimal working example:

## Code

```latex
\documentclass{article}
\usepackage{minted}

\begin{document}

\begin{itemize}
    \item \mintinline[breaklines,breakanywhere]{output}{This_is_very_very_very_very_very_very_very_very_very_long_verbatim_text}
\end{itemize}

\end{document}
```

## Observed result

The output of LaTeX contains the following warning:
```
Overfull \hbox (0.61113pt too wide) in paragraph at lines 2--9
[][][]\TU/lmtt/m/n/10 T[]h[]i[]s[]_[]i[]s[]_[]v[]e[]r[]y[]_[]v[]e[]r[]y[]_[]v[]
e[]r[]y[]_[]v[]e[]r[]y[]_[]v[]e[]r[]y[]_[]v[]e[]r[]y[]_[]v[]e[]r[]y[]_[]v[]e[]r
[]y[]_[]v[]e[]r[]y[]_[]l[]o[]n[]g[]_[]v[]e[]
```

The warning does not occur when `mintinline` is not used inside an `enumerate` environment

## Expected result

No warnings

**Comment by muzimuzhi** [comment]
I would suggest to just live with such a small amount of overfull hbox (0.61113pt).

> The warning does not occur when `mintinline` is not used inside an `enumerate` environment

Given the same left margin, the overfull hbox is reproducible outside of an `itemize` environment.

```tex
\documentclass{article}
\usepackage{minted}

\begin{document}

\begin{itemize}
    \item \mintinline[breaklines,breakanywhere]{output}{This_is_very_very_very_very_very_very_very_very_very_long_verbatim_text}
\end{itemize}

% emulate left margin of \item in first level itemize
% see anatomy of list dimensions in https://latexref.xyz/list.html
\noindent\hskip\dimexpr\leftmargin+\itemindent\relax
\mintinline[breaklines,breakanywhere]{output}{This_is_very_very_very_very_very_very_very_very_very_long_verbatim_text}

\end{document}
```

**Comment by gpoore** [comment]
I agree with @muzimuzhi about ignoring the overfull `\hbox` in a case like this and perhaps setting `\hfuzz` to a larger value to suppress `\hbox` warnings. `fancyvrb` sets `\hfuzz=2pt` by default, but that only works within `Verbatim` environments, not for inline code. Apparently `\hfuzz` must be set for an entire paragraph or larger segment of a document at a time.

I've added a new option `breakanywhereinlinestretch` in `fvextra`. This is currently in the dev version ([`fvextra.sty`](https://github.com/gpoore/fvextra/blob/master/fvextra/fvextra.sty)); a new release will be on CTAN within a few days. This is supported in `minted` v3.0, which is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon.

`breakanywhereinlinestretch` makes it possible to allow the spacing between adjacent non-space characters to stretch slightly. Using the new `fvextra` plus `minted` v3.0, it is possible to set `breakanywhereinlinestretch=0.01em` and prevent overfull `\hbox` in the examples above. Personally, I don't think that results in any significant visual improvement in this case; it just causes the line break to occur one character earlier. But I think this feature will be significantly more helpful in some other scenarios.
