### ISSUE TITLE
Missing Pygments output; \inputminted...

### ISSUE THREAD

**Issue by pikapuma** [gpoore/minted#393]
I came up with the same problem as issue 81(https://github.com/gpoore/minted/issues/81). I‘v installed pygmentize and added it to path, and "pygmentize -v" works in cmd. I tried "\usepackage[cache=false]{minted}", the .tex file can be compiled successfully. However, the code could not appear in the generated PDF file. I also tried other posibble solutions mentioned in issue 81, but they all didn't work.

Here's the log:
This is XeTeX, Version 3.141592653-2.6-0.999995 (MiKTeX 24.1) (preloaded format=xelatex.fmt)
 \write18 enabled.
entering extended mode
(test.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-20>
(D:\MiKTeX\tex/latex/base\article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(D:\MiKTeX\tex/latex/base\size10.clo)) (D:\MiKTeX\tex/latex/minted\minted.sty
(D:\MiKTeX\tex/latex/graphics\keyval.sty)
(D:\MiKTeX\tex/latex/kvoptions\kvoptions.sty
(D:\MiKTeX\tex/generic/ltxcmds\ltxcmds.sty)
(D:\MiKTeX\tex/latex/kvsetkeys\kvsetkeys.sty))
(D:\MiKTeX\tex/latex/fvextra\fvextra.sty
(D:\MiKTeX\tex/latex/etoolbox\etoolbox.sty)
(D:\MiKTeX\tex/latex/fancyvrb\fancyvrb.sty)
(D:\MiKTeX\tex/latex/upquote\upquote.sty (D:\MiKTeX\tex/latex/base\textcomp.sty
)) (D:\MiKTeX\tex/latex/lineno\lineno.sty))
(D:\MiKTeX\tex/latex/base\ifthen.sty) (D:\MiKTeX\tex/latex/tools\shellesc.sty)
(D:\MiKTeX\tex/latex/ifplatform\ifplatform.sty
(D:\MiKTeX\tex/generic/pdftexcmds\pdftexcmds.sty
(D:\MiKTeX\tex/generic/infwarerr\infwarerr.sty)
(D:\MiKTeX\tex/generic/iftex\iftex.sty))
(D:\MiKTeX\tex/generic/catchfile\catchfile.sty
(D:\MiKTeX\tex/generic/etexcmds\etexcmds.sty))
(D:\MiKTeX\tex/generic/iftex\ifluatex.sty))
(D:\MiKTeX\tex/latex/xstring\xstring.sty
(D:\MiKTeX\tex/generic/xstring\xstring.tex))
(D:\MiKTeX\tex/latex/framed\framed.sty) (D:\MiKTeX\tex/latex/float\float.sty))
(D:\MiKTeX\tex/latex/xcolor\xcolor.sty
(D:\MiKTeX\tex/latex/graphics-cfg\color.cfg)
(D:\MiKTeX\tex/latex/graphics-def\xetex.def)
(D:\MiKTeX\tex/latex/graphics\mathcolor.ltx))
d:\LaTeXfiles\test>set  /p x=D:\software\Python312\Scripts\pygmentize.exe 0<nul: 1>>test.aex 

d:\LaTeXfiles\test>set  /p x= 0<nul: 1>>test.aex 

d:\LaTeXfiles\test>set  /p x= 0<nul: 1>>test.aex 

(D:\MiKTeX\tex/latex/l3backend\l3backend-xetex.def)
No file test.aux.
(D:\MiKTeX\tex/latex/base\ts1cmr.fd) (_minted-test/default.pygstyle)Error: Invalid value 'False -o _minted-test/F4324A37EE6AF25085C1182FD3F845E1BD968F0BABE9D056D2818AC1457194D6.pygtex test.pyg' for option stripnl; use 1/0, yes/no, true/false, on/off

test.tex:6: Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.6 \end{minted}
                
(test.aux) )
(see the transcript file for additional information)
No pages of output.
Transcript written on test.log.

"\usepackage[cache=false]{minted}" could make compilation successful, but would not generate the code in "\begin{minted} ... \end{minted}":
![屏幕截图 2024-04-30 231250](https://github.com/gpoore/minted/assets/116414939/b5b0f4b1-6bd9-49f5-a7ed-4f1e9bd36ff6)

**Comment by gpoore** [comment]
Have you tried updating MiKTeX? This is likely the same MiKTeX issue as #386, which was resolved by using the latest version of MiKTeX.

**Comment by pikapuma** [comment]
Thanks a lot! it works well after updating MikTeX
