### ISSUE TITLE
Get full timestamp in XeTeX through \creationdate

### ISSUE THREAD

**Issue by muzimuzhi** [gpoore/minted#395]
Code comment on [line 1578 of `minted.dtx@1ac8e25e`](https://github.com/gpoore/minted/blob/1ac8e25ed1d390faa9a3df2c2fb99b7feefeb60a/latex/minted/minted.dtx#L1578C104-L1578C205) says

> Under XeTeX, a derived timestamp (via |\year|, |\month|, |\day|, |\time|) with only minute precision.

Actually XeTeX provides `\creationdate` since TeX Live 2019, which is equivalent to `\pdfcreationdate` in pdfTeX.

Since `\pdfcreationdate` (or its equivalence) is one of the primitives required by l3kernel and l3kernel is bundled in the LaTeX2e format, `\creationdate` is always available in recent LaTeX2e.

Also the expl3 provides a cross-engine string variable `\c_sys_timestamp_str` which holds the full timestamp of current job. But it's relatively new (needs l3kernel [2023-08-29](https://github.com/latex3/latex3/compare/2023-08-11...2023-08-29)).

**Comment by gpoore** [comment]
Thanks for the suggestions! I've switched to `\creationdate`, and left a note in the code documentation to use `\c_sys_timestamp_str` once it has been available for longer.
