### ISSUE TITLE
Feature request - mintinline max. depth and height

### ISSUE THREAD

**Issue by projetmbc** [gpoore/minted#397]
The following MWE shows that it would be more useful to have a `b`-height and a `p`-depth when a background color is used.

```latex
\documentclass[12pt]{article}

\usepackage{minted}
\newmintinline{latex}{bgcolor = yellow}

\begin{document}

TEST \latexinline|b| \latexinline|.| \latexinline|p| TEST

\end{document}
```

**Comment by muzimuzhi** [comment]
Something like this?

```tex
\documentclass{article}
\usepackage{minted}
\newmintinline{latex}{bgcolor = yellow}

\begin{document}
\subsection*{Before}
TEST \latexinline|b| \latexinline|.| \latexinline|p| TEST \\
TEST \latexinline|b| \latexinline|.| \latexinline|p| TEST

\makeatletter
\def\minted@inputpyg@inline{%
  \ifthenelse{\equal{\minted@get@opt{bgcolor}{}}{}}%
   {\minted@input{\minted@outputdir\minted@infile}}%
   {\colorbox{\minted@get@opt{bgcolor}{}}{%
      % added \strut
      \strut\minted@input{\minted@outputdir\minted@infile}}}%
}
\makeatother

\subsection*{After}
TEST \latexinline|b| \latexinline|.| \latexinline|p| TEST \\
TEST \latexinline|b| \latexinline|.| \latexinline|p| TEST
\end{document}
```
![image](https://github.com/gpoore/minted/assets/6376638/88640f15-6e13-4404-879d-d15047bd6182)

**Comment by projetmbc** [comment]
Looks great.

Are you going to use this feature by default?

Maybe an optional argument would be the right choice, to leave the possibility of having the old behavior.

**Comment by muzimuzhi** [comment]
Using `tcolorbox` package, if the title of a tcolorbox is set by `adjusted title=<title>`, the `<title>` will have the same minimum height and depth as that of `\"Agypten`, which is configurable by  `/tcb/adjust text=<text>` option.

If `minted` would like to provide a flexible solution then the treatment in `tcolorbox` may help.

> Do you plan to make this option available by default?

That depends on the maintainer of `minted`, @gpoore .
