### ISSUE TITLE
Error with `dvilualatex`

### ISSUE THREAD

**Issue by michal-h21** [gpoore/minted#406]
I've just updated Mintex in my TeX Live installation, and it now produces an error in the DVI output with LuaLaTeX. Here is a MWE:

```latex
\documentclass{article}
\usepackage{minted}
\usepackage[svgnames]{xcolor}
\begin{document}
\begin{minted}[bgcolor=Beige, bgcolorpadding=0.5em]{c}
int main() {
  printf("hello, world");
  return 0;
}
\end{minted}
\end{document}
```

Compiled using:

      $ dvilualatex sample.tex

I've got the following error:

```
! unexpected use of \pdffeedback.
<argument> \pdffeedback 
             creationdate
l.83 ...ondatetotimestamp{\pdffeedback creationdate}
                                                  }
```

More errors follow, but they are the result of this one. 

Dvilualatex is not that much used on it's own, but it can be used as a backend in TeX4ht, using `make4ht -l filename.tex`.

The solution is to test if we  are in the PDF mode using `\ifpdf` command provided by the `iftex` package:

```
\ifpdf
  \expandafter\ifx\csname pdftexversion\endcsname\relax
  \else
    \xdef\minted@timestamp{\minted@creationdatetotimestamp{\pdfcreationdate}}
  \fi
  \expandafter\ifx\csname XeTeXrevision\endcsname\relax
  \else
    \xdef\minted@timestamp{\minted@creationdatetotimestamp{\creationdate}}
  \fi
  \expandafter\ifx\csname directlua\endcsname\relax
  \else
    \xdef\minted@timestamp{\minted@creationdatetotimestamp{\pdffeedback creationdate}}
  \fi
\fi
```

The fallback method of the timestamp calculation will be used in the DVI mode, which seems to work fine.

**Comment by davidcarlisle** [comment]
the solution used by `luatex85.sty` (compatibility layer for luatex) is to just locally switch modes while defining the command
there it does (to define the pdftex name)

```
{\outputmode=1
         \xdef\pdfcreationdate   {\pdffeedback creationdate}
}
```

so here you could do

```
{\outputmode=1
         \xdef\minted@whatever  {\pdffeedback creationdate}
}
```

As long as the mode is set at the time of definition it doesn't need to be set when you use it.

**Comment by michal-h21** [comment]
Thanks, David. I can confirm that this fixed the error:

```latex 
    {\outputmode=1
    \xdef\minted@timestamp{\minted@creationdatetotimestamp{\pdffeedback creationdate}}
    }
```

**Comment by gpoore** [comment]
This is fixed in the dev version on GitHub, and I will be uploading a new release to CTAN within the next few hours. @davidcarlisle, thanks for the compact solution!

**Comment by michal-h21** [comment]
Thanks!

**Comment by muzimuzhi** [comment]
Alternatively, `l3kernel` uses `\directlua{pdf.getcreationdate()}`, see [here](https://github.com/latex3/latex3/blob/445d06f8ba3800241b1fc93426e5e8bf7fb5c43d/l3kernel/l3sys.dtx#L1030-L1045).
