### ISSUE TITLE
Package minted Error: minted v3+ executable is not installed or is not added to `PATH`.

### ISSUE THREAD

**Issue by Witiko** [gpoore/minted#409]
Since the last week's build of the `texlive/texlive` Docker image, the `minted` package appears broken:

```
$ docker run --pull=always --rm -it texlive/texlive
# cat > mwe.tex
```
``` tex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{tex}
\foo
\end{minted}
\end{document}
```
```
# pdflatex -shell-escape mwe.tex
```
```
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=pdflatex)
 \write18 enabled.

[... output omitted for brevity]

) (./_1A79A4D60DE6718E8E5B326E338AE533.config.minted)

! Package minted Error: minted v3+ executable is not installed or is not added 
to PATH.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.6 \end{minted}
                
? 
```

This prevents today's planned release of `witiko/markdown`, since we can't build documentation.
Any suggestions as to what the issue/solution could be, beyond what the error text says, and a hotfix/ETA for a fix?

**Comment by Witiko** [comment]
Closed as a duplicate of https://github.com/gpoore/minted/issues/401. Sorry about that!

**Comment by gpoore** [comment]
I believe #401 was primarily due to an issue with the initial CTAN packaging of `minted` v3.0. Everything should be working now. Does your Docker image include absolutely all recent TeX Live updates? If not, that could be the issue.

The only remaining part of #401 that I am aware of is the potential for errors during the first compile due to temp files. These automatically fix themselves on subsequent compiles once `minted` switched out of first-compile-optimization mode. That can currently be addressed by using `\usepackage[highlightmode=immediate]{minted}`, but I will be releasing a new version within the next day or so that automatically detects most temp files and prevents that error, while still working with first-compile-optimization mode.

**Comment by Witiko** [comment]
> I believe #401 was primarily due to an issue with the initial CTAN packaging of `minted` v3.0. Everything should be working now. Does your Docker image include absolutely all recent TeX Live updates? If not, that could be the issue.

It definitely includes the released version from 2024-09-22 that is listed on [CTAN](https://ctan.org/pkg/minted?lang=en). Running `tlmgr update --self minted` has no effect. The environmental variable `PATH` should also be set correctly but to rule it out, I manually ran `tlmgr path add` to no effect. My CI runs weekly and this is the first time the issue has surfaced, so this seems related to the 3.0.0 release.

My example from https://github.com/gpoore/minted/issues/409#issue-2556453303 should be easy to reproduce if you have a Linux box with Docker installed.

**Comment by Witiko** [comment]
> You might check to see if a `latexminted` executable exists in your Docker image.

It exists:

```
$ docker run --pull=always --rm texlive/texlive latexminted --version
```
```
latexminted 0.1.0 (libraries: latex2pydata 0.4.0, pygments 2.18.0)
```

**Comment by Vasco-Da-Gama-png** [comment]
I have the same problem as @Witiko with my own docker image. You can pull it from [here](https://collaborating.tuhh.de/m21/public/theses/latex_dockerfile/container_registry/416). The problem exist with the latest image. To pull use:
registry.collaborating.tuhh.de/m21/public/theses/latex_dockerfile:latest
I fixed the problem in my LaTeX project at the moment with the use of minted2.
latexminted is installed and on the path and python 3.12.6 as well.

**Comment by gpoore** [comment]
I released v3.1.1 on October 3, so it would have become available on October 4 or 5 from CTAN. This has resolved the missing executable error for at least some people. @Vasco-Da-Gama-png, it looks like your latest image isn't recent enough to include v3.1.1. I will also be releasing a new version later today, but don't expect that to include any changes that would affect this.

**Comment by Witiko** [comment]
The issue has been fixed for me in https://github.com/Witiko/markdown/pull/516 using today's release of the Docker image `texlive/texlive`. I am closing this issue. Please, feel free to reopen if @Vasco-Da-Gama-png still experiences issues with an up-to-date installation of TeX Live.

**Comment by Vasco-Da-Gama-png** [comment]
I rebuilded my docker image today and you're right, the mistake/error seems to be fixed. Thanks a lot!
