### ISSUE TITLE
Missing Color schemes from pygments

### ISSUE THREAD

**Issue by mauriciomm7** [gpoore/minted#417]
I am big fan of Git-Hub dark theme and wanted to use it for a paper but it trows me an error when using it (see below), yet you can find it list it on the pygments [styles list](https://pygments.org/styles/) .

**Source Code:**

```Tex
\setminted{ 
    style=github-dark,
}
```

**Expected behavior:** Set`github-dark` as highlighting theme

**Actual behavior:** Color not found.

![image](https://github.com/user-attachments/assets/e5d41a4c-c660-45e2-b079-8b4d560b698b)

I am not sure if this is an error a feature request 🤔

**Comment by samcarter** [comment]
@mauriciomm7 are you using overleaf? If yes, their pygments styles are maybe not up-to-date.

**Comment by muzimuzhi** [comment]
The `github-dark` style was added in [pygments v2.13.0](https://github.com/pygments/pygments/releases/tag/2.13.0) (2022-08-16), which is only available in the TeX Live 2024 image on overleaf.com.

| texlive version | pygments version | style <code>github-dark</code> available? |
|------|--------|-----|
| 2024 | 2.15.1 | Yes |
| 2023 | 2.11.2 | No  |

---

```tex
\documentclass{article}
\usepackage{minted}
\setminted{style=github-dark}
\begin{document}

{\ttfamily
\fmtversion \par
\input|"pygmentize -V" }

\begin{minted}[bgcolor=black]{python}
from typing import Iterator

# This is an example
class Math:
    @staticmethod
    def fib(n: int) -> Iterator[int]:
        """Fibonacci series up to n."""
        a, b = 0, 1
        while a < n:
            yield a
            a, b = b, a + b

result = sum(Math.fib(42))
print(f"The answer is {result}")
\end{minted}
\end{document}
```

<img width="685" alt="image" src="https://github.com/user-attachments/assets/778226de-3d5e-4e4f-96d7-0bb7324663dd">

**Comment by muzimuzhi** [comment]
BTW, one can use `\input|"pygmentize -L styles | grep -A1 github-dark"` (shell-escape needed) to show if the `github-dark` style is available.

**Comment by mauriciomm7** [comment]
Thank you so much @muzimuzhi! this worked perfectly, you see my own example below!
Overleaf has so many parameters that I just take them for granted.  

![image](https://github.com/user-attachments/assets/418cf124-1769-4b03-ba61-c82d1ba34dc9)

Also, thank you for tip to cross check what styles are available. I didn't know you add bash into La TeX.

**Comment by muzimuzhi** [comment]
> I didn't know you add bash into La TeX.

`\input|"<shell command>"` (or `\input{|"<shell command>"}`) is a special syntax of `\input` which expands to the standard output of executing `<shell command>`. The `pygmentize` and `grep` commands are provided by the invoked shell, not by LaTeX itself.
