### ISSUE TITLE
Cannot disable line numbers per listing when enabled globally

### ISSUE THREAD

**Issue by jonasc** [gpoore/minted#48]
The following code should (in my opinion) not display line numbers but it does (see picture):

``` .latex
\documentclass{article}
\usepackage{minted}
\setminted{linenos=true} % Enable line numbering globally
\begin{document}
\begin{minted}[linenos=false]{c} % Disable line numbering only for this code sample
int main() {
    printf("hello, world");
    return 0;
}
\end{minted}
\end{document}
```

![minted](https://cloud.githubusercontent.com/assets/2046766/4023106/ae1c0644-2b75-11e4-89e8-187c331bd3af.png)

Tested with current master c988796.

**Comment by danielpcampagna** [comment]
@jonasc Shouldn't it work independently of draft mode?
