### ISSUE TITLE
Additional dummy / plain text language

### ISSUE THREAD

**Issue by jonasc** [gpoore/minted#51]
I would really like to have a language (I suggest `plain` or `none`) which triggers minted to not call pygments and just render it without highlighting, just like it currently does in draft mode.

The reason for this is, that I don't want to have different ways of including source code for languages supported by pygments and code that is not supported. Additionally it would make it much easier to highlight it in case someone (e.g. me) writes a pygments lexer for the specific language.

I had a look into the code to see how draftmode is implemented but was rather held back when reading `The |draft| version digs into a lot of \pkg{fancyvrb} internals`.

**Comment by kupiakos** [comment]
If it makes you feel any better, I had the same question and this is the top result of "plaintext minted" on Google.

**Comment by ComFreek** [comment]
I've been here at least 5 times already in my life -- every time I forget what minted's plaintext language is called.

**Comment by muzimuzhi** [comment]
@randolf-scholz The `#1` in `\NewDocumentCommand{\minttt}{#1}{...}` is wrong syntax. Something like the following should just work
```tex
\NewDocumentCommnad{\minttt}{}{\mintinline{text}}
```
