### ISSUE TITLE
Defining a \newcommand that can take a minted environment as an argument

### ISSUE THREAD

**Issue by jonasc** [gpoore/minted#54]
I'm trying to create a new command to which I can give an minted environment. In the end I want a command to be able to take, among others, two minted environments which should be displayed side by side.
But I added a very simple example how I want to do it (at which also does not work and fails with the same error):

~~~.latex
\newcommand{\foo}[1]{#1}

\foo{
\begin{minted}{text}
a := 3 * b + c / 2
\end{minted}
}
~~~
The error output is:
~~~
! FancyVerb Error:
  Extraneous input ` a := 3 * b + c / 2 \end {minted} ' between \begin{minted}[
<key=value>] and line end
.
\FV@Error ... {FancyVerb Error:
\space \space #1
}
                                                  
l.31 }
~~~
Removing the `\foo{` and `}` compiles just fine. I guess it is somehow related with #45 -- but trying to use the savebox you recommended gives me other errors…

Maybe this is a more general LaTeX error/misuse on my side and not so much minted-related but if you could help me I'd appreciate it a lot.

**Comment by xiehao** [comment]
> You really want to use savebox if at all possible.
> 
> This will work, but will break easily and isn't compatible with XeLaTeX due to a bug in XeLaTeX's implementation of `\scantokens`. You have to do lots of trickery with catcodes.
> 
> ```
> \makeatletter
> \newcommand{\foo}{%
>   \begingroup
>   \let\do\@makeother\dospecials
>   \catcode`\{=1
>   \catcode`\}=2
>   \endlinechar`\^^J
>   \foo@i}
> \newcommand{\foo@i}[1]{%
>   \endgroup\scantokens{#1\noexpand}%
>   \expandafter\foo@cleanup}
> \def\foo@cleanup#1^^J{#1 }
> %http://tex.stackexchange.com/questions/71049/allow-macro-to-end-without-new-line
> \makeatother
> 
> \foo{
> \begin{minted}{text}
> a := 3 * b + c / 2
> \end{minted}
> }
> ```

Thanks for your reply, and this works with `xelatex` and `lualatex` now.

I have the same problem, how about a new command with 2 or more arguments (sorry I cannot quite follow your trick)? Say this MWE (the `\mintinline` works fine):

``` latex
\documentclass{beamer}

\usepackage{minted}%
\setminted{autogobble}
\usepackage{calc}%

\newlength{\leftwidth}
\newlength{\rightwidth}
\newcommand{\bicolumns}[3][0.618]{
    \setlength{\leftwidth}{#1\textwidth}
    \setlength{\rightwidth}{\textwidth-\leftwidth}
    \begin{columns}[T,onlytextwidth]
        \begin{column}{\leftwidth}
        #2
        \end{column}
        \begin{column}{\rightwidth}
        #3
        \end{column}
    \end{columns}
}

\begin{document}

\begin{frame}[fragile]
    \bicolumns[0.5]{
        \begin{minted}{python}
            print('Hello World!')
        \end{minted}
    }{
        \mintinline{python}{print('Hello World!')}
    }
\end{frame}

\end{document}
```

**Comment by gpoore** [comment]
@xiehao You could modify `\foo@i` to take more arguments, and then add `\scantokens{#2\noexpand}` etc. for those additional arguments. At some point, though, it's probably better to try a different approach.

**Comment by xiehao** [comment]
@gpoore Thank you very much for your help! I made it with your tips. But it seems no other character is allowed in the lines of "{" and "}" when invoking my new command. Besides, would you mind to share some "different approach" as you said?

**Comment by gpoore** [comment]
@xiehao The braces `{` and `}` have to be on lines by themselves because that is how line breaks are preserved. I suppose you could try to have them on the same line, and then add additional `^^J` with your command as needed. But that's why this approach can easily get pretty complicated.

The other approach will probably be a savebox or a specialized environment (perhaps with `\NewEnviron`). You might search and find some examples related to those at https://tex.stackexchange.com/.
