### ISSUE TITLE
way to specify pygments location?

### ISSUE THREAD

**Issue by soonhokong** [gpoore/minted#62]
Is there any way to specify the location of pygments to be used?

**Comment by gpoore** [comment]
The macro `\MintedPygmentize` contains the name of the program that is called to perform the highlighting. By default, this is `pygmentize`. You could change this by `\renewcommand{\MintedPygmentize}{<path to alternate pygmentize>}`.

**Comment by soonhokong** [comment]
Thank you!!

**Comment by soonhokong** [comment]
There is a problem. Could you help? This is my context:

 - `pygmentize` is not installed globally, but only locally. `pygmentize` is not in `PATH`. Let's say that we have `pygmentize` at `./pygments-main/pygmentize`.
 - I tried something like

    ```tex
\usepackage{minted}
\renewcommand{\MintedPygmentize}{./pygments-main/pygmentize}
    ```

But it gives me an error:
```
! Package minted Error: You must have `pygmentize' installed to use this packag
e.
```

The error comes from https://github.com/gpoore/minted/blob/master/source/minted.sty#L1199-L1206. I first attempted to fix this by having the following change:

```text
-    \TestAppExists{pygmentize}
+    \TestAppExists{\MintedPygmentize}
```

but it didn't work because of obvious reason: the error is generated at the time we run "usepackage{minted}" so it doesn't recognize the new value of `MintedPygmentize`. It seems that we, at least I, need a way to pass the location of `pygmentize` as an optional argument to `\usepackage{minted}`.

What do you think? Is there an easy way to achieve this?

**Comment by gpoore** [comment]
You are working with a case I hadn't considered. I wrote the code expecting a global `pygmentize`, but a custom script that would be used for calling it or hooking into Pygments. So this is actually a bug.

At https://github.com/gpoore/minted/blob/master/source/minted.sty#L1190, try replacing `\AtEndOfPackage` with `\AtEndPreamble`. That, plus your `\TestAppExists{\MintedPygmentize}`, should fix it. Then I will have to figure out the best way to deal with this case long-term.

**Comment by soonhokong** [comment]
> At https://github.com/gpoore/minted/blob/master/source/minted.sty#L1190, try replacing \AtEndOfPackage with \AtEndPreamble. That, plus your \TestAppExists{\MintedPygmentize}, should fix it.

It fixed my problem. Thanks a lot!! Do you want me to close the issue?

**Comment by gpoore** [comment]
Leave the issue open. I will fix this in the next release, and close it then.

**Comment by soonhokong** [comment]
I see. Thanks again!!

**Comment by soonhokong** [comment]
@gpoore, thank you! :+1:

**Comment by xuhdev** [comment]
@soonhokong I think `\TestAppExists{pygmentize}` should be `\TestAppExists{\MintedPygmentize}`...

**Comment by soonhokong** [comment]
@xuhdev, I don't get it. I already put `\TestAppExists{\MintedPygmentize}` on my codebase (see https://github.com/soonhokong/lean-tutorial/commit/a97800fe30735df924cf590bf7782fa10150d0df).

@gpoore, thanks for re-openning this issue. In 2.0, it worked well. But in the new version (2.1), it seems that it's not working anymore..

**Comment by xuhdev** [comment]
@soonhokong Sorry I shouldn't have pinged you....

The issue still exists on [this line](https://github.com/gpoore/minted/blob/master/source/minted.sty#L1485)

**Comment by soonhokong** [comment]
@xuhdev, I see. Probably, that's why the feature is not working in the new version (2.1).

**Comment by gpoore** [comment]
This should be correctly fixed now. @xuhdev thanks for pointing out the bug.
