### ISSUE TITLE
Ability to fold/hide sections of code

### ISSUE THREAD

**Issue by shobute** [gpoore/minted#64]
Would it be possible to have a feature which can fold/hide a section of code from a file? For example if I want to include a listing of everything in somefile.py apart from lines 5-10 it would miss out those lines and the line numbering would go 1,2,3,4,11,12,....

**Comment by gpoore** [comment]
There are currently `firstline` and `lastline` options that allow a range of lines to be specified. These, when combined with `firstnumber`, would allow you to get what you want. You would have to use `\inputminted` once for each range of lines that you want to show.

It would be possible to add built-in support for specifying multiple ranges of lines to show, but that would require modifications to the `fancyvrb` package, which `minted` uses internally. So it's unlikely to be added in the near future.

**Comment by shobute** [comment]
Thank you!
