### ISSUE TITLE
Compatibility with memoir class

### ISSUE THREAD

**Issue by PieterStroobants** [gpoore/minted#67]
I am interested in a standard look for every ```listof...``` inside my documents. I want
to switch from the standard ```listings``` package and use minted. Nearly every document
I produce uses the ```memoir``` class, which gets error messages when combined with
minted. I traced the source of this issue back to the inclusion of the ```float``` package.
A MWE is:
```
\documentclass{memoir}
\usepackage{minted}
\newlistof{listoflistings}{lol}{List of Listings}
\newfloat[chapter]{ftlisting}{lol}{Listing}% Error
\newlistentry[chapter]{ftlisting}{lol}{0}
\begin{document}
\listoflistings
\chapter{A}
\begin{minted}{java}
   System.out.println("...");
\end{minted}
\end{document}
```

**Comment by gpoore** [comment]
The `float` package defines a `\newfloat` command, which is overwriting the `\newfloat` defined by `memoir`, so it doesn't work properly. If you define your floats before loading `minted`, everything seems to work fine.

```latex
\documentclass{memoir}

\newlistof{listoflistings}{lol}{List of Listings}
\newfloat[chapter]{ftlisting}{lol}{Listing}
\newlistentry[chapter]{ftlisting}{lol}{0}
\usepackage{minted}
\begin{document}
\listoflistings
\chapter{A}
\begin{ftlisting}[H]
\begin{minted}{java}
   System.out.println("...");
\end{minted}
\caption{Caption}
\end{ftlisting}
\end{document}
```
