### ISSUE TITLE
How can I skip laxer errors which make red-box on pdf file

### ISSUE THREAD

**Issue by mickyching** [gpoore/minted#69]
minted generate file default.pygstyle which include following line:

\expandafter\def\csname PYGdefault@tok@err\endcsname{\def\PYGdefault@bc##1{\setlength{\fboxsep}{0pt}\fcolorbox[rgb]{1.00,0.00,0.00}{1,1,1}{\strut ##1}}}

The pygments parse complex code as errors and draw a red-box on the string, how can I skip the error
globally and remove the red-box. That is to say how to generate default.pygstyle without the above line.

Thanks.

**Comment by gpoore** [comment]
If you can tell me what language you're working with and give an example, I might be able to help with settings, or it might turn out that this is a Pygments bug.

If you want to customize the output, there is no way to do that directly in the *.pygstyle file. But you could create a wrapper for the Pygments macro. An example: http://tex.stackexchange.com/questions/232721/disabling-one-keyword-in-minted/232760#232760. You could look in the cached output, and see which letter corresponds to errors in the first argument to `\PYGdefault`.

Another option would be to create a dummy version of `\fcolorbox` that doesn't do anything. Something like this:
```latex
\AtBeginEnvironment{minted}{%
  \renewcommand{\fcolorbox}[4][]{#4}}
```

**Comment by mickyching** [comment]
I'm using org-mode to write source code, using c language with macros, this may be Pygments issue.
Please see the below pictures to find the problem.

create a dummy version of \fcolorbox is useful, Thank you very much!


![org-mode](https://cloud.githubusercontent.com/assets/3090447/6683027/3ca4c77a-ccbb-11e4-82a0-3e4f2baec5e7.png)
![latex-output](https://cloud.githubusercontent.com/assets/3090447/6683033/5a7e0cfc-ccbb-11e4-9334-62ea85ae88d5.png)

**Comment by gpoore** [comment]
My guess is that something isn't working with Pygments. I quickly tried the last `#define` from your picture, and it works fine for me. If you want to paste in the complete code for one of these blocks, as text so I can copy it, then I should be able to track down the source of the problem.

**Comment by mickyching** [comment]
The latex code generated was:

```latex

\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage{minted}

\setmainfont{Times New Roman}
\setmonofont{Ubuntu Mono}

\title{Sample Code Block}
\author{Micky}
\date{}

\begin{document}
\maketitle

\begin{minted}[frame=lines,fontsize=\small]{cpp}
  #define ATTRIBUTE_GROUPS(_name)                       \
  static const struct attribute_group _name##_group = { \
      .attrs = _name##_attrs,                           \
  };                                                    \
  __ATTRIBUTE_GROUPS(_name)
  #define __ATTRIBUTE_GROUPS(_name)                         \
  static const struct attribute_group *_name##_groups[] = { \
      &_name##_group,                                       \
      NULL,                                                 \
  }
\end{minted}

\end{document}

```

build with:
```sh
xelatex -shell-escape sample.tex
````

![latex-code](https://cloud.githubusercontent.com/assets/3090447/6703544/7d86c424-cd78-11e4-81fd-74f94e341e2a.png)

**Comment by gpoore** [comment]
The problem is that the code is indented by two spaces. Pygments will treat the code as preprocessor directives only if there is no leading indentation at the top level. You might open an issue at the [Pygments site](https://bitbucket.org/birkenfeld/pygments-main/issues).

In terms of working around this, you might be able to modify org-mode to strip the leading indentation. Or you could use the minted `autogobble` option (only available in minted 2.0+), which strips all common leading whitespace before passing code to Pygments.

**Comment by mickyching** [comment]
I'm compile org-mode files with setting org-src-preserve-indentation true, but not set it for edit, so the result has 2-spaces. When set it for edit, then no extra leading indent exists.

I tried autogobble option, It works fine. Thanks.

**Comment by Freed-Wu** [comment]
> Another option would be to create a dummy version of `\fcolorbox` that doesn't do anything. Something like this:
> 
> ```
> \AtBeginEnvironment{minted}{%
>   \renewcommand{\fcolorbox}[4][]{#4}}
> ```

it can only work for `\begin{minted}`, not work for `\inputminted`. if want it work for `\inputminted`, must
```
\documentclass{book}
\usepackage{minted}
\begin{document}
\renewcommand{\fcolorbox}[4][]{#4}
\inputminted{mysql}{lst/main.mysql}
\end{document}
```

i think if can give a option to disable the red box, it will be good, just like

```
\setminted{%
  disabletokenerrfcolorbox
}
```
