### ISSUE TITLE
#include directives are in italics

### ISSUE THREAD

**Issue by elador** [gpoore/minted#71]
First of all, awesome package, thank you very much for developing and maintaining it!

I'm having an issue with the following code:

```
\begin{minted}{c++}
#include <iostream>
int main(void) {}
\end{minted}
```

![image](https://cloud.githubusercontent.com/assets/1831934/7057934/5e47db5c-de53-11e4-9ab0-b746e40e3b3e.png)

The first line with the #include is all displayed in italics. The rest of the code is nicely in code-font. Is there a way to change that?

**Comment by gpoore** [comment]
That's the standard behavior for the `default` highlighting style. You could try a different style. See http://pygments.org/demo to try a quick demo online and get a list of styles (but notice that some details in LaTeX may be a little different, due to how Pygments outputs LaTeX). To change the style in the document, `\setminted{style=<style>}`.

Another option is to disable italics altogether within `minted` environments. You could use something like `\AtBeginEnvironment{minted}{\let\itshape\relax}`.

**Comment by elador** [comment]
Ah, thank you very much for the info. That demo page is great as well.

The behaviour is still a bit odd though: I don't think the behavior of `default` is italics - on the demo page, that code is n code-font as well. So is it for e.g. `native`. But in my latex document, both get displayed as italics. If I choose another style like `vs`, I get non-italic behaviour on both the demo site and in my document.

**Comment by gpoore** [comment]
You're correct, something is strange with the demo page, and `bw` isn't working properly there. Looks like a bug in the site. If you do a web search, you can probably find some (correct) pre-renderd Pygments style galleries.

**Comment by elador** [comment]
Yep, there's a lot more wrong with that demo page than only the `bw` style.

Anyway, so there's no way to disable italics in the default style only for stuff with `#`, and possibly only for C++ codeblocks? (in other languages, `#` may often indicate a comment, but in C++ it's regular code, so I personally would like that in non-italic).

**Comment by gpoore** [comment]
Unfortunately, the [Pygments lexer](https://bitbucket.org/birkenfeld/pygments-main/src/a287342ee7165f50fdd54e3500be48256222cff6/pygments/lexers/c_cpp.py?at=default) treats  preprocessor directives as a *subclass* of comments, which makes this tricky.

There are a couple ways to deal with this. You could create a custom environment for C++ with `\newminted`, and then use the `\AtBeginEnvironment{<new_env>}{\let\itshape\relax}` trick to eliminate italics in the new environment.

Or you could eliminate italics for preprocessor directives directly. Inspired by [this TeX.SE question](http://tex.stackexchange.com/questions/232721/disabling-one-keyword-in-minted), the following code should do what you want. You can put it in the preamble after loading `minted` (it assumes `minted` 2.0). It allows you to treat preprocessor directives as a different type of token. Currently, this will treat `c+cp` (**c**omment:**c**omment.**p**reprocessor) as `s+o` (**s**tring:string.**o**ther). A list of Pygments tokens is [here](http://pygments.org/docs/tokens/). Generally, they are abbreviated to some combination of the first letters in the LaTeX style definitions. I'm not aware of any existing reference; the best way to get the "code" for a particular token is probably just to highlight an example of it and then look at the cached output. Note that if you want to use this for styles other than `default`, you would need to replace `\PYGdefault` with `\PYG<other_style>`.
```latex
\usemintedstyle{default}
\AtBeginEnvironment{minted}{%
  \let\originalPYGdefault\PYGdefault
  \renewcommand{\PYGdefault}[2]{%
    \ifstrequal{#1}{c+cp}%
     {\originalPYGdefault{s+o}{#2}}%
     {\originalPYGdefault{#1}{#2}}%
  }%
}
```

**Comment by elador** [comment]
Aah, wicked. Thank you very much! This works well enough.

**Comment by zhayu** [comment]
yes, I have the same problem, but now I solved by using gpoore's approach.
Adding the following to the preemble do the charm: 
```
\usepackage{minted}
\usepackage{etoolbox}
\usepackage{newunicodechar}
\newtoggle{inminted}
\AtBeginEnvironment{minted}{\let\itshape\relax}
```
Hope this may help you!

**Comment by jendrikw** [comment]
This issue should be fixed with https://github.com/pygments/pygments/pull/1391.
