### ISSUE TITLE
Color of normal text ignored

### ISSUE THREAD

**Issue by klmr** [gpoore/minted#72]
Pygments stylesheets can include [`Text` tokens](http://pygments.org/docs/tokens/). However, these seem to be ignored by minted. In fact, very few stylesheets define a style for this token. Unfortunately, however, I’m using a lexer (`SLexer`) which defines normal identifiers as `Text` (rather than `Name`) and I have made a custom stylesheet which includes a custom colour for `Text`, and need `minted` to use this style.

Here’s an MWE:

```tex
\documentclass{article}
\usepackage{minted}
\usemintedstyle{monokai}

\begin{document}
\begin{minted}{r}
test = 42
\end{minted}
\end{document}
```

The `test` should be rendered in very light gray (`#F8F8F2`) but it’s black.

Is there an easy way of integrating the `Text` token into `minted`? The problem is that the Pygments token type `Text` doesn’t actually correspond to any token type in the output; here’s the code Pygments produces:

```tex
\begin{Verbatim}[commandchars=\\\{\}]
test \PYGmonokai{o}{=} \PYGmonokai{l+m}{42}
\end{Verbatim}
```

Lacking a proper solution, I’d also be happy with a solution which, inside LaTeX, assigns a given colour to the “normal”, unstyled text inside a `minted`/`Verbatim` environment.

**Comment by gpoore** [comment]
I think the end of your text was cut off. If you can add it back, that will give me a better idea regarding workarounds.

**Comment by klmr** [comment]
Oh, no idea how that happened. I added it now.

**Comment by gpoore** [comment]
I think something like this will give you what you need for the "normal" text. My guess is that a proper solution would involve modifying the lexer. As it is, there isn't really anything to work with on the LaTeX side. `xcolor` is automatically loaded by `minted` at the end of the preamble if neither `color` or `xcolor` has been loaded by then, but we need to load it explicitly so that `\definecolor` is available earlier.
```latex
\documentclass{article}
\usepackage{minted}
\usemintedstyle{monokai}

\usepackage{xcolor}
\definecolor{Text}{HTML}{F8F8F2}
\AtBeginEnvironment{minted}{\color{Text}}

\begin{document}
\begin{minted}{r}
test = 42
\end{minted}
\end{document}
````

**Comment by klmr** [comment]
Ah, that’s actually a pretty clean workaround, all things considered. I agree that in the long run the lexer should be modified (it’s pretty basic anyway). It’s just weird that `Text` is a styleable token as far as Pygments is concerned, but minted doesn’t pick this up.

**Comment by gpoore** [comment]
Pygments doesn't apply styling for `Text` in html, either.
```html
<div class="highlight"><pre>test <span class="o">=</span> <span class="m">42</span>
</pre></div>
```

If you look at the `raw` format, you will see that `test` and the following space (` `) are parsed as separate `Text` tokens.
```
Token.Text      'test'
Token.Text      ' '
Token.Operator  '='
Token.Text      ' '
Token.Literal.Number    '42'
Token.Text      '\n'
```
So even if you could style `Text`, you would be limited to things that wouldn't affect whitespace characters (for example, no background colors).

As far as I can tell, in `pygments/formatters/latex.py`, styles are only applied to things that aren't `Token`. In `pygments/token.py` both `Token` and `Text` are mapped to the same short name (`''`, empty string). My guess is that this is pretty hardwired into the Pygments internals. So either applying external formatting, or changing the lexer definition, seem to be the simplest approaches.
