### ISSUE TITLE
TikZ externalization compatibility: only create cache directory if needed, patch or amend docs

### ISSUE THREAD

**Issue by gpoore** [gpoore/minted#73]
Based on [this TeX.SE question](http://tex.stackexchange.com/questions/239780/minted-caching-in-tikz-externalize-job), TikZ externalization and minted caching are inefficient when used together.

* The docs need to be amended to deal with this case. Also, should consider automatically checking for TikZ externalization.
* Caching needs to be modified, so that directories are only created at the last possible moment, once we are *sure* that they will indeed be needed.

**Comment by patrickvogt** [comment]
Hi, is it possible, that this patch introduced problems with the order of the \tikzexternalize and \upepackage{minted} commands? See: http://tex.stackexchange.com/questions/270492/problem-when-loading-minted-after-tikzexternalize

**Comment by gpoore** [comment]
Yes, it looks like there is an issue with the order. In the example case that inspired the fix, `\tikzexternalize` was used after `minted` was loaded. The case you are looking at uses `\tikzexternalize` first. I should be able to modify the check for externalization relatively easily, so that the order doesn't matter.

**Comment by patrickvogt** [comment]
Hi, I think I found a fix for the issue. Maybe you wanna try it:

Expand the following code:

\ifcsname tikzexternalrealjob\endcsname
  \minted@drafttrue
  \minted@cachefalse
\else
\fi

with:

\ifcsname tikzifexternalizing\endcsname
    \tikzifexternalizing{\minted@drafttrue\minted@cachefalse}{}
\else
    \ifcsname tikzexternalrealjob\endcsname
      \minted@drafttrue
      \minted@cachefalse
    \else
    \fi
\fi

\tikzifexternalizing will only be true when the externalization job runs (according to thepackage documentation)

**Comment by gpoore** [comment]
@patrickvogt This is fixed, using your suggestion. If you'd like to be listed in the `minted` acknowledgements for this, let me know, and I'll do that.

**Comment by patrickvogt** [comment]
Hi,

    If you'd like to be listed in the minted acknowledgements for this, let me know, and I'll do that.

This would be cool. Thanks for maintaining and enhancing the minted package. I really like this package.
