### ISSUE TITLE
Linebreaks after opening paren in (\mintinline{clojure}|-0.1|)

### ISSUE THREAD

**Issue by tsdh** [gpoore/minted#77]
Compiling the following minimal document results in a linebreak between an opening paren and the minted-formatted `-0.1`.

I'm not exactly sure what's the culprit, and it has been really hard to reproduce with a MWE.  I suspect the `breakbytoken` option is at least part of the issue.  At least when setting that to `false`, the problem goes away, however that option is very valuable in other cases.

```latex
\documentclass{article}
\usepackage{url}
\usepackage{relsize}
\usepackage{minted}
\setminted{fontsize=\small,breaklines=true,breakbytoken=true,autogobble}
\setmintedinline{fontsize=\relscale{.9},breaklines=true,breakbytoken=true}
\newmintinline{clojure}{}
\newcommand{\code}{\clojureinline}
 
\begin{document}
 
The \emph{Extensible Data Notation}
(\emph{EDN}\footnote{\url{http://edn-format.org}} proposed by
the Clojure author Rich Hickey is a light-weight alternative to XML.  In
essence, EDN is a subset of Clojure data comprising the null value
(\code|nil|), booleans (\code|true| and \code|false|), characters (\code|\x|),
symbols (\code|example|), keywords (\code|:kw|), integers (\code|-17|),
floating point numbers (\code|-0.1|), strings (\code|"a string"|), sets
(\code|#{1 2 3}|), lists (\code|(1 2 3)|), and maps (\code|{1 :one, 2 :one}|).
 
\end{document}
```

**Comment by gpoore** [comment]
This is due to `breakbytoken`.  When `breakbytoken` is on, `\allowbreak{}` is inserted *before* each token. In this case, that's allowing a break between the preceding parenthesis and the start of the code.

The `\allowbreak{}` is *before* the token because if it were afterward, it could under some conditions introduce spurious linebreaks (if I remember correctly). This issue suggests that the simple insertion of an `\allowbreak{}` in any position isn't really sufficient. I will need to look into creating a conditional version of `\allowbreak` that is aware of its surroundings.

**Comment by tsdh** [comment]
Wouldn't it be enough to allow breaks only between tokens but not before the first and after the last? Typically, there's a space before and after a \mintinline anyway with the exceptions of parentheses and punctuation, and there you don't want breaks anyway.

**Comment by gpoore** [comment]
Yes, I think that's the solution. That's why I will need a conditional `\allowbreak`. I think the conditional `\allowbreak` will need to be after each token, and will need to look ahead to see if it is followed by another token. To insert the  `\allowbreak`, I'm modifying the Pygments macros, after all the highlighting has been performed. So I don't have a way to only insert the breaks in some positions. With a conditional break, I can insert breaks everywhere, but only have them actually activate when appropriate.

**Comment by tsdh** [comment]
Sounds good.

**Comment by gpoore** [comment]
This should be fixed now for inline use.

I'm going to leave the issue open for the moment, because I think that the behavior in the environment case can also be improved, but that will require some additional work with the `fancyvrb` internals.

**Comment by tsdh** [comment]
@gpoore Works, thanks.

Now I have a related problem, though.  In the text
```latex
Firstly, there are instants in time in
RFC-3339~\cite{rfc3339} format (\code|#inst "1985-04-12T23:20:50.52Z"|), and
secondly, there are universally unique identifiers (UUID~\cite{rfc4122})
(\code|#uuid "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"|).
```
where `\code` is a shorthand for `\mintinline{clojure}` it is possible that there are line breaks after `#`.  In Clojure, `#` is a valid symbol constituent, so `#inst` and `#uuid` are just one token each.

Would it be possible to let users define what minted considers as token chars (or rather non-token chars)?  I think, in general I'd be happy to have only line breaks at actual whitespace characters.

**Comment by tsdh** [comment]
@gpoore Oh, it seems your latest changes have introduced another problem.  See the attached screenshot.  That's the result of the following latex input:

```latex
The \code|forall?| quantified expression predicate returns true if and only if
\code|(pred el)| returns true for any \code|el| in the collection \code|coll|.

\apidoc{Function}{funnyqt.query}{forall?}|pred coll|

\code|forall?| is short-circuiting, i.e., it stops testing elements and returns
false as soon as the first element not satisfying \code|pred| has been
encountered.  This is an important property in case \code|coll| is a lazy
(possibly infinite) sequence.
```
![screenshot from 2015-05-29 14-13-58](https://cloud.githubusercontent.com/assets/103854/7882378/3c50ffa6-060d-11e5-9486-a57bd063dc7e.png)

**Comment by gpoore** [comment]
As far as I can tell (Pygments 2.0.2), `#inst` is being parsed as `#` (operator) plus `inst` (name:variable). ([Pygments tokens](http://pygments.org/docs/tokens/), [clojure lexer source](https://bitbucket.org/birkenfeld/pygments-main/src/a287342ee7165f50fdd54e3500be48256222cff6/pygments/lexers/jvm.py?at=default).) Ultimately, my guess is that this is a bug/shortcoming in the clojure lexer.

Given the issues like this that I keep seeing with Pygments parsing, by default I may need to only break before tokens preceded by spaces, with an optional setting to break between immediately adjacent tokens. I should have a fix for that soon.

Regarding the undesired newline, that's a bug in `breakbytoken` that goes back to the beginning. It needs a `\leavevmode` before the `\hbox` ([Reference](http://tex.stackexchange.com/questions/109977/doubts-about-hbox-behavior)).

I should have a fix for both very soon.

**Comment by tsdh** [comment]
Thanks!

**Comment by gpoore** [comment]
`breakbytoken` now only breaks at spaces. That was how it was described in the docs, so the existing behavior was inconsistent.

There is a new option `breakbytokenanywhere` that does what `breakbytoken` had been doing, allowing breaks between immediately adjacent characters.

The bug with linebreaks at the beginning of paragraphs is fixed.

**Comment by tsdh** [comment]
Confirmed, it works nicely now.  Thanks a lot!
