### ISSUE TITLE
Allow line breaks anywhere

### ISSUE THREAD

**Issue by gpoore** [gpoore/minted#79]
This is in response to [this TeX.SE question](http://tex.stackexchange.com/questions/251321/break-lines-at-any-character-in-minted).

Current progress:
* `breakanywhere` allows breaks anywhere
* `breakanywheresymbolpre` sets pre-break symbol for these sorts of breaks
* `breakanywheresymbolpost` sets post-break symbol for these sorts of breaks
* `breakanywhereafter` allows breaks anywhere, but only after the specified character(s); currently, this **only** works with `fancyvrb`, and there are reasons that `minted` support will probably always be limited at best (related to Pygments tokenization and macros)
* `breakanywhereaftergroup` groups the characters specified by `breakanywhereafter` when they are adjacent, so that breaks don't occur between them; again, **only** works with `fancyvrb` at present

**Comment by pstroobants** [comment]
Again thanks for implementing this feature.

**Comment by gpoore** [comment]
The last commit for this (2c17520) added Pygments support for the options that were previously `fancyvrb`-only. I believe the extended line breaking features are now complete. No bugs have been reported since that commit, so I am closing this issue.

**Comment by evandrocoan** [comment]
Related to: Linebreaks for a single \mintinline #31
