### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by JohnRobson** [gpoore/minted#80]
If my code indentation use Tabs (and this is very common), minted output the symbol "I".

Should be good if replace tabs by 2 or 4 spaces (maybe set in the options).

**Comment by gpoore** [comment]
Are you using XeTeX?  If so, you need to use the `-8bit` command-line option for tabs to work.

**Comment by JohnRobson** [comment]
Works perfectly, thank you very much.

**Comment by JohnRobson** [comment]
Just one more question, I didn't find, but do you know how can I change the tab spacing? Tks.

**Comment by gpoore** [comment]
You probably want `tabsize`. Depending on what you are doing, you might also want `showtabs` or `obeytabs`.

**Comment by JohnRobson** [comment]
Thank you again, next time I'll check the manual carefully.
