### ISSUE TITLE
`common-lispcode` (or any other) environment is undefined.

### ISSUE THREAD

**Issue by zackp30** [gpoore/minted#83]
When using `minted` with Org-mode (Emacs document/note/whatever format that is fantastic) and when I use it with a simple LaTeX file such as:

```latex
\documentclass[11pt]{article}
\usepackage[cache=false]{minted}

\begin{document}
\begin{pythoncode}
  "hi"
\end{pythoncode}
\end{document}
```

I get something such as:

```
! LaTeX Error: Environment pythoncode undefined.
```

Sorry if the `${LANG}code` is actually Org-mode specific, it's not clear to me if it is or not.

I was curious if #81 was related to this if the code wasn't detecting the list of languages from pygments correctly.

Thanks!

**Comment by gpoore** [comment]
Environments `${LANG}code` are not created by default. You can create whichever ones you need using the `\newminted` command.  In this case, `\newminted{python}{}`.  Note the trailing, empty `{}`. If you wanted to specify default options for the new environment, that's where you would put them.  Also, if you didn't want to call the new environment `pythoncode`, you could give `\newminted` an optional argument. More details are in the docs.

If Org-mode is exporting LaTeX using the `${LANG}code` form, then it should really be creating the corresponding environments automatically by default. But I would think it would really be simpler for it to export standard `minted` environments. I haven't used it, so I can't make any suggestions about configuration.

**Comment by zackp30** [comment]
Okay, thanks! Makes sense. :smile:
