### ISSUE TITLE
MATLAB single quote becomes string after }

### ISSUE THREAD

**Issue by kwlg** [gpoore/minted#86]
In MATLAB, the single quote character means the transpose of a matrix or vector, but it could also be used for strings. If it is used as the transpose after the charachter }, minted treats it as a string and highlights the rest of the code as a string. See the attached image for an example.
![screenshot from 2015-09-21 09-08-02](https://cloud.githubusercontent.com/assets/5015685/9986745/a2b68ea4-6040-11e5-98aa-d191a39abf61.png)

**Comment by gpoore** [comment]
This is actually an issue with Pygments, which `minted` uses internally. There have been issues with Pygments' treatment of the transpose multiple times:

* https://bitbucket.org/birkenfeld/pygments-main/issues/881/matlab-highlighting-inconsistencies-after
* https://bitbucket.org/birkenfeld/pygments-main/issues/1070/transpose-sign-recognized-as-string

Apparently, the fixes still aren't complete enough for your case. I would recommend opening an issue at the [Pygments site](https://bitbucket.org/birkenfeld/pygments-main).
