### ISSUE TITLE
outputdir option with relative path bug

### ISSUE THREAD

**Issue by sebasv** [gpoore/minted#87]
Great package. I found a minor issue that may deserve a place in the documentation: If the minted package is not loaded last, then the current working directory is not guaranteed, therefore relative paths may become invalid, and build files can't be found anymore. 

I came across this issue when loading the `fancybox` package after loading and setting the minted package.

**Comment by gpoore** [comment]
This should be added to the docs. Thanks!

The [`fancybox` and `fancyvrb` packages are incompatible](http://tex.stackexchange.com/questions/39271/error-using-usepackagefancyvrb-fancybox), in the sense that whichever one is loaded last defines a few things about verbatim environments its own way. `minted` requires `fancyvrb`'s way of doing things, so any time `fancybox` is loaded, it must be loaded before `minted` (or before `fancyvrb` is loaded).
