### ISSUE TITLE
whitespace in minted environment produces "^^I"

### ISSUE THREAD

**Issue by Cylox** [gpoore/minted#9]
Using minted 1.7 with pygmentize 1.6:
This code:
    \begin{minted}[fontsize=\footnotesize]{xml}
    <Window x:Class="_2200DatabaseExport.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:_2200DatabaseExport.ViewModel"
        xmlns:v="clr-namespace:_2200DatabaseExport.View"
        Title="2200 Database Export" 
        Width="800" 
        Height="Auto">
        
    </Window>
    \end{minted}
will produce the following output:
![whitespacebug](https://f.cloud.github.com/assets/5357159/1063752/921d04f8-12e3-11e3-8e57-7eff3e2d19d4.JPG)

I'm using windows 7 with miktex 2.9. 
I also have another machine which has minted 1.6 and pygmentize 1.5 installed. The output there is absolutely fine.

**Comment by Ahmedshukr** [comment]
@gpoore Thanks, this helped me.
