### ISSUE TITLE
mathescape and xml language

### ISSUE THREAD

**Issue by koppor** [gpoore/minted#90]
Based on [Reference source code line in minted package](http://tex.stackexchange.com/questions/24945/reference-source-code-line-in-minted-package), I created following minimal example:

```
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[linenos=true, mathescape]{xml}
    i = i + 1 ;  
    j = j + 1 ; // The important line $\label{myline}$
    k = k + 1 ;
\end{minted}
The important line is line \ref{myline}.
\end{document}
```

The content between `$` is not replaced. When I change `xml` to `c++`, everyhting works as described in [the answer](http://tex.stackexchange.com/a/24992/9075).

`Pygments version 2.0.2`, `minted 2.1`.

**Comment by gpoore** [comment]
This shouldn't work, because valid `c++` is not the same as valid `xml`, and Pygments actually tokenizes the code it is given. Have you tried using `mathescape` with an actual sample of `xml`?

**Comment by koppor** [comment]
Sure, this was my original issue and therefore I googled for it. Here a kind of MCVE:

```
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[linenos=true, mathescape]{xml}
<hello> 
text $\label{myline}$
</hello>
\end{minted}
The important line is line \ref{myline}.
\end{document}
```

Other variations like the following also fail:

```
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[linenos=true, mathescape]{xml}
<hello>
$\label{myline}$</hello>
\end{minted}
The important line is line \ref{myline}.
\end{document}
```

**Comment by koppor** [comment]
I get it working with following setting:

```
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[linenos=true, mathescape]{xml}
<hello>
<!--$\label{myline}$-->
</hello>
\end{minted}
The important line is line \ref{myline}.
\end{document}
```

That means, the `mathescape` feature is available at comments only? Why not also in other free text areas (speaking having XML in mind)

**Comment by gpoore** [comment]
You are correct, `mathescape` only works in comments. That's just the way that [Pygments chooses to do it](http://pygments.org/docs/formatters/).

For your case, what you want is `escapeinside`, which allows escaping to LaTeX anywhere (with some limitations due to Pygments current implementation, as noted in the docs). Something like this should do what you want:
```latex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}[linenos=true, escapeinside=||]{xml}
<hello>
|\label{myline}|</hello>
\end{minted}
The important line is line \ref{myline}.
\end{document}
```

**Comment by koppor** [comment]
Thank you.
