### ISSUE TITLE
Difficulty compiling minimal complete example

### ISSUE THREAD

**Issue by nwhetsell** [gpoore/minted#92]
I just updated `minted` to version 2.1, and I’m encountering an issue when attempting to compile the minimal example in the manual:

```tex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{c}
int main() {
  printf("hello, world");
  return 0;
}
\end{minted}
\end{document}
```

When I compile that by running (in Terminal, on OS&nbsp;X)

```sh
pdflatex -shell-escape test.tex
```

compilation fails with

```
! Undefined control sequence.
<argument> \PYGZob 
                   {}
l.2 ...G{n+nf}{main}\PYG{p}{()} \PYG{p}{\PYGZob{}}
```

I have a feeling I’ve done something bone-headed to produce this, but I’m at a loss.

**Comment by gpoore** [comment]
Your example looks fine and works for me. If there is a directory `_minted-test`, you might delete that and try compiling again. Also, you might check that your Pygments version is recent. If it still doesn't work, you could try `\usepackage[cache=false]{minted}` to see if that makes any difference.

**Comment by nwhetsell** [comment]
Deleting `_minted-test` fixed it, don’t know how I didn’t think to try that before. Thanks for your help!

**Comment by tsdh** [comment]
I had that right now with \PYGZgt being the undefined control sequence.  Deleting the cache dir and recompiling did the trick, too.
