### ISSUE TITLE
does minted support all pygments lexers?

### ISSUE THREAD

**Issue by mooreniemi** [gpoore/minted#96]
Running `Pygments version 2.0.2, (c) 2006-2014 by Georg Brandl.` on my machine.

Tried to use minted in TexShop. Works fine for my Ruby code, but for Eiffel it silently fails to output anything (I don't even see any error). This is bog standard Eiffel from [its own documentation](https://docs.eiffel.com/book/method/et-design-contract-tm-assertions-and-exceptions).

```latex
\begin{minted}[mathescape,
               linenos,
               numbersep=5pt,
               gobble=0,
               frame=lines,
               framesep=2mm]{eiffel}
feature -- Element change
 
    deposit (sum: INTEGER)
            -- Add `sum' to account.
        require
            non_negative: sum >= 0
        do
            ... As before ...
        ensure
            one_more_deposit: deposit_count = old deposit_count + 1
            updated: balance = old balance + sum
        end
\end{minted}
```

Using the pygments online highlighter, this highlights just fine. So the problem doesn't appear to be with pygments. Anything I can do to diagnose or fix?

**Comment by gpoore** [comment]
Your example works fine on my machine.

If you can post the complete log for the failed compile, I could take a look.

**Comment by mooreniemi** [comment]
@gpoore I closed TexShop and retried, and it worked fine. Fluke, I guess!
